# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/etienne/Toolbox/visbrain/visbrain/ndviz/interface/gui/ndviz_gui.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1328, 919)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.q_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q_widget.sizePolicy().hasHeightForWidth())
        self.q_widget.setSizePolicy(sizePolicy)
        self.q_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.q_widget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.q_widget.setObjectName("q_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.q_widget)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.QuickSettings = QtWidgets.QTabWidget(self.q_widget)
        self.QuickSettings.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.QuickSettings.setAutoFillBackground(False)
        self.QuickSettings.setMovable(True)
        self.QuickSettings.setObjectName("QuickSettings")
        self.q_UI = QtWidgets.QWidget()
        self.q_UI.setObjectName("q_UI")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.q_UI)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.q_UI)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 328, 147))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self._uiBgdRed = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self._uiBgdRed.setMaximum(1.0)
        self._uiBgdRed.setSingleStep(0.1)
        self._uiBgdRed.setObjectName("_uiBgdRed")
        self.horizontalLayout_8.addWidget(self._uiBgdRed)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self._uiBgdGreen = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self._uiBgdGreen.setMaximum(1.0)
        self._uiBgdGreen.setSingleStep(0.1)
        self._uiBgdGreen.setObjectName("_uiBgdGreen")
        self.horizontalLayout_8.addWidget(self._uiBgdGreen)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self._uiBgdBlue = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self._uiBgdBlue.setMaximum(1.0)
        self._uiBgdBlue.setSingleStep(0.1)
        self._uiBgdBlue.setObjectName("_uiBgdBlue")
        self.horizontalLayout_8.addWidget(self._uiBgdBlue)
        self.verticalLayout_27.addWidget(self.groupBox_5)
        self.groupBox_11 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self._CanVisNd = QtWidgets.QCheckBox(self.groupBox_11)
        self._CanVisNd.setObjectName("_CanVisNd")
        self.gridLayout.addWidget(self._CanVisNd, 0, 0, 1, 1)
        self._CanVis1d = QtWidgets.QCheckBox(self.groupBox_11)
        self._CanVis1d.setObjectName("_CanVis1d")
        self.gridLayout.addWidget(self._CanVis1d, 0, 1, 1, 1)
        self._CanVisIm = QtWidgets.QCheckBox(self.groupBox_11)
        self._CanVisIm.setObjectName("_CanVisIm")
        self.gridLayout.addWidget(self._CanVisIm, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_27.addWidget(self.groupBox_11)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout.addWidget(self.scrollArea_2)
        self.QuickSettings.addTab(self.q_UI, "")
        self.q_Ndplt = QtWidgets.QWidget()
        self.q_Ndplt.setObjectName("q_Ndplt")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.q_Ndplt)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.q_Ndplt)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 344, 902))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self._ndAxShapePan = QtWidgets.QFrame(self.groupBox)
        self._ndAxShapePan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._ndAxShapePan.setFrameShadow(QtWidgets.QFrame.Raised)
        self._ndAxShapePan.setObjectName("_ndAxShapePan")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self._ndAxShapePan)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self._ndAxShape = QtWidgets.QLabel(self._ndAxShapePan)
        self._ndAxShape.setObjectName("_ndAxShape")
        self.horizontalLayout_11.addWidget(self._ndAxShape)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.verticalLayout_7.addWidget(self._ndAxShapePan)
        self._ndAxTimePan = QtWidgets.QWidget(self.groupBox)
        self._ndAxTimePan.setMinimumSize(QtCore.QSize(0, 0))
        self._ndAxTimePan.setObjectName("_ndAxTimePan")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self._ndAxTimePan)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_13 = QtWidgets.QLabel(self._ndAxTimePan)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        self._ndAxTime = QtWidgets.QComboBox(self._ndAxTimePan)
        self._ndAxTime.setObjectName("_ndAxTime")
        self.horizontalLayout_10.addWidget(self._ndAxTime)
        self._ndAx2dSecText = QtWidgets.QLabel(self._ndAxTimePan)
        self._ndAx2dSecText.setObjectName("_ndAx2dSecText")
        self.horizontalLayout_10.addWidget(self._ndAx2dSecText)
        self._ndAx2d = QtWidgets.QComboBox(self._ndAxTimePan)
        self._ndAx2d.setObjectName("_ndAx2d")
        self.horizontalLayout_10.addWidget(self._ndAx2d)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.verticalLayout_7.addWidget(self._ndAxTimePan)
        self._ndAx2DPan = QtWidgets.QWidget(self.groupBox)
        self._ndAx2DPan.setMinimumSize(QtCore.QSize(0, 0))
        self._ndAx2DPan.setObjectName("_ndAx2DPan")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self._ndAx2DPan)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_15 = QtWidgets.QLabel(self._ndAx2DPan)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self._ndAx2dRows = QtWidgets.QSpinBox(self._ndAx2DPan)
        self._ndAx2dRows.setMaximum(100000)
        self._ndAx2dRows.setObjectName("_ndAx2dRows")
        self.horizontalLayout_12.addWidget(self._ndAx2dRows)
        self._ndAx2dCols = QtWidgets.QSpinBox(self._ndAx2DPan)
        self._ndAx2dCols.setMaximum(100000)
        self._ndAx2dCols.setObjectName("_ndAx2dCols")
        self.horizontalLayout_12.addWidget(self._ndAx2dCols)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.verticalLayout_7.addWidget(self._ndAx2DPan)
        self._ndAxNdPan = QtWidgets.QWidget(self.groupBox)
        self._ndAxNdPan.setMinimumSize(QtCore.QSize(0, 0))
        self._ndAxNdPan.setObjectName("_ndAxNdPan")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self._ndAxNdPan)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 9)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self._ndAxNdPan)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self._ndAxNdRows = QtWidgets.QComboBox(self._ndAxNdPan)
        self._ndAxNdRows.setObjectName("_ndAxNdRows")
        self.horizontalLayout_13.addWidget(self._ndAxNdRows)
        self.label_19 = QtWidgets.QLabel(self._ndAxNdPan)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_13.addWidget(self.label_19)
        self._ndAxNdCols = QtWidgets.QComboBox(self._ndAxNdPan)
        self._ndAxNdCols.setObjectName("_ndAxNdCols")
        self.horizontalLayout_13.addWidget(self._ndAxNdCols)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.verticalLayout_7.addWidget(self._ndAxNdPan)
        self._ndAxCheckMsg = QtWidgets.QLabel(self.groupBox)
        self._ndAxCheckMsg.setObjectName("_ndAxCheckMsg")
        self.verticalLayout_7.addWidget(self._ndAxCheckMsg)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self._ndAxUpdate = QtWidgets.QPushButton(self.groupBox)
        self._ndAxUpdate.setObjectName("_ndAxUpdate")
        self.horizontalLayout_7.addWidget(self._ndAxUpdate)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_19.addWidget(self.groupBox)
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_64.setSpacing(0)
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_64.addItem(spacerItem10)
        self.line_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_11.setMinimumSize(QtCore.QSize(200, 0))
        self.line_11.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_64.addWidget(self.line_11)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_64.addItem(spacerItem11)
        self.verticalLayout_19.addLayout(self.horizontalLayout_64)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_coltype = QtWidgets.QLabel(self.widget_2)
        self.label_coltype.setObjectName("label_coltype")
        self.horizontalLayout_3.addWidget(self.label_coltype)
        self._ndColType = QtWidgets.QComboBox(self.widget_2)
        self._ndColType.setObjectName("_ndColType")
        self._ndColType.addItem("")
        self._ndColType.addItem("")
        self._ndColType.addItem("")
        self._ndColType.addItem("")
        self.horizontalLayout_3.addWidget(self._ndColType)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.verticalLayout_2.addWidget(self.widget_2)
        self._ndRndPan = QtWidgets.QWidget(self.groupBox_2)
        self._ndRndPan.setObjectName("_ndRndPan")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self._ndRndPan)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self._ndRndPan)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self._ndRndDynMin = QtWidgets.QDoubleSpinBox(self._ndRndPan)
        self._ndRndDynMin.setMaximum(0.9)
        self._ndRndDynMin.setSingleStep(0.1)
        self._ndRndDynMin.setProperty("value", 0.3)
        self._ndRndDynMin.setObjectName("_ndRndDynMin")
        self.horizontalLayout.addWidget(self._ndRndDynMin)
        self._ndRndDynMax = QtWidgets.QDoubleSpinBox(self._ndRndPan)
        self._ndRndDynMax.setMinimum(0.1)
        self._ndRndDynMax.setMaximum(1.0)
        self._ndRndDynMax.setSingleStep(0.1)
        self._ndRndDynMax.setProperty("value", 0.9)
        self._ndRndDynMax.setObjectName("_ndRndDynMax")
        self.horizontalLayout.addWidget(self._ndRndDynMax)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self._ndRndNew = QtWidgets.QPushButton(self._ndRndPan)
        self._ndRndNew.setObjectName("_ndRndNew")
        self.horizontalLayout.addWidget(self._ndRndNew)
        self.verticalLayout_2.addWidget(self._ndRndPan)
        self._ndUniPan = QtWidgets.QWidget(self.groupBox_2)
        self._ndUniPan.setMinimumSize(QtCore.QSize(0, 0))
        self._ndUniPan.setObjectName("_ndUniPan")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self._ndUniPan)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self._ndUniPan)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self._ndUniColor = QtWidgets.QLineEdit(self._ndUniPan)
        self._ndUniColor.setObjectName("_ndUniColor")
        self.horizontalLayout_6.addWidget(self._ndUniColor)
        self.verticalLayout_2.addWidget(self._ndUniPan)
        self._ndDynText = QtWidgets.QLabel(self.groupBox_2)
        self._ndDynText.setObjectName("_ndDynText")
        self.verticalLayout_2.addWidget(self._ndDynText)
        self.verticalLayout_19.addWidget(self.groupBox_2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem14)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setMinimumSize(QtCore.QSize(200, 0))
        self.line_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_14.addWidget(self.line_2)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem15)
        self.verticalLayout_19.addLayout(self.horizontalLayout_14)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_39.addWidget(self.label_2)
        self._ndRtLaps = QtWidgets.QSpinBox(self.groupBox_3)
        self._ndRtLaps.setMaximum(1000000000)
        self._ndRtLaps.setProperty("value", 1)
        self._ndRtLaps.setObjectName("_ndRtLaps")
        self.horizontalLayout_39.addWidget(self._ndRtLaps)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem16)
        self.verticalLayout_20.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem17)
        self._ndRtStart = QtWidgets.QPushButton(self.groupBox_3)
        self._ndRtStart.setObjectName("_ndRtStart")
        self.horizontalLayout_4.addWidget(self._ndRtStart)
        self._ndRtStop = QtWidgets.QPushButton(self.groupBox_3)
        self._ndRtStop.setObjectName("_ndRtStop")
        self.horizontalLayout_4.addWidget(self._ndRtStop)
        self._ndRtReset = QtWidgets.QPushButton(self.groupBox_3)
        self._ndRtReset.setObjectName("_ndRtReset")
        self.horizontalLayout_4.addWidget(self._ndRtReset)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem18)
        self.verticalLayout_20.addLayout(self.horizontalLayout_4)
        self.verticalLayout_19.addWidget(self.groupBox_3)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_36.setSpacing(0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem19)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_5.setMinimumSize(QtCore.QSize(200, 0))
        self.line_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_36.addWidget(self.line_5)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem20)
        self.verticalLayout_19.addLayout(self.horizontalLayout_36)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setContentsMargins(0, 9, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self._ndSetSpace = QtWidgets.QDoubleSpinBox(self.widget_3)
        self._ndSetSpace.setMinimum(2.0)
        self._ndSetSpace.setMaximum(100.0)
        self._ndSetSpace.setSingleStep(0.1)
        self._ndSetSpace.setObjectName("_ndSetSpace")
        self.horizontalLayout_5.addWidget(self._ndSetSpace)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem21)
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self._ndLineWidth = QtWidgets.QDoubleSpinBox(self.widget_3)
        self._ndLineWidth.setDecimals(1)
        self._ndLineWidth.setMinimum(0.1)
        self._ndLineWidth.setSingleStep(0.1)
        self._ndLineWidth.setProperty("value", 2.0)
        self._ndLineWidth.setObjectName("_ndLineWidth")
        self.horizontalLayout_5.addWidget(self._ndLineWidth)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem22)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.widget = QtWidgets.QWidget(self.groupBox_4)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self._ndScaleX = QtWidgets.QDoubleSpinBox(self.widget)
        self._ndScaleX.setSingleStep(0.1)
        self._ndScaleX.setProperty("value", 1.0)
        self._ndScaleX.setObjectName("_ndScaleX")
        self.horizontalLayout_9.addWidget(self._ndScaleX)
        self._ndScaleY = QtWidgets.QDoubleSpinBox(self.widget)
        self._ndScaleY.setSingleStep(0.1)
        self._ndScaleY.setProperty("value", 1.0)
        self._ndScaleY.setObjectName("_ndScaleY")
        self.horizontalLayout_9.addWidget(self._ndScaleY)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem23)
        self.verticalLayout_6.addWidget(self.widget)
        self.verticalLayout_19.addWidget(self.groupBox_4)
        self.horizontalLayout_95 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_95.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_95.setSpacing(0)
        self.horizontalLayout_95.setObjectName("horizontalLayout_95")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_95.addItem(spacerItem24)
        self.line_18 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_18.setMinimumSize(QtCore.QSize(200, 0))
        self.line_18.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.horizontalLayout_95.addWidget(self.line_18)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_95.addItem(spacerItem25)
        self.verticalLayout_19.addLayout(self.horizontalLayout_95)
        self.groupBox_15 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self._ndXlabEdit = QtWidgets.QLineEdit(self.groupBox_15)
        self._ndXlabEdit.setObjectName("_ndXlabEdit")
        self.gridLayout_3.addWidget(self._ndXlabEdit, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_15)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_15)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 3, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_15)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 2, 0, 1, 1)
        self._ndYlabEdit = QtWidgets.QLineEdit(self.groupBox_15)
        self._ndYlabEdit.setObjectName("_ndYlabEdit")
        self.gridLayout_3.addWidget(self._ndYlabEdit, 3, 1, 1, 1)
        self._ndTitleEdit = QtWidgets.QLineEdit(self.groupBox_15)
        self._ndTitleEdit.setObjectName("_ndTitleEdit")
        self.gridLayout_3.addWidget(self._ndTitleEdit, 1, 1, 1, 1)
        self._ndGridTog = QtWidgets.QCheckBox(self.groupBox_15)
        self._ndGridTog.setObjectName("_ndGridTog")
        self.gridLayout_3.addWidget(self._ndGridTog, 0, 0, 1, 1)
        self.verticalLayout_25.addLayout(self.gridLayout_3)
        self.verticalLayout_19.addWidget(self.groupBox_15)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem26)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.QuickSettings.addTab(self.q_Ndplt, "")
        self.q_1dPlt = QtWidgets.QWidget()
        self.q_1dPlt.setObjectName("q_1dPlt")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.q_1dPlt)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self._1dPltTab = QtWidgets.QTabWidget(self.q_1dPlt)
        self._1dPltTab.setObjectName("_1dPltTab")
        self._1dSigTab = QtWidgets.QWidget()
        self._1dSigTab.setObjectName("_1dSigTab")
        self.verticalLayout_69 = QtWidgets.QVBoxLayout(self._1dSigTab)
        self.verticalLayout_69.setObjectName("verticalLayout_69")
        self.scrollArea_8 = QtWidgets.QScrollArea(self._1dSigTab)
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollArea_8.setObjectName("scrollArea_8")
        self.scrollAreaWidgetContents_9 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(0, 0, 329, 944))
        self.scrollAreaWidgetContents_9.setObjectName("scrollAreaWidgetContents_9")
        self.verticalLayout_59 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_9)
        self.verticalLayout_59.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.groupBox_32 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_9)
        self.groupBox_32.setObjectName("groupBox_32")
        self.verticalLayout_61 = QtWidgets.QVBoxLayout(self.groupBox_32)
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self._ndAxShapePan_6 = QtWidgets.QFrame(self.groupBox_32)
        self._ndAxShapePan_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._ndAxShapePan_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self._ndAxShapePan_6.setObjectName("_ndAxShapePan_6")
        self.horizontalLayout_101 = QtWidgets.QHBoxLayout(self._ndAxShapePan_6)
        self.horizontalLayout_101.setObjectName("horizontalLayout_101")
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_101.addItem(spacerItem27)
        self._1dAxShape = QtWidgets.QLabel(self._ndAxShapePan_6)
        self._1dAxShape.setObjectName("_1dAxShape")
        self.horizontalLayout_101.addWidget(self._1dAxShape)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_101.addItem(spacerItem28)
        self.verticalLayout_61.addWidget(self._ndAxShapePan_6)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem29, 1, 5, 1, 1)
        self.label_97 = QtWidgets.QLabel(self.groupBox_32)
        self.label_97.setObjectName("label_97")
        self.gridLayout_14.addWidget(self.label_97, 1, 0, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.groupBox_32)
        self.label_96.setObjectName("label_96")
        self.gridLayout_14.addWidget(self.label_96, 0, 0, 1, 1)
        self.label_98 = QtWidgets.QLabel(self.groupBox_32)
        self.label_98.setObjectName("label_98")
        self.gridLayout_14.addWidget(self.label_98, 1, 3, 1, 1)
        self._1dAxInd = QtWidgets.QSpinBox(self.groupBox_32)
        self._1dAxInd.setObjectName("_1dAxInd")
        self.gridLayout_14.addWidget(self._1dAxInd, 1, 4, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem30, 1, 2, 1, 1)
        self._1dAxY = QtWidgets.QComboBox(self.groupBox_32)
        self._1dAxY.setObjectName("_1dAxY")
        self.gridLayout_14.addWidget(self._1dAxY, 1, 1, 1, 1)
        self._1dAxX = QtWidgets.QComboBox(self.groupBox_32)
        self._1dAxX.setObjectName("_1dAxX")
        self.gridLayout_14.addWidget(self._1dAxX, 0, 1, 1, 1)
        self.verticalLayout_61.addLayout(self.gridLayout_14)
        self._1dAxCheckTxt = QtWidgets.QLabel(self.groupBox_32)
        self._1dAxCheckTxt.setObjectName("_1dAxCheckTxt")
        self.verticalLayout_61.addWidget(self._1dAxCheckTxt)
        self.verticalLayout_59.addWidget(self.groupBox_32)
        self.horizontalLayout_105 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_105.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_105.setSpacing(0)
        self.horizontalLayout_105.setObjectName("horizontalLayout_105")
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_105.addItem(spacerItem31)
        self.line_19 = QtWidgets.QFrame(self.scrollAreaWidgetContents_9)
        self.line_19.setMinimumSize(QtCore.QSize(200, 0))
        self.line_19.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.horizontalLayout_105.addWidget(self.line_19)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_105.addItem(spacerItem32)
        self.verticalLayout_59.addLayout(self.horizontalLayout_105)
        self.groupBox_33 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_9)
        self.groupBox_33.setObjectName("groupBox_33")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_33)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self._1dPltSpec = QtWidgets.QWidget(self.groupBox_33)
        self._1dPltSpec.setObjectName("_1dPltSpec")
        self.horizontalLayout_104 = QtWidgets.QHBoxLayout(self._1dPltSpec)
        self.horizontalLayout_104.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_104.setObjectName("horizontalLayout_104")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_100 = QtWidgets.QLabel(self._1dPltSpec)
        self.label_100.setObjectName("label_100")
        self.gridLayout_16.addWidget(self.label_100, 0, 0, 1, 1)
        self._1dPltNfft = QtWidgets.QSpinBox(self._1dPltSpec)
        self._1dPltNfft.setMaximum(10000)
        self._1dPltNfft.setSingleStep(32)
        self._1dPltNfft.setProperty("value", 256)
        self._1dPltNfft.setObjectName("_1dPltNfft")
        self.gridLayout_16.addWidget(self._1dPltNfft, 0, 1, 1, 1)
        self._1dPltStep = QtWidgets.QSpinBox(self._1dPltSpec)
        self._1dPltStep.setMaximum(10000)
        self._1dPltStep.setSingleStep(32)
        self._1dPltStep.setProperty("value", 128)
        self._1dPltStep.setObjectName("_1dPltStep")
        self.gridLayout_16.addWidget(self._1dPltStep, 0, 3, 1, 1)
        self.label_102 = QtWidgets.QLabel(self._1dPltSpec)
        self.label_102.setObjectName("label_102")
        self.gridLayout_16.addWidget(self.label_102, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self._1dPltSpec)
        self.label.setObjectName("label")
        self.gridLayout_16.addWidget(self.label, 1, 0, 1, 1)
        self.label_130 = QtWidgets.QLabel(self._1dPltSpec)
        self.label_130.setObjectName("label_130")
        self.gridLayout_16.addWidget(self.label_130, 1, 2, 1, 1)
        self._1dPltfStart = QtWidgets.QDoubleSpinBox(self._1dPltSpec)
        self._1dPltfStart.setMaximum(10000.0)
        self._1dPltfStart.setObjectName("_1dPltfStart")
        self.gridLayout_16.addWidget(self._1dPltfStart, 1, 1, 1, 1)
        self._1dPltfEnd = QtWidgets.QDoubleSpinBox(self._1dPltSpec)
        self._1dPltfEnd.setMaximum(10000.0)
        self._1dPltfEnd.setObjectName("_1dPltfEnd")
        self.gridLayout_16.addWidget(self._1dPltfEnd, 1, 3, 1, 1)
        self.horizontalLayout_104.addLayout(self.gridLayout_16)
        self.gridLayout_12.addWidget(self._1dPltSpec, 3, 0, 1, 1)
        self.horizontalLayout_96 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_96.setContentsMargins(-1, 0, -1, 6)
        self.horizontalLayout_96.setSpacing(6)
        self.horizontalLayout_96.setObjectName("horizontalLayout_96")
        self.label_91 = QtWidgets.QLabel(self.groupBox_33)
        self.label_91.setObjectName("label_91")
        self.horizontalLayout_96.addWidget(self.label_91)
        self._1dPltPick = QtWidgets.QComboBox(self.groupBox_33)
        self._1dPltPick.setObjectName("_1dPltPick")
        self._1dPltPick.addItem("")
        self._1dPltPick.addItem("")
        self._1dPltPick.addItem("")
        self._1dPltPick.addItem("")
        self.horizontalLayout_96.addWidget(self._1dPltPick)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_96.addItem(spacerItem33)
        self.gridLayout_12.addLayout(self.horizontalLayout_96, 0, 0, 1, 1)
        self._1dPltHist = QtWidgets.QWidget(self.groupBox_33)
        self._1dPltHist.setObjectName("_1dPltHist")
        self.horizontalLayout_97 = QtWidgets.QHBoxLayout(self._1dPltHist)
        self.horizontalLayout_97.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_97.setObjectName("horizontalLayout_97")
        self.label_92 = QtWidgets.QLabel(self._1dPltHist)
        self.label_92.setObjectName("label_92")
        self.horizontalLayout_97.addWidget(self.label_92)
        self._1dPltBins = QtWidgets.QSpinBox(self._1dPltHist)
        self._1dPltBins.setMinimum(1)
        self._1dPltBins.setMaximum(10000)
        self._1dPltBins.setProperty("value", 10)
        self._1dPltBins.setObjectName("_1dPltBins")
        self.horizontalLayout_97.addWidget(self._1dPltBins)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_97.addItem(spacerItem34)
        self.gridLayout_12.addWidget(self._1dPltHist, 2, 0, 1, 1)
        self._1dPltLine = QtWidgets.QWidget(self.groupBox_33)
        self._1dPltLine.setObjectName("_1dPltLine")
        self.horizontalLayout_103 = QtWidgets.QHBoxLayout(self._1dPltLine)
        self.horizontalLayout_103.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_103.setObjectName("horizontalLayout_103")
        self.label_99 = QtWidgets.QLabel(self._1dPltLine)
        self.label_99.setObjectName("label_99")
        self.horizontalLayout_103.addWidget(self.label_99)
        self._1dLineWidth = QtWidgets.QDoubleSpinBox(self._1dPltLine)
        self._1dLineWidth.setDecimals(1)
        self._1dLineWidth.setMinimum(0.1)
        self._1dLineWidth.setMaximum(100.0)
        self._1dLineWidth.setSingleStep(0.1)
        self._1dLineWidth.setProperty("value", 1.0)
        self._1dLineWidth.setObjectName("_1dLineWidth")
        self.horizontalLayout_103.addWidget(self._1dLineWidth)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_103.addItem(spacerItem35)
        self.label_101 = QtWidgets.QLabel(self._1dPltLine)
        self.label_101.setObjectName("label_101")
        self.horizontalLayout_103.addWidget(self.label_101)
        self._1dLineMeth = QtWidgets.QComboBox(self._1dPltLine)
        self._1dLineMeth.setObjectName("_1dLineMeth")
        self._1dLineMeth.addItem("")
        self._1dLineMeth.addItem("")
        self.horizontalLayout_103.addWidget(self._1dLineMeth)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_103.addItem(spacerItem36)
        self.gridLayout_12.addWidget(self._1dPltLine, 1, 0, 1, 1)
        self._1dPltMark = QtWidgets.QWidget(self.groupBox_33)
        self._1dPltMark.setObjectName("_1dPltMark")
        self.horizontalLayout_122 = QtWidgets.QHBoxLayout(self._1dPltMark)
        self.horizontalLayout_122.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_122.setObjectName("horizontalLayout_122")
        self.label_120 = QtWidgets.QLabel(self._1dPltMark)
        self.label_120.setObjectName("label_120")
        self.horizontalLayout_122.addWidget(self.label_120)
        self._1dMarkSize = QtWidgets.QDoubleSpinBox(self._1dPltMark)
        self._1dMarkSize.setDecimals(1)
        self._1dMarkSize.setMinimum(0.1)
        self._1dMarkSize.setMaximum(1000.0)
        self._1dMarkSize.setObjectName("_1dMarkSize")
        self.horizontalLayout_122.addWidget(self._1dMarkSize)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_122.addItem(spacerItem37)
        self.gridLayout_12.addWidget(self._1dPltMark, 4, 0, 1, 1)
        self.verticalLayout_59.addWidget(self.groupBox_33)
        self.horizontalLayout_106 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_106.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_106.setSpacing(0)
        self.horizontalLayout_106.setObjectName("horizontalLayout_106")
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_106.addItem(spacerItem38)
        self.line_20 = QtWidgets.QFrame(self.scrollAreaWidgetContents_9)
        self.line_20.setMinimumSize(QtCore.QSize(200, 0))
        self.line_20.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.horizontalLayout_106.addWidget(self.line_20)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_106.addItem(spacerItem39)
        self.verticalLayout_59.addLayout(self.horizontalLayout_106)
        self._1dColBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_9)
        self._1dColBox.setObjectName("_1dColBox")
        self.verticalLayout_60 = QtWidgets.QVBoxLayout(self._1dColBox)
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self._1dColPickType = QtWidgets.QWidget(self._1dColBox)
        self._1dColPickType.setObjectName("_1dColPickType")
        self.horizontalLayout_98 = QtWidgets.QHBoxLayout(self._1dColPickType)
        self.horizontalLayout_98.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_98.setObjectName("horizontalLayout_98")
        self.label_93 = QtWidgets.QLabel(self._1dColPickType)
        self.label_93.setObjectName("label_93")
        self.horizontalLayout_98.addWidget(self.label_93)
        self._1dColType = QtWidgets.QComboBox(self._1dColPickType)
        self._1dColType.setObjectName("_1dColType")
        self._1dColType.addItem("")
        self._1dColType.addItem("")
        self._1dColType.addItem("")
        self._1dColType.addItem("")
        self.horizontalLayout_98.addWidget(self._1dColType)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_98.addItem(spacerItem40)
        self.verticalLayout_60.addWidget(self._1dColPickType)
        self._1dRndPan = QtWidgets.QWidget(self._1dColBox)
        self._1dRndPan.setObjectName("_1dRndPan")
        self.horizontalLayout_99 = QtWidgets.QHBoxLayout(self._1dRndPan)
        self.horizontalLayout_99.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_99.setObjectName("horizontalLayout_99")
        self.label_94 = QtWidgets.QLabel(self._1dRndPan)
        self.label_94.setObjectName("label_94")
        self.horizontalLayout_99.addWidget(self.label_94)
        self._1dRndDynMin = QtWidgets.QDoubleSpinBox(self._1dRndPan)
        self._1dRndDynMin.setMaximum(0.9)
        self._1dRndDynMin.setSingleStep(0.1)
        self._1dRndDynMin.setProperty("value", 0.3)
        self._1dRndDynMin.setObjectName("_1dRndDynMin")
        self.horizontalLayout_99.addWidget(self._1dRndDynMin)
        self._1dRndDynMax = QtWidgets.QDoubleSpinBox(self._1dRndPan)
        self._1dRndDynMax.setMinimum(0.1)
        self._1dRndDynMax.setMaximum(1.0)
        self._1dRndDynMax.setSingleStep(0.1)
        self._1dRndDynMax.setProperty("value", 0.9)
        self._1dRndDynMax.setObjectName("_1dRndDynMax")
        self.horizontalLayout_99.addWidget(self._1dRndDynMax)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_99.addItem(spacerItem41)
        self._1dRndNew = QtWidgets.QPushButton(self._1dRndPan)
        self._1dRndNew.setObjectName("_1dRndNew")
        self.horizontalLayout_99.addWidget(self._1dRndNew)
        self.verticalLayout_60.addWidget(self._1dRndPan)
        self._1dUniPan = QtWidgets.QWidget(self._1dColBox)
        self._1dUniPan.setMinimumSize(QtCore.QSize(0, 0))
        self._1dUniPan.setObjectName("_1dUniPan")
        self.horizontalLayout_100 = QtWidgets.QHBoxLayout(self._1dUniPan)
        self.horizontalLayout_100.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_100.setObjectName("horizontalLayout_100")
        self.label_95 = QtWidgets.QLabel(self._1dUniPan)
        self.label_95.setObjectName("label_95")
        self.horizontalLayout_100.addWidget(self.label_95)
        self._1dUniColor = QtWidgets.QLineEdit(self._1dUniPan)
        self._1dUniColor.setObjectName("_1dUniColor")
        self.horizontalLayout_100.addWidget(self._1dUniColor)
        self.verticalLayout_60.addWidget(self._1dUniPan)
        self._1dDynText = QtWidgets.QLabel(self._1dColBox)
        self._1dDynText.setObjectName("_1dDynText")
        self.verticalLayout_60.addWidget(self._1dDynText)
        self.verticalLayout_59.addWidget(self._1dColBox)
        self.horizontalLayout_118 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_118.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_118.setSpacing(0)
        self.horizontalLayout_118.setObjectName("horizontalLayout_118")
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_118.addItem(spacerItem42)
        self.line_23 = QtWidgets.QFrame(self.scrollAreaWidgetContents_9)
        self.line_23.setMinimumSize(QtCore.QSize(200, 0))
        self.line_23.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.horizontalLayout_118.addWidget(self.line_23)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_118.addItem(spacerItem43)
        self.verticalLayout_59.addLayout(self.horizontalLayout_118)
        self.groupBox_34 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_9)
        self.groupBox_34.setObjectName("groupBox_34")
        self.horizontalLayout_120 = QtWidgets.QHBoxLayout(self.groupBox_34)
        self.horizontalLayout_120.setObjectName("horizontalLayout_120")
        self.label_118 = QtWidgets.QLabel(self.groupBox_34)
        self.label_118.setObjectName("label_118")
        self.horizontalLayout_120.addWidget(self.label_118)
        self._1dInterType = QtWidgets.QComboBox(self.groupBox_34)
        self._1dInterType.setObjectName("_1dInterType")
        self._1dInterType.addItem("")
        self._1dInterType.addItem("")
        self._1dInterType.addItem("")
        self._1dInterType.addItem("")
        self._1dInterType.addItem("")
        self._1dInterType.addItem("")
        self._1dInterType.addItem("")
        self.horizontalLayout_120.addWidget(self._1dInterType)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_120.addItem(spacerItem44)
        self.label_119 = QtWidgets.QLabel(self.groupBox_34)
        self.label_119.setObjectName("label_119")
        self.horizontalLayout_120.addWidget(self.label_119)
        self._1dInterStep = QtWidgets.QDoubleSpinBox(self.groupBox_34)
        self._1dInterStep.setMinimum(0.01)
        self._1dInterStep.setMaximum(0.99)
        self._1dInterStep.setSingleStep(0.1)
        self._1dInterStep.setProperty("value", 0.99)
        self._1dInterStep.setObjectName("_1dInterStep")
        self.horizontalLayout_120.addWidget(self._1dInterStep)
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_120.addItem(spacerItem45)
        self.verticalLayout_59.addWidget(self.groupBox_34)
        self.horizontalLayout_121 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_121.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_121.setSpacing(0)
        self.horizontalLayout_121.setObjectName("horizontalLayout_121")
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_121.addItem(spacerItem46)
        self.line_24 = QtWidgets.QFrame(self.scrollAreaWidgetContents_9)
        self.line_24.setMinimumSize(QtCore.QSize(200, 0))
        self.line_24.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.horizontalLayout_121.addWidget(self.line_24)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_121.addItem(spacerItem47)
        self.verticalLayout_59.addLayout(self.horizontalLayout_121)
        self.groupBox_31 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_9)
        self.groupBox_31.setObjectName("groupBox_31")
        self.verticalLayout_58 = QtWidgets.QVBoxLayout(self.groupBox_31)
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_90 = QtWidgets.QLabel(self.groupBox_31)
        self.label_90.setObjectName("label_90")
        self.gridLayout_10.addWidget(self.label_90, 3, 0, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.groupBox_31)
        self.label_88.setObjectName("label_88")
        self.gridLayout_10.addWidget(self.label_88, 1, 0, 1, 1)
        self.label_89 = QtWidgets.QLabel(self.groupBox_31)
        self.label_89.setObjectName("label_89")
        self.gridLayout_10.addWidget(self.label_89, 2, 0, 1, 1)
        self._1dYlabEdit = QtWidgets.QLineEdit(self.groupBox_31)
        self._1dYlabEdit.setObjectName("_1dYlabEdit")
        self.gridLayout_10.addWidget(self._1dYlabEdit, 3, 1, 1, 1)
        self._1dTitleEdit = QtWidgets.QLineEdit(self.groupBox_31)
        self._1dTitleEdit.setObjectName("_1dTitleEdit")
        self.gridLayout_10.addWidget(self._1dTitleEdit, 1, 1, 1, 1)
        self._1dXlabEdit = QtWidgets.QLineEdit(self.groupBox_31)
        self._1dXlabEdit.setObjectName("_1dXlabEdit")
        self.gridLayout_10.addWidget(self._1dXlabEdit, 2, 1, 1, 1)
        self._1dGridTog = QtWidgets.QCheckBox(self.groupBox_31)
        self._1dGridTog.setObjectName("_1dGridTog")
        self.gridLayout_10.addWidget(self._1dGridTog, 0, 0, 1, 1)
        self.verticalLayout_58.addLayout(self.gridLayout_10)
        self.verticalLayout_59.addWidget(self.groupBox_31)
        spacerItem48 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_59.addItem(spacerItem48)
        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents_9)
        self.verticalLayout_69.addWidget(self.scrollArea_8)
        self._1dPltTab.addTab(self._1dSigTab, "")
        self._2dSigTab = QtWidgets.QWidget()
        self._2dSigTab.setObjectName("_2dSigTab")
        self.verticalLayout_70 = QtWidgets.QVBoxLayout(self._2dSigTab)
        self.verticalLayout_70.setObjectName("verticalLayout_70")
        self.scrollArea_7 = QtWidgets.QScrollArea(self._2dSigTab)
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 304, 255))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.verticalLayout_68 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_8)
        self.verticalLayout_68.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_68.setObjectName("verticalLayout_68")
        self.groupBox_39 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_8)
        self.groupBox_39.setObjectName("groupBox_39")
        self.verticalLayout_67 = QtWidgets.QVBoxLayout(self.groupBox_39)
        self.verticalLayout_67.setObjectName("verticalLayout_67")
        self._ImShapePan = QtWidgets.QFrame(self.groupBox_39)
        self._ImShapePan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._ImShapePan.setFrameShadow(QtWidgets.QFrame.Raised)
        self._ImShapePan.setObjectName("_ImShapePan")
        self.horizontalLayout_102 = QtWidgets.QHBoxLayout(self._ImShapePan)
        self.horizontalLayout_102.setObjectName("horizontalLayout_102")
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_102.addItem(spacerItem49)
        self._imAxShape = QtWidgets.QLabel(self._ImShapePan)
        self._imAxShape.setObjectName("_imAxShape")
        self.horizontalLayout_102.addWidget(self._imAxShape)
        spacerItem50 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_102.addItem(spacerItem50)
        self.verticalLayout_67.addWidget(self._ImShapePan)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem51 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem51, 1, 5, 1, 1)
        self._imAxZ = QtWidgets.QComboBox(self.groupBox_39)
        self._imAxZ.setObjectName("_imAxZ")
        self.gridLayout_15.addWidget(self._imAxZ, 2, 1, 1, 1)
        self.label_126 = QtWidgets.QLabel(self.groupBox_39)
        self.label_126.setObjectName("label_126")
        self.gridLayout_15.addWidget(self.label_126, 1, 0, 1, 1)
        self.label_127 = QtWidgets.QLabel(self.groupBox_39)
        self.label_127.setObjectName("label_127")
        self.gridLayout_15.addWidget(self.label_127, 0, 0, 1, 1)
        self.label_128 = QtWidgets.QLabel(self.groupBox_39)
        self.label_128.setObjectName("label_128")
        self.gridLayout_15.addWidget(self.label_128, 1, 3, 1, 1)
        self._imAxInd = QtWidgets.QSpinBox(self.groupBox_39)
        self._imAxInd.setObjectName("_imAxInd")
        self.gridLayout_15.addWidget(self._imAxInd, 1, 4, 1, 1)
        spacerItem52 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem52, 1, 2, 1, 1)
        self._imAxY = QtWidgets.QComboBox(self.groupBox_39)
        self._imAxY.setObjectName("_imAxY")
        self.gridLayout_15.addWidget(self._imAxY, 1, 1, 1, 1)
        self._imAxZTxt = QtWidgets.QLabel(self.groupBox_39)
        self._imAxZTxt.setObjectName("_imAxZTxt")
        self.gridLayout_15.addWidget(self._imAxZTxt, 2, 0, 1, 1)
        self._imAxX = QtWidgets.QComboBox(self.groupBox_39)
        self._imAxX.setObjectName("_imAxX")
        self.gridLayout_15.addWidget(self._imAxX, 0, 1, 1, 1)
        self.label_129 = QtWidgets.QLabel(self.groupBox_39)
        self.label_129.setObjectName("label_129")
        self.gridLayout_15.addWidget(self.label_129, 0, 3, 1, 1)
        self._imAxIndTxt = QtWidgets.QLabel(self.groupBox_39)
        self._imAxIndTxt.setObjectName("_imAxIndTxt")
        self.gridLayout_15.addWidget(self._imAxIndTxt, 0, 4, 1, 1)
        self.verticalLayout_67.addLayout(self.gridLayout_15)
        self._imAxCheckTxt = QtWidgets.QLabel(self.groupBox_39)
        self._imAxCheckTxt.setObjectName("_imAxCheckTxt")
        self.verticalLayout_67.addWidget(self._imAxCheckTxt)
        spacerItem53 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_67.addItem(spacerItem53)
        self.verticalLayout_68.addWidget(self.groupBox_39)
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_8)
        self.verticalLayout_70.addWidget(self.scrollArea_7)
        self._1dPltTab.addTab(self._2dSigTab, "")
        self.verticalLayout_3.addWidget(self._1dPltTab)
        self.QuickSettings.addTab(self.q_1dPlt, "")
        self.q_Cmap = QtWidgets.QWidget()
        self.q_Cmap.setObjectName("q_Cmap")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.q_Cmap)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.q_Cmap)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 376, 251))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.horizontalLayout_119 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_119.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_119.setObjectName("horizontalLayout_119")
        spacerItem54 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_119.addItem(spacerItem54)
        self.label_125 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_125.setObjectName("label_125")
        self.horizontalLayout_119.addWidget(self.label_125)
        self._cbObjects = QtWidgets.QComboBox(self.scrollAreaWidgetContents_4)
        self._cbObjects.setObjectName("_cbObjects")
        self._cbObjects.addItem("")
        self._cbObjects.addItem("")
        self._cbObjects.addItem("")
        self._cbObjects.addItem("")
        self._cbObjects.addItem("")
        self.horizontalLayout_119.addWidget(self._cbObjects)
        spacerItem55 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_119.addItem(spacerItem55)
        self.verticalLayout_28.addLayout(self.horizontalLayout_119)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_18.addWidget(self.label_10)
        self._cbCmap = QtWidgets.QComboBox(self.scrollAreaWidgetContents_4)
        self._cbCmap.setEditable(False)
        self._cbCmap.setObjectName("_cbCmap")
        self.horizontalLayout_18.addWidget(self._cbCmap)
        self._cbInvert = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self._cbInvert.setObjectName("_cbInvert")
        self.horizontalLayout_18.addWidget(self._cbInvert)
        self._cbAutoScale = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self._cbAutoScale.setObjectName("_cbAutoScale")
        self.horizontalLayout_18.addWidget(self._cbAutoScale)
        spacerItem56 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem56)
        self.verticalLayout_28.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_48.addWidget(self.label_18)
        spacerItem57 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem57)
        self._cbClimMin = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self._cbClimMin.setMinimum(-16777215.0)
        self._cbClimMin.setMaximum(16777215.0)
        self._cbClimMin.setSingleStep(1.0)
        self._cbClimMin.setObjectName("_cbClimMin")
        self.horizontalLayout_48.addWidget(self._cbClimMin)
        spacerItem58 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem58)
        self._cbClimMax = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self._cbClimMax.setMinimum(-16777215.0)
        self._cbClimMax.setMaximum(16777215.0)
        self._cbClimMax.setObjectName("_cbClimMax")
        self.horizontalLayout_48.addWidget(self._cbClimMax)
        spacerItem59 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem59)
        self.verticalLayout_28.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self._cbVminChk = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self._cbVminChk.setObjectName("_cbVminChk")
        self.horizontalLayout_20.addWidget(self._cbVminChk)
        self._cbVmin = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self._cbVmin.setMinimum(-16777215.0)
        self._cbVmin.setMaximum(16777215.0)
        self._cbVmin.setSingleStep(1.0)
        self._cbVmin.setObjectName("_cbVmin")
        self.horizontalLayout_20.addWidget(self._cbVmin)
        spacerItem60 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem60)
        self._cbVmaxChk = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self._cbVmaxChk.setObjectName("_cbVmaxChk")
        self.horizontalLayout_20.addWidget(self._cbVmaxChk)
        self._cbVmax = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self._cbVmax.setMinimum(-16777215.0)
        self._cbVmax.setMaximum(16777215.0)
        self._cbVmax.setObjectName("_cbVmax")
        self.horizontalLayout_20.addWidget(self._cbVmax)
        spacerItem61 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem61)
        self.verticalLayout_28.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.qUnder_txt = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.qUnder_txt.setObjectName("qUnder_txt")
        self.horizontalLayout_21.addWidget(self.qUnder_txt)
        self._cbUnder = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self._cbUnder.setObjectName("_cbUnder")
        self.horizontalLayout_21.addWidget(self._cbUnder)
        self.qOver_txt = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.qOver_txt.setObjectName("qOver_txt")
        self.horizontalLayout_21.addWidget(self.qOver_txt)
        self._cbOver = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self._cbOver.setObjectName("_cbOver")
        self.horizontalLayout_21.addWidget(self._cbOver)
        self.verticalLayout_28.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_25.addWidget(self.label_11)
        self._cbLabel = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self._cbLabel.setObjectName("_cbLabel")
        self.horizontalLayout_25.addWidget(self._cbLabel)
        self.verticalLayout_28.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_63.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_63.setSpacing(0)
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        spacerItem62 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_63.addItem(spacerItem62)
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.line_10.setMinimumSize(QtCore.QSize(200, 0))
        self.line_10.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_63.addWidget(self.line_10)
        spacerItem63 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_63.addItem(spacerItem63)
        self.verticalLayout_28.addLayout(self.horizontalLayout_63)
        self.cbpanel = QtWidgets.QVBoxLayout()
        self.cbpanel.setContentsMargins(-1, 0, -1, 0)
        self.cbpanel.setSpacing(0)
        self.cbpanel.setObjectName("cbpanel")
        spacerItem64 = QtWidgets.QSpacerItem(100, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.cbpanel.addItem(spacerItem64)
        self.verticalLayout_28.addLayout(self.cbpanel)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_23.addWidget(self.scrollArea_3)
        self.colorbar_pan = QtWidgets.QWidget(self.q_Cmap)
        self.colorbar_pan.setMinimumSize(QtCore.QSize(0, 0))
        self.colorbar_pan.setObjectName("colorbar_pan")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout(self.colorbar_pan)
        self.verticalLayout_46.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.verticalLayout_23.addWidget(self.colorbar_pan)
        self.QuickSettings.addTab(self.q_Cmap, "")
        self.verticalLayout_4.addWidget(self.QuickSettings)
        self.horizontalLayout_2.addWidget(self.q_widget)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.MODIFY = QtWidgets.QHBoxLayout()
        self.MODIFY.setContentsMargins(0, 0, 0, 0)
        self.MODIFY.setSpacing(0)
        self.MODIFY.setObjectName("MODIFY")
        spacerItem65 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.MODIFY.addItem(spacerItem65)
        self._NdVizPanel = QtWidgets.QWidget(self.centralwidget)
        self._NdVizPanel.setObjectName("_NdVizPanel")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self._NdVizPanel)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self._NdVizLayout = QtWidgets.QHBoxLayout()
        self._NdVizLayout.setContentsMargins(-1, -1, 0, -1)
        self._NdVizLayout.setSpacing(0)
        self._NdVizLayout.setObjectName("_NdVizLayout")
        self.verticalLayout_17.addLayout(self._NdVizLayout)
        self.MODIFY.addWidget(self._NdVizPanel)
        self._1dVizPanel = QtWidgets.QWidget(self.centralwidget)
        self._1dVizPanel.setObjectName("_1dVizPanel")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self._1dVizPanel)
        self.horizontalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_38.setSpacing(0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self._1dVizLayout = QtWidgets.QHBoxLayout()
        self._1dVizLayout.setContentsMargins(-1, -1, 0, -1)
        self._1dVizLayout.setSpacing(0)
        self._1dVizLayout.setObjectName("_1dVizLayout")
        self.horizontalLayout_38.addLayout(self._1dVizLayout)
        self.MODIFY.addWidget(self._1dVizPanel)
        self.verticalLayout_18.addLayout(self.MODIFY)
        spacerItem66 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_18.addItem(spacerItem66)
        self.horizontalLayout_2.addLayout(self.verticalLayout_18)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1328, 25))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        self.menuDisplay = QtWidgets.QMenu(self.menubar)
        self.menuDisplay.setObjectName("menuDisplay")
        self.menuPanel = QtWidgets.QMenu(self.menuDisplay)
        self.menuPanel.setObjectName("menuPanel")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionCortical_repartition = QtWidgets.QAction(MainWindow)
        self.actionCortical_repartition.setObjectName("actionCortical_repartition")
        self.actionCortical = QtWidgets.QAction(MainWindow)
        self.actionCortical.setObjectName("actionCortical")
        self.actionSagittal = QtWidgets.QAction(MainWindow)
        self.actionSagittal.setObjectName("actionSagittal")
        self.actionAxial = QtWidgets.QAction(MainWindow)
        self.actionAxial.setObjectName("actionAxial")
        self.actionCamera = QtWidgets.QAction(MainWindow)
        self.actionCamera.setObjectName("actionCamera")
        self.actionLeft = QtWidgets.QAction(MainWindow)
        self.actionLeft.setObjectName("actionLeft")
        self.actionRight = QtWidgets.QAction(MainWindow)
        self.actionRight.setObjectName("actionRight")
        self.actionQuick_settings = QtWidgets.QAction(MainWindow)
        self.actionQuick_settings.setCheckable(True)
        self.actionQuick_settings.setObjectName("actionQuick_settings")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionProjection = QtWidgets.QAction(MainWindow)
        self.actionProjection.setObjectName("actionProjection")
        self.actionRepartition = QtWidgets.QAction(MainWindow)
        self.actionRepartition.setObjectName("actionRepartition")
        self.actionShortcuts = QtWidgets.QAction(MainWindow)
        self.actionShortcuts.setCheckable(True)
        self.actionShortcuts.setObjectName("actionShortcuts")
        self.actionUi_settings = QtWidgets.QAction(MainWindow)
        self.actionUi_settings.setCheckable(True)
        self.actionUi_settings.setChecked(False)
        self.actionUi_settings.setObjectName("actionUi_settings")
        self.actionNdPlt = QtWidgets.QAction(MainWindow)
        self.actionNdPlt.setCheckable(True)
        self.actionNdPlt.setObjectName("actionNdPlt")
        self.actionOnedPlt = QtWidgets.QAction(MainWindow)
        self.actionOnedPlt.setCheckable(True)
        self.actionOnedPlt.setObjectName("actionOnedPlt")
        self.actionImage = QtWidgets.QAction(MainWindow)
        self.actionImage.setCheckable(True)
        self.actionImage.setObjectName("actionImage")
        self.actionColormap = QtWidgets.QAction(MainWindow)
        self.actionColormap.setCheckable(True)
        self.actionColormap.setObjectName("actionColormap")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.menuPanel.addAction(self.actionUi_settings)
        self.menuPanel.addAction(self.actionNdPlt)
        self.menuPanel.addAction(self.actionOnedPlt)
        self.menuPanel.addAction(self.actionImage)
        self.menuPanel.addAction(self.actionColormap)
        self.menuDisplay.addAction(self.actionQuick_settings)
        self.menuDisplay.addAction(self.menuPanel.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.menuFiles.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.QuickSettings.setCurrentIndex(1)
        self._1dPltTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self._cbCmap, self._cbInvert)
        MainWindow.setTabOrder(self._cbInvert, self._cbVminChk)
        MainWindow.setTabOrder(self._cbVminChk, self._cbVmin)
        MainWindow.setTabOrder(self._cbVmin, self._cbVmaxChk)
        MainWindow.setTabOrder(self._cbVmaxChk, self._cbVmax)
        MainWindow.setTabOrder(self._cbVmax, self._cbUnder)
        MainWindow.setTabOrder(self._cbUnder, self._cbOver)
        MainWindow.setTabOrder(self._cbOver, self._cbLabel)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ndviz"))
        self.QuickSettings.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Background color"))
        self.label_5.setText(_translate("MainWindow", "Red"))
        self.label_6.setText(_translate("MainWindow", "Green"))
        self.label_7.setText(_translate("MainWindow", "Blue"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Canvas"))
        self._CanVisNd.setText(_translate("MainWindow", "Nd-plot"))
        self._CanVis1d.setText(_translate("MainWindow", "1d-plot"))
        self._CanVisIm.setText(_translate("MainWindow", "Image"))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_UI), _translate("MainWindow", "Settings"))
        self.q_Ndplt.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Axis selection"))
        self._ndAxShape.setText(_translate("MainWindow", "data.shape"))
        self.label_13.setText(_translate("MainWindow", "Time axis :"))
        self._ndAx2dSecText.setText(_translate("MainWindow", "2nd axis :"))
        self.label_15.setText(_translate("MainWindow", "Grid (Rows x Cols):"))
        self.label_14.setText(_translate("MainWindow", "Row axis"))
        self.label_19.setText(_translate("MainWindow", "Col axis"))
        self._ndAxCheckMsg.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic;\">Check message N_rows x N_cols = selected dim</span></p></body></html>"))
        self._ndAxUpdate.setText(_translate("MainWindow", "Update"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Color"))
        self.label_coltype.setText(_translate("MainWindow", "Type"))
        self._ndColType.setItemText(0, _translate("MainWindow", "random"))
        self._ndColType.setItemText(1, _translate("MainWindow", "uniform"))
        self._ndColType.setItemText(2, _translate("MainWindow", "dyn_time"))
        self._ndColType.setItemText(3, _translate("MainWindow", "dyn_minmax"))
        self.label_3.setText(_translate("MainWindow", "Color range"))
        self._ndRndNew.setText(_translate("MainWindow", "New random"))
        self.label_8.setText(_translate("MainWindow", "Color"))
        self._ndDynText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic; color:#ffffff;\">Control signal color using the colormap tab...</span></p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Real time"))
        self.label_2.setText(_translate("MainWindow", "Laps"))
        self._ndRtStart.setText(_translate("MainWindow", "Start"))
        self._ndRtStop.setText(_translate("MainWindow", "Stop"))
        self._ndRtReset.setText(_translate("MainWindow", "Reset"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Settings"))
        self.label_4.setText(_translate("MainWindow", "Space"))
        self.label_9.setText(_translate("MainWindow", "Line width"))
        self.label_12.setText(_translate("MainWindow", "Scale (x, y)"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Info"))
        self.label_16.setText(_translate("MainWindow", "Title"))
        self.label_39.setText(_translate("MainWindow", "Y label"))
        self.label_17.setText(_translate("MainWindow", "X label"))
        self._ndGridTog.setText(_translate("MainWindow", "Grid"))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_Ndplt), _translate("MainWindow", "Nd-Plot"))
        self.groupBox_32.setTitle(_translate("MainWindow", "Axis selection"))
        self._1dAxShape.setText(_translate("MainWindow", "data.shape"))
        self.label_97.setText(_translate("MainWindow", "Y axis"))
        self.label_96.setText(_translate("MainWindow", "X axis"))
        self.label_98.setText(_translate("MainWindow", "Index"))
        self._1dAxCheckTxt.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic;\">All axis must be different...</span></p></body></html>"))
        self.groupBox_33.setTitle(_translate("MainWindow", "Plot"))
        self.label_100.setText(_translate("MainWindow", "nfft"))
        self.label_102.setText(_translate("MainWindow", "Step"))
        self.label.setText(_translate("MainWindow", "f start"))
        self.label_130.setText(_translate("MainWindow", "f end"))
        self.label_91.setText(_translate("MainWindow", "Plot data as"))
        self._1dPltPick.setItemText(0, _translate("MainWindow", "line"))
        self._1dPltPick.setItemText(1, _translate("MainWindow", "histogram"))
        self._1dPltPick.setItemText(2, _translate("MainWindow", "spectrogram"))
        self._1dPltPick.setItemText(3, _translate("MainWindow", "marker"))
        self.label_92.setText(_translate("MainWindow", "Bins"))
        self.label_99.setText(_translate("MainWindow", "Line width"))
        self.label_101.setText(_translate("MainWindow", "Method"))
        self._1dLineMeth.setItemText(0, _translate("MainWindow", "gl"))
        self._1dLineMeth.setItemText(1, _translate("MainWindow", "agg"))
        self.label_120.setText(_translate("MainWindow", "Size"))
        self._1dColBox.setTitle(_translate("MainWindow", "Color"))
        self.label_93.setText(_translate("MainWindow", "Type"))
        self._1dColType.setItemText(0, _translate("MainWindow", "random"))
        self._1dColType.setItemText(1, _translate("MainWindow", "uniform"))
        self._1dColType.setItemText(2, _translate("MainWindow", "dyn_time"))
        self._1dColType.setItemText(3, _translate("MainWindow", "dyn_minmax"))
        self.label_94.setText(_translate("MainWindow", "Color range"))
        self._1dRndNew.setText(_translate("MainWindow", "New random"))
        self.label_95.setText(_translate("MainWindow", "Color"))
        self._1dDynText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic; color:#ffffff;\">Control signal color using the colormap tab...</span></p></body></html>"))
        self.groupBox_34.setTitle(_translate("MainWindow", "Interpolation"))
        self.label_118.setText(_translate("MainWindow", "Type"))
        self._1dInterType.setItemText(0, _translate("MainWindow", "None"))
        self._1dInterType.setItemText(1, _translate("MainWindow", "linear"))
        self._1dInterType.setItemText(2, _translate("MainWindow", "nearest"))
        self._1dInterType.setItemText(3, _translate("MainWindow", "zero"))
        self._1dInterType.setItemText(4, _translate("MainWindow", "slinear"))
        self._1dInterType.setItemText(5, _translate("MainWindow", "quadratic"))
        self._1dInterType.setItemText(6, _translate("MainWindow", "cubic"))
        self.label_119.setText(_translate("MainWindow", "Step"))
        self.groupBox_31.setTitle(_translate("MainWindow", "Info"))
        self.label_90.setText(_translate("MainWindow", "Y label"))
        self.label_88.setText(_translate("MainWindow", "Title"))
        self.label_89.setText(_translate("MainWindow", "X label"))
        self._1dGridTog.setText(_translate("MainWindow", "Grid"))
        self._1dPltTab.setTabText(self._1dPltTab.indexOf(self._1dSigTab), _translate("MainWindow", "1d-Signal"))
        self.groupBox_39.setTitle(_translate("MainWindow", "Axis selection"))
        self._imAxShape.setText(_translate("MainWindow", "data.shape"))
        self.label_126.setText(_translate("MainWindow", "Y axis"))
        self.label_127.setText(_translate("MainWindow", "X axis"))
        self.label_128.setText(_translate("MainWindow", "Index"))
        self._imAxZTxt.setText(_translate("MainWindow", "Z axis"))
        self.label_129.setText(_translate("MainWindow", "Move along"))
        self._imAxIndTxt.setText(_translate("MainWindow", "Z-Axis"))
        self._imAxCheckTxt.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic;\">All axis must be different...</span></p></body></html>"))
        self._1dPltTab.setTabText(self._1dPltTab.indexOf(self._2dSigTab), _translate("MainWindow", "2d-Signal"))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_1dPlt), _translate("MainWindow", "Inspect"))
        self.label_125.setText(_translate("MainWindow", "Object"))
        self._cbObjects.setItemText(0, _translate("MainWindow", "ndplt"))
        self._cbObjects.setItemText(1, _translate("MainWindow", "line"))
        self._cbObjects.setItemText(2, _translate("MainWindow", "marker"))
        self._cbObjects.setItemText(3, _translate("MainWindow", "spectrogram"))
        self._cbObjects.setItemText(4, _translate("MainWindow", "image"))
        self.label_10.setText(_translate("MainWindow", "Colormap"))
        self._cbInvert.setText(_translate("MainWindow", "Invert"))
        self._cbAutoScale.setText(_translate("MainWindow", "Auto-scale"))
        self.label_18.setText(_translate("MainWindow", "clim"))
        self._cbVminChk.setToolTip(_translate("MainWindow", "Every values under vmin will be set to the \"under\" color"))
        self._cbVminChk.setText(_translate("MainWindow", "vmin"))
        self._cbVmaxChk.setText(_translate("MainWindow", "vmax"))
        self.qUnder_txt.setText(_translate("MainWindow", "Under"))
        self.qOver_txt.setText(_translate("MainWindow", "Over"))
        self.label_11.setText(_translate("MainWindow", "Colorbar label: "))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_Cmap), _translate("MainWindow", "Colormap"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files"))
        self.menuDisplay.setTitle(_translate("MainWindow", "Display"))
        self.menuPanel.setTitle(_translate("MainWindow", "Panel"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionCortical_repartition.setText(_translate("MainWindow", "Cortical repartition"))
        self.actionCortical.setText(_translate("MainWindow", "Cortical"))
        self.actionSagittal.setText(_translate("MainWindow", "Sagittal"))
        self.actionAxial.setText(_translate("MainWindow", "Axial"))
        self.actionCamera.setText(_translate("MainWindow", "Camera"))
        self.actionLeft.setText(_translate("MainWindow", "Left"))
        self.actionRight.setText(_translate("MainWindow", "Right"))
        self.actionQuick_settings.setText(_translate("MainWindow", "Quick settings"))
        self.actionQuick_settings.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionProjection.setText(_translate("MainWindow", "Projection"))
        self.actionProjection.setToolTip(_translate("MainWindow", "<html><head/><body><p>Find all vertices under a distance of t_radius with each source and project s_data to the surface</p></body></html>"))
        self.actionProjection.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionRepartition.setText(_translate("MainWindow", "Repartition"))
        self.actionRepartition.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionShortcuts.setText(_translate("MainWindow", "Shortcuts"))
        self.actionShortcuts.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionUi_settings.setText(_translate("MainWindow", "Ui settings"))
        self.actionNdPlt.setText(_translate("MainWindow", "Nd-plot"))
        self.actionOnedPlt.setText(_translate("MainWindow", "1d-plot"))
        self.actionImage.setText(_translate("MainWindow", "Image"))
        self.actionColormap.setText(_translate("MainWindow", "Colormap"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))

