# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/etienne/Toolbox/visbrain/visbrain/ndviz/interface/gui/ndviz_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1328, 919)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 25, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.q_widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q_widget.sizePolicy().hasHeightForWidth())
        self.q_widget.setSizePolicy(sizePolicy)
        self.q_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.q_widget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.q_widget.setObjectName(_fromUtf8("q_widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.q_widget)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.QuickSettings = QtGui.QTabWidget(self.q_widget)
        self.QuickSettings.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.QuickSettings.setAutoFillBackground(False)
        self.QuickSettings.setMovable(True)
        self.QuickSettings.setObjectName(_fromUtf8("QuickSettings"))
        self.q_UI = QtGui.QWidget()
        self.q_UI.setObjectName(_fromUtf8("q_UI"))
        self.verticalLayout = QtGui.QVBoxLayout(self.q_UI)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea_2 = QtGui.QScrollArea(self.q_UI)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 358, 801))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.groupBox_5 = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self._uiBgdRed = QtGui.QDoubleSpinBox(self.groupBox_5)
        self._uiBgdRed.setMaximum(1.0)
        self._uiBgdRed.setSingleStep(0.1)
        self._uiBgdRed.setObjectName(_fromUtf8("_uiBgdRed"))
        self.horizontalLayout_8.addWidget(self._uiBgdRed)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self._uiBgdGreen = QtGui.QDoubleSpinBox(self.groupBox_5)
        self._uiBgdGreen.setMaximum(1.0)
        self._uiBgdGreen.setSingleStep(0.1)
        self._uiBgdGreen.setObjectName(_fromUtf8("_uiBgdGreen"))
        self.horizontalLayout_8.addWidget(self._uiBgdGreen)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self._uiBgdBlue = QtGui.QDoubleSpinBox(self.groupBox_5)
        self._uiBgdBlue.setMaximum(1.0)
        self._uiBgdBlue.setSingleStep(0.1)
        self._uiBgdBlue.setObjectName(_fromUtf8("_uiBgdBlue"))
        self.horizontalLayout_8.addWidget(self._uiBgdBlue)
        self.verticalLayout_27.addWidget(self.groupBox_5)
        self.groupBox_11 = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self._CanVisNd = QtGui.QCheckBox(self.groupBox_11)
        self._CanVisNd.setObjectName(_fromUtf8("_CanVisNd"))
        self.gridLayout.addWidget(self._CanVisNd, 0, 0, 1, 1)
        self._CanVis1d = QtGui.QCheckBox(self.groupBox_11)
        self._CanVis1d.setObjectName(_fromUtf8("_CanVis1d"))
        self.gridLayout.addWidget(self._CanVis1d, 0, 1, 1, 1)
        self._CanVisImage = QtGui.QCheckBox(self.groupBox_11)
        self._CanVisImage.setObjectName(_fromUtf8("_CanVisImage"))
        self.gridLayout.addWidget(self._CanVisImage, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_27.addWidget(self.groupBox_11)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout.addWidget(self.scrollArea_2)
        self.QuickSettings.addTab(self.q_UI, _fromUtf8(""))
        self.q_Ndplt = QtGui.QWidget()
        self.q_Ndplt.setObjectName(_fromUtf8("q_Ndplt"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.q_Ndplt)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.scrollArea = QtGui.QScrollArea(self.q_Ndplt)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -101, 344, 902))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self._ndAxShapePan = QtGui.QFrame(self.groupBox)
        self._ndAxShapePan.setFrameShape(QtGui.QFrame.StyledPanel)
        self._ndAxShapePan.setFrameShadow(QtGui.QFrame.Raised)
        self._ndAxShapePan.setObjectName(_fromUtf8("_ndAxShapePan"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self._ndAxShapePan)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self._ndAxShape = QtGui.QLabel(self._ndAxShapePan)
        self._ndAxShape.setObjectName(_fromUtf8("_ndAxShape"))
        self.horizontalLayout_11.addWidget(self._ndAxShape)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.verticalLayout_7.addWidget(self._ndAxShapePan)
        self._ndAxTimePan = QtGui.QWidget(self.groupBox)
        self._ndAxTimePan.setMinimumSize(QtCore.QSize(0, 0))
        self._ndAxTimePan.setObjectName(_fromUtf8("_ndAxTimePan"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self._ndAxTimePan)
        self.horizontalLayout_10.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_13 = QtGui.QLabel(self._ndAxTimePan)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_10.addWidget(self.label_13)
        self._ndAxTime = QtGui.QComboBox(self._ndAxTimePan)
        self._ndAxTime.setObjectName(_fromUtf8("_ndAxTime"))
        self.horizontalLayout_10.addWidget(self._ndAxTime)
        self._ndAx2dSecText = QtGui.QLabel(self._ndAxTimePan)
        self._ndAx2dSecText.setObjectName(_fromUtf8("_ndAx2dSecText"))
        self.horizontalLayout_10.addWidget(self._ndAx2dSecText)
        self._ndAx2d = QtGui.QComboBox(self._ndAxTimePan)
        self._ndAx2d.setObjectName(_fromUtf8("_ndAx2d"))
        self.horizontalLayout_10.addWidget(self._ndAx2d)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.verticalLayout_7.addWidget(self._ndAxTimePan)
        self._ndAx2DPan = QtGui.QWidget(self.groupBox)
        self._ndAx2DPan.setMinimumSize(QtCore.QSize(0, 0))
        self._ndAx2DPan.setObjectName(_fromUtf8("_ndAx2DPan"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self._ndAx2DPan)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_15 = QtGui.QLabel(self._ndAx2DPan)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_12.addWidget(self.label_15)
        self._ndAx2dRows = QtGui.QSpinBox(self._ndAx2DPan)
        self._ndAx2dRows.setMaximum(100000)
        self._ndAx2dRows.setObjectName(_fromUtf8("_ndAx2dRows"))
        self.horizontalLayout_12.addWidget(self._ndAx2dRows)
        self._ndAx2dCols = QtGui.QSpinBox(self._ndAx2DPan)
        self._ndAx2dCols.setMaximum(100000)
        self._ndAx2dCols.setObjectName(_fromUtf8("_ndAx2dCols"))
        self.horizontalLayout_12.addWidget(self._ndAx2dCols)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.verticalLayout_7.addWidget(self._ndAx2DPan)
        self._ndAxNdPan = QtGui.QWidget(self.groupBox)
        self._ndAxNdPan.setMinimumSize(QtCore.QSize(0, 0))
        self._ndAxNdPan.setObjectName(_fromUtf8("_ndAxNdPan"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self._ndAxNdPan)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 9)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_14 = QtGui.QLabel(self._ndAxNdPan)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_13.addWidget(self.label_14)
        self._ndAxNdRows = QtGui.QComboBox(self._ndAxNdPan)
        self._ndAxNdRows.setObjectName(_fromUtf8("_ndAxNdRows"))
        self.horizontalLayout_13.addWidget(self._ndAxNdRows)
        self.label_19 = QtGui.QLabel(self._ndAxNdPan)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_13.addWidget(self.label_19)
        self._ndAxNdCols = QtGui.QComboBox(self._ndAxNdPan)
        self._ndAxNdCols.setObjectName(_fromUtf8("_ndAxNdCols"))
        self.horizontalLayout_13.addWidget(self._ndAxNdCols)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.verticalLayout_7.addWidget(self._ndAxNdPan)
        self._ndAxCheckMsg = QtGui.QLabel(self.groupBox)
        self._ndAxCheckMsg.setObjectName(_fromUtf8("_ndAxCheckMsg"))
        self.verticalLayout_7.addWidget(self._ndAxCheckMsg)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self._ndAxUpdate = QtGui.QPushButton(self.groupBox)
        self._ndAxUpdate.setObjectName(_fromUtf8("_ndAxUpdate"))
        self.horizontalLayout_7.addWidget(self._ndAxUpdate)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_19.addWidget(self.groupBox)
        self.horizontalLayout_64 = QtGui.QHBoxLayout()
        self.horizontalLayout_64.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_64.setSpacing(0)
        self.horizontalLayout_64.setObjectName(_fromUtf8("horizontalLayout_64"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_64.addItem(spacerItem10)
        self.line_11 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_11.setMinimumSize(QtCore.QSize(200, 0))
        self.line_11.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.horizontalLayout_64.addWidget(self.line_11)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_64.addItem(spacerItem11)
        self.verticalLayout_19.addLayout(self.horizontalLayout_64)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget_2 = QtGui.QWidget(self.groupBox_2)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.widget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self._ndColType = QtGui.QComboBox(self.widget_2)
        self._ndColType.setObjectName(_fromUtf8("_ndColType"))
        self._ndColType.addItem(_fromUtf8(""))
        self._ndColType.addItem(_fromUtf8(""))
        self._ndColType.addItem(_fromUtf8(""))
        self._ndColType.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self._ndColType)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.verticalLayout_2.addWidget(self.widget_2)
        self._ndRndPan = QtGui.QWidget(self.groupBox_2)
        self._ndRndPan.setObjectName(_fromUtf8("_ndRndPan"))
        self.horizontalLayout = QtGui.QHBoxLayout(self._ndRndPan)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self._ndRndPan)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self._ndRndDynMin = QtGui.QDoubleSpinBox(self._ndRndPan)
        self._ndRndDynMin.setMaximum(0.9)
        self._ndRndDynMin.setSingleStep(0.1)
        self._ndRndDynMin.setProperty("value", 0.3)
        self._ndRndDynMin.setObjectName(_fromUtf8("_ndRndDynMin"))
        self.horizontalLayout.addWidget(self._ndRndDynMin)
        self._ndRndDynMax = QtGui.QDoubleSpinBox(self._ndRndPan)
        self._ndRndDynMax.setMinimum(0.1)
        self._ndRndDynMax.setMaximum(1.0)
        self._ndRndDynMax.setSingleStep(0.1)
        self._ndRndDynMax.setProperty("value", 0.9)
        self._ndRndDynMax.setObjectName(_fromUtf8("_ndRndDynMax"))
        self.horizontalLayout.addWidget(self._ndRndDynMax)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self._ndRndNew = QtGui.QPushButton(self._ndRndPan)
        self._ndRndNew.setObjectName(_fromUtf8("_ndRndNew"))
        self.horizontalLayout.addWidget(self._ndRndNew)
        self.verticalLayout_2.addWidget(self._ndRndPan)
        self._ndUniPan = QtGui.QWidget(self.groupBox_2)
        self._ndUniPan.setMinimumSize(QtCore.QSize(0, 0))
        self._ndUniPan.setObjectName(_fromUtf8("_ndUniPan"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self._ndUniPan)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_8 = QtGui.QLabel(self._ndUniPan)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_6.addWidget(self.label_8)
        self._ndUniColor = QtGui.QLineEdit(self._ndUniPan)
        self._ndUniColor.setObjectName(_fromUtf8("_ndUniColor"))
        self.horizontalLayout_6.addWidget(self._ndUniColor)
        self.verticalLayout_2.addWidget(self._ndUniPan)
        self._ndDynText = QtGui.QLabel(self.groupBox_2)
        self._ndDynText.setObjectName(_fromUtf8("_ndDynText"))
        self.verticalLayout_2.addWidget(self._ndDynText)
        self.verticalLayout_19.addWidget(self.groupBox_2)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem14)
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setMinimumSize(QtCore.QSize(200, 0))
        self.line_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_14.addWidget(self.line_2)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem15)
        self.verticalLayout_19.addLayout(self.horizontalLayout_14)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_39.addWidget(self.label_2)
        self._ndRtLaps = QtGui.QSpinBox(self.groupBox_3)
        self._ndRtLaps.setMaximum(1000000000)
        self._ndRtLaps.setProperty("value", 1)
        self._ndRtLaps.setObjectName(_fromUtf8("_ndRtLaps"))
        self.horizontalLayout_39.addWidget(self._ndRtLaps)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem16)
        self.verticalLayout_20.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem17)
        self._ndRtStart = QtGui.QPushButton(self.groupBox_3)
        self._ndRtStart.setObjectName(_fromUtf8("_ndRtStart"))
        self.horizontalLayout_4.addWidget(self._ndRtStart)
        self._ndRtStop = QtGui.QPushButton(self.groupBox_3)
        self._ndRtStop.setObjectName(_fromUtf8("_ndRtStop"))
        self.horizontalLayout_4.addWidget(self._ndRtStop)
        self._ndRtReset = QtGui.QPushButton(self.groupBox_3)
        self._ndRtReset.setObjectName(_fromUtf8("_ndRtReset"))
        self.horizontalLayout_4.addWidget(self._ndRtReset)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem18)
        self.verticalLayout_20.addLayout(self.horizontalLayout_4)
        self.groupBox_2.raise_()
        self.verticalLayout_19.addWidget(self.groupBox_3)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_36.setSpacing(0)
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem19)
        self.line_5 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_5.setMinimumSize(QtCore.QSize(200, 0))
        self.line_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout_36.addWidget(self.line_5)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem20)
        self.verticalLayout_19.addLayout(self.horizontalLayout_36)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.widget_3 = QtGui.QWidget(self.groupBox_4)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setContentsMargins(0, 9, 0, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.widget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self._ndSetSpace = QtGui.QDoubleSpinBox(self.widget_3)
        self._ndSetSpace.setMinimum(2.0)
        self._ndSetSpace.setMaximum(100.0)
        self._ndSetSpace.setSingleStep(0.1)
        self._ndSetSpace.setObjectName(_fromUtf8("_ndSetSpace"))
        self.horizontalLayout_5.addWidget(self._ndSetSpace)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem21)
        self.label_9 = QtGui.QLabel(self.widget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        self._ndLineWidth = QtGui.QDoubleSpinBox(self.widget_3)
        self._ndLineWidth.setDecimals(1)
        self._ndLineWidth.setMinimum(0.1)
        self._ndLineWidth.setSingleStep(0.1)
        self._ndLineWidth.setProperty("value", 2.0)
        self._ndLineWidth.setObjectName(_fromUtf8("_ndLineWidth"))
        self.horizontalLayout_5.addWidget(self._ndLineWidth)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem22)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.widget = QtGui.QWidget(self.groupBox_4)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_9.addWidget(self.label_12)
        self._ndScaleX = QtGui.QDoubleSpinBox(self.widget)
        self._ndScaleX.setSingleStep(0.1)
        self._ndScaleX.setProperty("value", 1.0)
        self._ndScaleX.setObjectName(_fromUtf8("_ndScaleX"))
        self.horizontalLayout_9.addWidget(self._ndScaleX)
        self._ndScaleY = QtGui.QDoubleSpinBox(self.widget)
        self._ndScaleY.setSingleStep(0.1)
        self._ndScaleY.setProperty("value", 1.0)
        self._ndScaleY.setObjectName(_fromUtf8("_ndScaleY"))
        self.horizontalLayout_9.addWidget(self._ndScaleY)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem23)
        self.verticalLayout_6.addWidget(self.widget)
        self.verticalLayout_19.addWidget(self.groupBox_4)
        self.horizontalLayout_95 = QtGui.QHBoxLayout()
        self.horizontalLayout_95.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_95.setSpacing(0)
        self.horizontalLayout_95.setObjectName(_fromUtf8("horizontalLayout_95"))
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_95.addItem(spacerItem24)
        self.line_18 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_18.setMinimumSize(QtCore.QSize(200, 0))
        self.line_18.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.horizontalLayout_95.addWidget(self.line_18)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_95.addItem(spacerItem25)
        self.verticalLayout_19.addLayout(self.horizontalLayout_95)
        self.groupBox_15 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self._ndXlabEdit = QtGui.QLineEdit(self.groupBox_15)
        self._ndXlabEdit.setObjectName(_fromUtf8("_ndXlabEdit"))
        self.gridLayout_3.addWidget(self._ndXlabEdit, 2, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_15)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_39 = QtGui.QLabel(self.groupBox_15)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_3.addWidget(self.label_39, 3, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_15)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 2, 0, 1, 1)
        self._ndYlabEdit = QtGui.QLineEdit(self.groupBox_15)
        self._ndYlabEdit.setObjectName(_fromUtf8("_ndYlabEdit"))
        self.gridLayout_3.addWidget(self._ndYlabEdit, 3, 1, 1, 1)
        self._ndTitleEdit = QtGui.QLineEdit(self.groupBox_15)
        self._ndTitleEdit.setObjectName(_fromUtf8("_ndTitleEdit"))
        self.gridLayout_3.addWidget(self._ndTitleEdit, 1, 1, 1, 1)
        self._ndGridTog = QtGui.QCheckBox(self.groupBox_15)
        self._ndGridTog.setObjectName(_fromUtf8("_ndGridTog"))
        self.gridLayout_3.addWidget(self._ndGridTog, 0, 0, 1, 1)
        self.verticalLayout_25.addLayout(self.gridLayout_3)
        self.verticalLayout_19.addWidget(self.groupBox_15)
        spacerItem26 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem26)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.QuickSettings.addTab(self.q_Ndplt, _fromUtf8(""))
        self.q_SglPlt = QtGui.QWidget()
        self.q_SglPlt.setObjectName(_fromUtf8("q_SglPlt"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.q_SglPlt)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.scrollArea_8 = QtGui.QScrollArea(self.q_SglPlt)
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollArea_8.setObjectName(_fromUtf8("scrollArea_8"))
        self.scrollAreaWidgetContents_9 = QtGui.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(-5, 0, 363, 835))
        self.scrollAreaWidgetContents_9.setObjectName(_fromUtf8("scrollAreaWidgetContents_9"))
        self.verticalLayout_59 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_9)
        self.verticalLayout_59.setObjectName(_fromUtf8("verticalLayout_59"))
        self.groupBox_32 = QtGui.QGroupBox(self.scrollAreaWidgetContents_9)
        self.groupBox_32.setObjectName(_fromUtf8("groupBox_32"))
        self.verticalLayout_61 = QtGui.QVBoxLayout(self.groupBox_32)
        self.verticalLayout_61.setObjectName(_fromUtf8("verticalLayout_61"))
        self._ndAxShapePan_6 = QtGui.QFrame(self.groupBox_32)
        self._ndAxShapePan_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self._ndAxShapePan_6.setFrameShadow(QtGui.QFrame.Raised)
        self._ndAxShapePan_6.setObjectName(_fromUtf8("_ndAxShapePan_6"))
        self.horizontalLayout_101 = QtGui.QHBoxLayout(self._ndAxShapePan_6)
        self.horizontalLayout_101.setObjectName(_fromUtf8("horizontalLayout_101"))
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_101.addItem(spacerItem27)
        self._1dAxShape = QtGui.QLabel(self._ndAxShapePan_6)
        self._1dAxShape.setObjectName(_fromUtf8("_1dAxShape"))
        self.horizontalLayout_101.addWidget(self._1dAxShape)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_101.addItem(spacerItem28)
        self.verticalLayout_61.addWidget(self._ndAxShapePan_6)
        self.horizontalLayout_102 = QtGui.QHBoxLayout()
        self.horizontalLayout_102.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_102.setSpacing(2)
        self.horizontalLayout_102.setObjectName(_fromUtf8("horizontalLayout_102"))
        self.label_96 = QtGui.QLabel(self.groupBox_32)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.horizontalLayout_102.addWidget(self.label_96)
        self._1dAxX = QtGui.QComboBox(self.groupBox_32)
        self._1dAxX.setObjectName(_fromUtf8("_1dAxX"))
        self.horizontalLayout_102.addWidget(self._1dAxX)
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_102.addItem(spacerItem29)
        self.label_97 = QtGui.QLabel(self.groupBox_32)
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.horizontalLayout_102.addWidget(self.label_97)
        self._1dAxY = QtGui.QComboBox(self.groupBox_32)
        self._1dAxY.setObjectName(_fromUtf8("_1dAxY"))
        self.horizontalLayout_102.addWidget(self._1dAxY)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_102.addItem(spacerItem30)
        self.label_98 = QtGui.QLabel(self.groupBox_32)
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.horizontalLayout_102.addWidget(self.label_98)
        self._1dAxInd = QtGui.QSpinBox(self.groupBox_32)
        self._1dAxInd.setObjectName(_fromUtf8("_1dAxInd"))
        self.horizontalLayout_102.addWidget(self._1dAxInd)
        self.verticalLayout_61.addLayout(self.horizontalLayout_102)
        self.horizontalLayout_119 = QtGui.QHBoxLayout()
        self.horizontalLayout_119.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_119.setObjectName(_fromUtf8("horizontalLayout_119"))
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_119.addItem(spacerItem31)
        self._1dAxUpdate = QtGui.QPushButton(self.groupBox_32)
        self._1dAxUpdate.setObjectName(_fromUtf8("_1dAxUpdate"))
        self.horizontalLayout_119.addWidget(self._1dAxUpdate)
        spacerItem32 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_119.addItem(spacerItem32)
        self.verticalLayout_61.addLayout(self.horizontalLayout_119)
        self.verticalLayout_59.addWidget(self.groupBox_32)
        self.horizontalLayout_105 = QtGui.QHBoxLayout()
        self.horizontalLayout_105.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_105.setSpacing(0)
        self.horizontalLayout_105.setObjectName(_fromUtf8("horizontalLayout_105"))
        spacerItem33 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_105.addItem(spacerItem33)
        self.line_19 = QtGui.QFrame(self.scrollAreaWidgetContents_9)
        self.line_19.setMinimumSize(QtCore.QSize(200, 0))
        self.line_19.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.horizontalLayout_105.addWidget(self.line_19)
        spacerItem34 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_105.addItem(spacerItem34)
        self.verticalLayout_59.addLayout(self.horizontalLayout_105)
        self.groupBox_33 = QtGui.QGroupBox(self.scrollAreaWidgetContents_9)
        self.groupBox_33.setObjectName(_fromUtf8("groupBox_33"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_33)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.horizontalLayout_96 = QtGui.QHBoxLayout()
        self.horizontalLayout_96.setContentsMargins(-1, 0, -1, 6)
        self.horizontalLayout_96.setSpacing(6)
        self.horizontalLayout_96.setObjectName(_fromUtf8("horizontalLayout_96"))
        self.label_91 = QtGui.QLabel(self.groupBox_33)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.horizontalLayout_96.addWidget(self.label_91)
        self._1dPltPick = QtGui.QComboBox(self.groupBox_33)
        self._1dPltPick.setObjectName(_fromUtf8("_1dPltPick"))
        self._1dPltPick.addItem(_fromUtf8(""))
        self._1dPltPick.addItem(_fromUtf8(""))
        self._1dPltPick.addItem(_fromUtf8(""))
        self.horizontalLayout_96.addWidget(self._1dPltPick)
        spacerItem35 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_96.addItem(spacerItem35)
        self.gridLayout_12.addLayout(self.horizontalLayout_96, 0, 0, 1, 1)
        self._1dPltHist = QtGui.QWidget(self.groupBox_33)
        self._1dPltHist.setObjectName(_fromUtf8("_1dPltHist"))
        self.horizontalLayout_97 = QtGui.QHBoxLayout(self._1dPltHist)
        self.horizontalLayout_97.setMargin(0)
        self.horizontalLayout_97.setObjectName(_fromUtf8("horizontalLayout_97"))
        self.label_92 = QtGui.QLabel(self._1dPltHist)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.horizontalLayout_97.addWidget(self.label_92)
        self._1dPltBins = QtGui.QSpinBox(self._1dPltHist)
        self._1dPltBins.setMinimum(1)
        self._1dPltBins.setMaximum(10000)
        self._1dPltBins.setProperty("value", 10)
        self._1dPltBins.setObjectName(_fromUtf8("_1dPltBins"))
        self.horizontalLayout_97.addWidget(self._1dPltBins)
        spacerItem36 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_97.addItem(spacerItem36)
        self.gridLayout_12.addWidget(self._1dPltHist, 2, 0, 1, 1)
        self._1dPltLine = QtGui.QWidget(self.groupBox_33)
        self._1dPltLine.setObjectName(_fromUtf8("_1dPltLine"))
        self.horizontalLayout_103 = QtGui.QHBoxLayout(self._1dPltLine)
        self.horizontalLayout_103.setMargin(0)
        self.horizontalLayout_103.setObjectName(_fromUtf8("horizontalLayout_103"))
        self.label_99 = QtGui.QLabel(self._1dPltLine)
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.horizontalLayout_103.addWidget(self.label_99)
        self._1dLineWidth = QtGui.QDoubleSpinBox(self._1dPltLine)
        self._1dLineWidth.setDecimals(1)
        self._1dLineWidth.setMinimum(0.1)
        self._1dLineWidth.setMaximum(100.0)
        self._1dLineWidth.setSingleStep(0.1)
        self._1dLineWidth.setProperty("value", 1.0)
        self._1dLineWidth.setObjectName(_fromUtf8("_1dLineWidth"))
        self.horizontalLayout_103.addWidget(self._1dLineWidth)
        spacerItem37 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_103.addItem(spacerItem37)
        self.label_101 = QtGui.QLabel(self._1dPltLine)
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.horizontalLayout_103.addWidget(self.label_101)
        self._1dLineMeth = QtGui.QComboBox(self._1dPltLine)
        self._1dLineMeth.setObjectName(_fromUtf8("_1dLineMeth"))
        self._1dLineMeth.addItem(_fromUtf8(""))
        self._1dLineMeth.addItem(_fromUtf8(""))
        self.horizontalLayout_103.addWidget(self._1dLineMeth)
        spacerItem38 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_103.addItem(spacerItem38)
        self.gridLayout_12.addWidget(self._1dPltLine, 1, 0, 1, 1)
        self._1dPltSpec = QtGui.QWidget(self.groupBox_33)
        self._1dPltSpec.setObjectName(_fromUtf8("_1dPltSpec"))
        self.horizontalLayout_104 = QtGui.QHBoxLayout(self._1dPltSpec)
        self.horizontalLayout_104.setMargin(0)
        self.horizontalLayout_104.setObjectName(_fromUtf8("horizontalLayout_104"))
        self.label_100 = QtGui.QLabel(self._1dPltSpec)
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.horizontalLayout_104.addWidget(self.label_100)
        self._1dPltNfft = QtGui.QSpinBox(self._1dPltSpec)
        self._1dPltNfft.setMaximum(10000)
        self._1dPltNfft.setSingleStep(32)
        self._1dPltNfft.setProperty("value", 256)
        self._1dPltNfft.setObjectName(_fromUtf8("_1dPltNfft"))
        self.horizontalLayout_104.addWidget(self._1dPltNfft)
        self.label_102 = QtGui.QLabel(self._1dPltSpec)
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.horizontalLayout_104.addWidget(self.label_102)
        self._1dPltStep = QtGui.QSpinBox(self._1dPltSpec)
        self._1dPltStep.setMaximum(10000)
        self._1dPltStep.setSingleStep(32)
        self._1dPltStep.setProperty("value", 128)
        self._1dPltStep.setObjectName(_fromUtf8("_1dPltStep"))
        self.horizontalLayout_104.addWidget(self._1dPltStep)
        spacerItem39 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_104.addItem(spacerItem39)
        self.gridLayout_12.addWidget(self._1dPltSpec, 3, 0, 1, 1)
        self.verticalLayout_59.addWidget(self.groupBox_33)
        self.horizontalLayout_106 = QtGui.QHBoxLayout()
        self.horizontalLayout_106.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_106.setSpacing(0)
        self.horizontalLayout_106.setObjectName(_fromUtf8("horizontalLayout_106"))
        spacerItem40 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_106.addItem(spacerItem40)
        self.line_20 = QtGui.QFrame(self.scrollAreaWidgetContents_9)
        self.line_20.setMinimumSize(QtCore.QSize(200, 0))
        self.line_20.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.horizontalLayout_106.addWidget(self.line_20)
        spacerItem41 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_106.addItem(spacerItem41)
        self.verticalLayout_59.addLayout(self.horizontalLayout_106)
        self._1dColBox = QtGui.QGroupBox(self.scrollAreaWidgetContents_9)
        self._1dColBox.setObjectName(_fromUtf8("_1dColBox"))
        self.verticalLayout_60 = QtGui.QVBoxLayout(self._1dColBox)
        self.verticalLayout_60.setObjectName(_fromUtf8("verticalLayout_60"))
        self._1dColPickType = QtGui.QWidget(self._1dColBox)
        self._1dColPickType.setObjectName(_fromUtf8("_1dColPickType"))
        self.horizontalLayout_98 = QtGui.QHBoxLayout(self._1dColPickType)
        self.horizontalLayout_98.setMargin(0)
        self.horizontalLayout_98.setObjectName(_fromUtf8("horizontalLayout_98"))
        self.label_93 = QtGui.QLabel(self._1dColPickType)
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.horizontalLayout_98.addWidget(self.label_93)
        self._1dColType = QtGui.QComboBox(self._1dColPickType)
        self._1dColType.setObjectName(_fromUtf8("_1dColType"))
        self._1dColType.addItem(_fromUtf8(""))
        self._1dColType.addItem(_fromUtf8(""))
        self._1dColType.addItem(_fromUtf8(""))
        self._1dColType.addItem(_fromUtf8(""))
        self.horizontalLayout_98.addWidget(self._1dColType)
        spacerItem42 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_98.addItem(spacerItem42)
        self.verticalLayout_60.addWidget(self._1dColPickType)
        self._1dRndPan = QtGui.QWidget(self._1dColBox)
        self._1dRndPan.setObjectName(_fromUtf8("_1dRndPan"))
        self.horizontalLayout_99 = QtGui.QHBoxLayout(self._1dRndPan)
        self.horizontalLayout_99.setMargin(0)
        self.horizontalLayout_99.setObjectName(_fromUtf8("horizontalLayout_99"))
        self.label_94 = QtGui.QLabel(self._1dRndPan)
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.horizontalLayout_99.addWidget(self.label_94)
        self._1dRndDynMin = QtGui.QDoubleSpinBox(self._1dRndPan)
        self._1dRndDynMin.setMaximum(0.9)
        self._1dRndDynMin.setSingleStep(0.1)
        self._1dRndDynMin.setProperty("value", 0.3)
        self._1dRndDynMin.setObjectName(_fromUtf8("_1dRndDynMin"))
        self.horizontalLayout_99.addWidget(self._1dRndDynMin)
        self._1dRndDynMax = QtGui.QDoubleSpinBox(self._1dRndPan)
        self._1dRndDynMax.setMinimum(0.1)
        self._1dRndDynMax.setMaximum(1.0)
        self._1dRndDynMax.setSingleStep(0.1)
        self._1dRndDynMax.setProperty("value", 0.9)
        self._1dRndDynMax.setObjectName(_fromUtf8("_1dRndDynMax"))
        self.horizontalLayout_99.addWidget(self._1dRndDynMax)
        spacerItem43 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_99.addItem(spacerItem43)
        self._1dRndNew = QtGui.QPushButton(self._1dRndPan)
        self._1dRndNew.setObjectName(_fromUtf8("_1dRndNew"))
        self.horizontalLayout_99.addWidget(self._1dRndNew)
        self.verticalLayout_60.addWidget(self._1dRndPan)
        self._1dUniPan = QtGui.QWidget(self._1dColBox)
        self._1dUniPan.setMinimumSize(QtCore.QSize(0, 0))
        self._1dUniPan.setObjectName(_fromUtf8("_1dUniPan"))
        self.horizontalLayout_100 = QtGui.QHBoxLayout(self._1dUniPan)
        self.horizontalLayout_100.setMargin(0)
        self.horizontalLayout_100.setObjectName(_fromUtf8("horizontalLayout_100"))
        self.label_95 = QtGui.QLabel(self._1dUniPan)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.horizontalLayout_100.addWidget(self.label_95)
        self._1dUniColor = QtGui.QLineEdit(self._1dUniPan)
        self._1dUniColor.setObjectName(_fromUtf8("_1dUniColor"))
        self.horizontalLayout_100.addWidget(self._1dUniColor)
        self.verticalLayout_60.addWidget(self._1dUniPan)
        self._1dDynText = QtGui.QLabel(self._1dColBox)
        self._1dDynText.setObjectName(_fromUtf8("_1dDynText"))
        self.verticalLayout_60.addWidget(self._1dDynText)
        self.verticalLayout_59.addWidget(self._1dColBox)
        self.horizontalLayout_118 = QtGui.QHBoxLayout()
        self.horizontalLayout_118.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_118.setSpacing(0)
        self.horizontalLayout_118.setObjectName(_fromUtf8("horizontalLayout_118"))
        spacerItem44 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_118.addItem(spacerItem44)
        self.line_23 = QtGui.QFrame(self.scrollAreaWidgetContents_9)
        self.line_23.setMinimumSize(QtCore.QSize(200, 0))
        self.line_23.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_23.setFrameShape(QtGui.QFrame.HLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.horizontalLayout_118.addWidget(self.line_23)
        spacerItem45 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_118.addItem(spacerItem45)
        self.verticalLayout_59.addLayout(self.horizontalLayout_118)
        self.groupBox_34 = QtGui.QGroupBox(self.scrollAreaWidgetContents_9)
        self.groupBox_34.setObjectName(_fromUtf8("groupBox_34"))
        self.horizontalLayout_120 = QtGui.QHBoxLayout(self.groupBox_34)
        self.horizontalLayout_120.setObjectName(_fromUtf8("horizontalLayout_120"))
        self.label_118 = QtGui.QLabel(self.groupBox_34)
        self.label_118.setObjectName(_fromUtf8("label_118"))
        self.horizontalLayout_120.addWidget(self.label_118)
        self._1dInterType = QtGui.QComboBox(self.groupBox_34)
        self._1dInterType.setObjectName(_fromUtf8("_1dInterType"))
        self._1dInterType.addItem(_fromUtf8(""))
        self._1dInterType.addItem(_fromUtf8(""))
        self._1dInterType.addItem(_fromUtf8(""))
        self._1dInterType.addItem(_fromUtf8(""))
        self._1dInterType.addItem(_fromUtf8(""))
        self._1dInterType.addItem(_fromUtf8(""))
        self._1dInterType.addItem(_fromUtf8(""))
        self.horizontalLayout_120.addWidget(self._1dInterType)
        spacerItem46 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_120.addItem(spacerItem46)
        self.label_119 = QtGui.QLabel(self.groupBox_34)
        self.label_119.setObjectName(_fromUtf8("label_119"))
        self.horizontalLayout_120.addWidget(self.label_119)
        self._1dInterStep = QtGui.QDoubleSpinBox(self.groupBox_34)
        self._1dInterStep.setMaximum(1.0)
        self._1dInterStep.setSingleStep(0.1)
        self._1dInterStep.setProperty("value", 1.0)
        self._1dInterStep.setObjectName(_fromUtf8("_1dInterStep"))
        self.horizontalLayout_120.addWidget(self._1dInterStep)
        spacerItem47 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_120.addItem(spacerItem47)
        self.verticalLayout_59.addWidget(self.groupBox_34)
        self.horizontalLayout_121 = QtGui.QHBoxLayout()
        self.horizontalLayout_121.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_121.setSpacing(0)
        self.horizontalLayout_121.setObjectName(_fromUtf8("horizontalLayout_121"))
        spacerItem48 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_121.addItem(spacerItem48)
        self.line_24 = QtGui.QFrame(self.scrollAreaWidgetContents_9)
        self.line_24.setMinimumSize(QtCore.QSize(200, 0))
        self.line_24.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_24.setFrameShape(QtGui.QFrame.HLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.horizontalLayout_121.addWidget(self.line_24)
        spacerItem49 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_121.addItem(spacerItem49)
        self.verticalLayout_59.addLayout(self.horizontalLayout_121)
        self.groupBox_31 = QtGui.QGroupBox(self.scrollAreaWidgetContents_9)
        self.groupBox_31.setObjectName(_fromUtf8("groupBox_31"))
        self.verticalLayout_58 = QtGui.QVBoxLayout(self.groupBox_31)
        self.verticalLayout_58.setObjectName(_fromUtf8("verticalLayout_58"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_90 = QtGui.QLabel(self.groupBox_31)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.gridLayout_10.addWidget(self.label_90, 3, 0, 1, 1)
        self.label_88 = QtGui.QLabel(self.groupBox_31)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.gridLayout_10.addWidget(self.label_88, 1, 0, 1, 1)
        self.label_89 = QtGui.QLabel(self.groupBox_31)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.gridLayout_10.addWidget(self.label_89, 2, 0, 1, 1)
        self._1dYlabEdit = QtGui.QLineEdit(self.groupBox_31)
        self._1dYlabEdit.setObjectName(_fromUtf8("_1dYlabEdit"))
        self.gridLayout_10.addWidget(self._1dYlabEdit, 3, 1, 1, 1)
        self._1dTitleEdit = QtGui.QLineEdit(self.groupBox_31)
        self._1dTitleEdit.setObjectName(_fromUtf8("_1dTitleEdit"))
        self.gridLayout_10.addWidget(self._1dTitleEdit, 1, 1, 1, 1)
        self._1dXlabEdit = QtGui.QLineEdit(self.groupBox_31)
        self._1dXlabEdit.setObjectName(_fromUtf8("_1dXlabEdit"))
        self.gridLayout_10.addWidget(self._1dXlabEdit, 2, 1, 1, 1)
        self._1dGridTog = QtGui.QCheckBox(self.groupBox_31)
        self._1dGridTog.setObjectName(_fromUtf8("_1dGridTog"))
        self.gridLayout_10.addWidget(self._1dGridTog, 0, 0, 1, 1)
        self.verticalLayout_58.addLayout(self.gridLayout_10)
        self.verticalLayout_59.addWidget(self.groupBox_31)
        spacerItem50 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_59.addItem(spacerItem50)
        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents_9)
        self.verticalLayout_3.addWidget(self.scrollArea_8)
        self.QuickSettings.addTab(self.q_SglPlt, _fromUtf8(""))
        self.q_Plt2d = QtGui.QWidget()
        self.q_Plt2d.setObjectName(_fromUtf8("q_Plt2d"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.q_Plt2d)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.scrollArea_7 = QtGui.QScrollArea(self.q_Plt2d)
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName(_fromUtf8("scrollArea_7"))
        self.scrollAreaWidgetContents_8 = QtGui.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 358, 801))
        self.scrollAreaWidgetContents_8.setObjectName(_fromUtf8("scrollAreaWidgetContents_8"))
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_8)
        self.verticalLayout_13.addWidget(self.scrollArea_7)
        self.QuickSettings.addTab(self.q_Plt2d, _fromUtf8(""))
        self.q_Cmap = QtGui.QWidget()
        self.q_Cmap.setObjectName(_fromUtf8("q_Cmap"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.q_Cmap)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.scrollArea_3 = QtGui.QScrollArea(self.q_Cmap)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 382, 763))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.verticalLayout_28 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_18.addWidget(self.label_10)
        self._cbCmap = QtGui.QComboBox(self.scrollAreaWidgetContents_4)
        self._cbCmap.setEditable(False)
        self._cbCmap.setObjectName(_fromUtf8("_cbCmap"))
        self.horizontalLayout_18.addWidget(self._cbCmap)
        self._cbInvert = QtGui.QCheckBox(self.scrollAreaWidgetContents_4)
        self._cbInvert.setObjectName(_fromUtf8("_cbInvert"))
        self.horizontalLayout_18.addWidget(self._cbInvert)
        self._cbAutoScale = QtGui.QPushButton(self.scrollAreaWidgetContents_4)
        self._cbAutoScale.setObjectName(_fromUtf8("_cbAutoScale"))
        self.horizontalLayout_18.addWidget(self._cbAutoScale)
        spacerItem51 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem51)
        self.verticalLayout_28.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_48 = QtGui.QHBoxLayout()
        self.horizontalLayout_48.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout_48.setObjectName(_fromUtf8("horizontalLayout_48"))
        self.label_18 = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_48.addWidget(self.label_18)
        spacerItem52 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem52)
        self._cbClimMin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self._cbClimMin.setMinimum(-16777215.0)
        self._cbClimMin.setMaximum(16777215.0)
        self._cbClimMin.setSingleStep(1.0)
        self._cbClimMin.setObjectName(_fromUtf8("_cbClimMin"))
        self.horizontalLayout_48.addWidget(self._cbClimMin)
        spacerItem53 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem53)
        self._cbClimMax = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self._cbClimMax.setMinimum(-16777215.0)
        self._cbClimMax.setMaximum(16777215.0)
        self._cbClimMax.setObjectName(_fromUtf8("_cbClimMax"))
        self.horizontalLayout_48.addWidget(self._cbClimMax)
        spacerItem54 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_48.addItem(spacerItem54)
        self.verticalLayout_28.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self._cbVminChk = QtGui.QCheckBox(self.scrollAreaWidgetContents_4)
        self._cbVminChk.setObjectName(_fromUtf8("_cbVminChk"))
        self.horizontalLayout_20.addWidget(self._cbVminChk)
        spacerItem55 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem55)
        self._cbVmin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self._cbVmin.setMinimum(-16777215.0)
        self._cbVmin.setMaximum(16777215.0)
        self._cbVmin.setSingleStep(1.0)
        self._cbVmin.setObjectName(_fromUtf8("_cbVmin"))
        self.horizontalLayout_20.addWidget(self._cbVmin)
        spacerItem56 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem56)
        self._cbVmaxChk = QtGui.QCheckBox(self.scrollAreaWidgetContents_4)
        self._cbVmaxChk.setObjectName(_fromUtf8("_cbVmaxChk"))
        self.horizontalLayout_20.addWidget(self._cbVmaxChk)
        self._cbVmax = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_4)
        self._cbVmax.setMinimum(-16777215.0)
        self._cbVmax.setMaximum(16777215.0)
        self._cbVmax.setObjectName(_fromUtf8("_cbVmax"))
        self.horizontalLayout_20.addWidget(self._cbVmax)
        spacerItem57 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem57)
        self.verticalLayout_28.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.qUnder_txt = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.qUnder_txt.setObjectName(_fromUtf8("qUnder_txt"))
        self.horizontalLayout_21.addWidget(self.qUnder_txt)
        self._cbUnder = QtGui.QLineEdit(self.scrollAreaWidgetContents_4)
        self._cbUnder.setObjectName(_fromUtf8("_cbUnder"))
        self.horizontalLayout_21.addWidget(self._cbUnder)
        self.qOver_txt = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.qOver_txt.setObjectName(_fromUtf8("qOver_txt"))
        self.horizontalLayout_21.addWidget(self.qOver_txt)
        self._cbOver = QtGui.QLineEdit(self.scrollAreaWidgetContents_4)
        self._cbOver.setObjectName(_fromUtf8("_cbOver"))
        self.horizontalLayout_21.addWidget(self._cbOver)
        self.verticalLayout_28.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_25.addWidget(self.label_11)
        self._cbLabel = QtGui.QLineEdit(self.scrollAreaWidgetContents_4)
        self._cbLabel.setObjectName(_fromUtf8("_cbLabel"))
        self.horizontalLayout_25.addWidget(self._cbLabel)
        self.verticalLayout_28.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_63 = QtGui.QHBoxLayout()
        self.horizontalLayout_63.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_63.setSpacing(0)
        self.horizontalLayout_63.setObjectName(_fromUtf8("horizontalLayout_63"))
        spacerItem58 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_63.addItem(spacerItem58)
        self.line_10 = QtGui.QFrame(self.scrollAreaWidgetContents_4)
        self.line_10.setMinimumSize(QtCore.QSize(200, 0))
        self.line_10.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.horizontalLayout_63.addWidget(self.line_10)
        spacerItem59 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_63.addItem(spacerItem59)
        self.verticalLayout_28.addLayout(self.horizontalLayout_63)
        self.cbpanel = QtGui.QVBoxLayout()
        self.cbpanel.setContentsMargins(-1, 0, -1, 0)
        self.cbpanel.setSpacing(0)
        self.cbpanel.setObjectName(_fromUtf8("cbpanel"))
        spacerItem60 = QtGui.QSpacerItem(100, 200, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.cbpanel.addItem(spacerItem60)
        self.verticalLayout_28.addLayout(self.cbpanel)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_23.addWidget(self.scrollArea_3)
        self.colorbar_pan = QtGui.QWidget(self.q_Cmap)
        self.colorbar_pan.setMinimumSize(QtCore.QSize(0, 0))
        self.colorbar_pan.setObjectName(_fromUtf8("colorbar_pan"))
        self.verticalLayout_46 = QtGui.QVBoxLayout(self.colorbar_pan)
        self.verticalLayout_46.setObjectName(_fromUtf8("verticalLayout_46"))
        self.verticalLayout_23.addWidget(self.colorbar_pan)
        self.QuickSettings.addTab(self.q_Cmap, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.QuickSettings)
        self.horizontalLayout_2.addWidget(self.q_widget)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.MODIFY = QtGui.QHBoxLayout()
        self.MODIFY.setMargin(0)
        self.MODIFY.setSpacing(0)
        self.MODIFY.setObjectName(_fromUtf8("MODIFY"))
        spacerItem61 = QtGui.QSpacerItem(0, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.MODIFY.addItem(spacerItem61)
        self._NdVizPanel = QtGui.QWidget(self.centralwidget)
        self._NdVizPanel.setObjectName(_fromUtf8("_NdVizPanel"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self._NdVizPanel)
        self.verticalLayout_17.setMargin(0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self._NdVizLayout = QtGui.QHBoxLayout()
        self._NdVizLayout.setContentsMargins(-1, -1, 0, -1)
        self._NdVizLayout.setSpacing(0)
        self._NdVizLayout.setObjectName(_fromUtf8("_NdVizLayout"))
        self.verticalLayout_17.addLayout(self._NdVizLayout)
        self.MODIFY.addWidget(self._NdVizPanel)
        self._1dVizPanel = QtGui.QWidget(self.centralwidget)
        self._1dVizPanel.setObjectName(_fromUtf8("_1dVizPanel"))
        self.horizontalLayout_38 = QtGui.QHBoxLayout(self._1dVizPanel)
        self.horizontalLayout_38.setMargin(0)
        self.horizontalLayout_38.setSpacing(0)
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self._1dVizLayout = QtGui.QHBoxLayout()
        self._1dVizLayout.setContentsMargins(-1, -1, 0, -1)
        self._1dVizLayout.setSpacing(0)
        self._1dVizLayout.setObjectName(_fromUtf8("_1dVizLayout"))
        self.horizontalLayout_38.addLayout(self._1dVizLayout)
        self.MODIFY.addWidget(self._1dVizPanel)
        self.verticalLayout_18.addLayout(self.MODIFY)
        spacerItem62 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_18.addItem(spacerItem62)
        self.horizontalLayout_2.addLayout(self.verticalLayout_18)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1328, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFiles = QtGui.QMenu(self.menubar)
        self.menuFiles.setObjectName(_fromUtf8("menuFiles"))
        self.menuDisplay = QtGui.QMenu(self.menubar)
        self.menuDisplay.setObjectName(_fromUtf8("menuDisplay"))
        self.menuPanel = QtGui.QMenu(self.menuDisplay)
        self.menuPanel.setObjectName(_fromUtf8("menuPanel"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionCortical_repartition = QtGui.QAction(MainWindow)
        self.actionCortical_repartition.setObjectName(_fromUtf8("actionCortical_repartition"))
        self.actionCortical = QtGui.QAction(MainWindow)
        self.actionCortical.setObjectName(_fromUtf8("actionCortical"))
        self.actionSagittal = QtGui.QAction(MainWindow)
        self.actionSagittal.setObjectName(_fromUtf8("actionSagittal"))
        self.actionAxial = QtGui.QAction(MainWindow)
        self.actionAxial.setObjectName(_fromUtf8("actionAxial"))
        self.actionCamera = QtGui.QAction(MainWindow)
        self.actionCamera.setObjectName(_fromUtf8("actionCamera"))
        self.actionLeft = QtGui.QAction(MainWindow)
        self.actionLeft.setObjectName(_fromUtf8("actionLeft"))
        self.actionRight = QtGui.QAction(MainWindow)
        self.actionRight.setObjectName(_fromUtf8("actionRight"))
        self.actionQuick_settings = QtGui.QAction(MainWindow)
        self.actionQuick_settings.setCheckable(True)
        self.actionQuick_settings.setObjectName(_fromUtf8("actionQuick_settings"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionProjection = QtGui.QAction(MainWindow)
        self.actionProjection.setObjectName(_fromUtf8("actionProjection"))
        self.actionRepartition = QtGui.QAction(MainWindow)
        self.actionRepartition.setObjectName(_fromUtf8("actionRepartition"))
        self.actionShortcuts = QtGui.QAction(MainWindow)
        self.actionShortcuts.setCheckable(True)
        self.actionShortcuts.setObjectName(_fromUtf8("actionShortcuts"))
        self.actionUi_settings = QtGui.QAction(MainWindow)
        self.actionUi_settings.setCheckable(True)
        self.actionUi_settings.setChecked(False)
        self.actionUi_settings.setObjectName(_fromUtf8("actionUi_settings"))
        self.actionNdPlt = QtGui.QAction(MainWindow)
        self.actionNdPlt.setCheckable(True)
        self.actionNdPlt.setObjectName(_fromUtf8("actionNdPlt"))
        self.actionOnedPlt = QtGui.QAction(MainWindow)
        self.actionOnedPlt.setCheckable(True)
        self.actionOnedPlt.setObjectName(_fromUtf8("actionOnedPlt"))
        self.actionImage = QtGui.QAction(MainWindow)
        self.actionImage.setCheckable(True)
        self.actionImage.setObjectName(_fromUtf8("actionImage"))
        self.actionColormap = QtGui.QAction(MainWindow)
        self.actionColormap.setCheckable(True)
        self.actionColormap.setObjectName(_fromUtf8("actionColormap"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.menuPanel.addAction(self.actionUi_settings)
        self.menuPanel.addAction(self.actionNdPlt)
        self.menuPanel.addAction(self.actionOnedPlt)
        self.menuPanel.addAction(self.actionImage)
        self.menuPanel.addAction(self.actionColormap)
        self.menuDisplay.addAction(self.actionQuick_settings)
        self.menuDisplay.addAction(self.menuPanel.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.menuFiles.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.QuickSettings.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self._cbCmap, self._cbInvert)
        MainWindow.setTabOrder(self._cbInvert, self._cbVminChk)
        MainWindow.setTabOrder(self._cbVminChk, self._cbVmin)
        MainWindow.setTabOrder(self._cbVmin, self._cbVmaxChk)
        MainWindow.setTabOrder(self._cbVmaxChk, self._cbVmax)
        MainWindow.setTabOrder(self._cbVmax, self._cbUnder)
        MainWindow.setTabOrder(self._cbUnder, self._cbOver)
        MainWindow.setTabOrder(self._cbOver, self._cbLabel)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ndviz", None))
        self.QuickSettings.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Background color", None))
        self.label_5.setText(_translate("MainWindow", "Red", None))
        self.label_6.setText(_translate("MainWindow", "Green", None))
        self.label_7.setText(_translate("MainWindow", "Blue", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Canvas", None))
        self._CanVisNd.setText(_translate("MainWindow", "Nd-plot", None))
        self._CanVis1d.setText(_translate("MainWindow", "1d-plot", None))
        self._CanVisImage.setText(_translate("MainWindow", "Image", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_UI), _translate("MainWindow", "UI", None))
        self.q_Ndplt.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.groupBox.setTitle(_translate("MainWindow", "Axis selection", None))
        self._ndAxShape.setText(_translate("MainWindow", "data.shape", None))
        self.label_13.setText(_translate("MainWindow", "Time axis :", None))
        self._ndAx2dSecText.setText(_translate("MainWindow", "2nd axis :", None))
        self.label_15.setText(_translate("MainWindow", "Grid (Rows x Cols):", None))
        self.label_14.setText(_translate("MainWindow", "Row axis", None))
        self.label_19.setText(_translate("MainWindow", "Col axis", None))
        self._ndAxCheckMsg.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic;\">Check message N_rows x N_cols = selected dim</span></p></body></html>", None))
        self._ndAxUpdate.setText(_translate("MainWindow", "Update", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Color", None))
        self.label.setText(_translate("MainWindow", "Type", None))
        self._ndColType.setItemText(0, _translate("MainWindow", "random", None))
        self._ndColType.setItemText(1, _translate("MainWindow", "uniform", None))
        self._ndColType.setItemText(2, _translate("MainWindow", "dyn_time", None))
        self._ndColType.setItemText(3, _translate("MainWindow", "dyn_minmax", None))
        self.label_3.setText(_translate("MainWindow", "Color range", None))
        self._ndRndNew.setText(_translate("MainWindow", "New random", None))
        self.label_8.setText(_translate("MainWindow", "Color", None))
        self._ndDynText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic; color:#ffffff;\">Control signal color using the colormap tab...</span></p></body></html>", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Real time", None))
        self.label_2.setText(_translate("MainWindow", "Laps", None))
        self._ndRtStart.setText(_translate("MainWindow", "Start", None))
        self._ndRtStop.setText(_translate("MainWindow", "Stop", None))
        self._ndRtReset.setText(_translate("MainWindow", "Reset", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Settings", None))
        self.label_4.setText(_translate("MainWindow", "Space", None))
        self.label_9.setText(_translate("MainWindow", "Line width", None))
        self.label_12.setText(_translate("MainWindow", "Scale (x, y)", None))
        self.groupBox_15.setTitle(_translate("MainWindow", "Info", None))
        self.label_16.setText(_translate("MainWindow", "Title", None))
        self.label_39.setText(_translate("MainWindow", "Y label", None))
        self.label_17.setText(_translate("MainWindow", "X label", None))
        self._ndGridTog.setText(_translate("MainWindow", "Grid", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_Ndplt), _translate("MainWindow", "Nd-Plot", None))
        self.groupBox_32.setTitle(_translate("MainWindow", "Axis selection", None))
        self._1dAxShape.setText(_translate("MainWindow", "data.shape", None))
        self.label_96.setText(_translate("MainWindow", "X axis", None))
        self.label_97.setText(_translate("MainWindow", "Y axis", None))
        self.label_98.setText(_translate("MainWindow", "Index", None))
        self._1dAxUpdate.setText(_translate("MainWindow", "Update", None))
        self.groupBox_33.setTitle(_translate("MainWindow", "Plot", None))
        self.label_91.setText(_translate("MainWindow", "Plot data as", None))
        self._1dPltPick.setItemText(0, _translate("MainWindow", "line", None))
        self._1dPltPick.setItemText(1, _translate("MainWindow", "histogram", None))
        self._1dPltPick.setItemText(2, _translate("MainWindow", "spectrogram", None))
        self.label_92.setText(_translate("MainWindow", "Bins", None))
        self.label_99.setText(_translate("MainWindow", "Line width", None))
        self.label_101.setText(_translate("MainWindow", "Method", None))
        self._1dLineMeth.setItemText(0, _translate("MainWindow", "gl", None))
        self._1dLineMeth.setItemText(1, _translate("MainWindow", "agg", None))
        self.label_100.setText(_translate("MainWindow", "nfft", None))
        self.label_102.setText(_translate("MainWindow", "Step", None))
        self._1dColBox.setTitle(_translate("MainWindow", "Color", None))
        self.label_93.setText(_translate("MainWindow", "Type", None))
        self._1dColType.setItemText(0, _translate("MainWindow", "random", None))
        self._1dColType.setItemText(1, _translate("MainWindow", "uniform", None))
        self._1dColType.setItemText(2, _translate("MainWindow", "dyn_time", None))
        self._1dColType.setItemText(3, _translate("MainWindow", "dyn_minmax", None))
        self.label_94.setText(_translate("MainWindow", "Color range", None))
        self._1dRndNew.setText(_translate("MainWindow", "New random", None))
        self.label_95.setText(_translate("MainWindow", "Color", None))
        self._1dDynText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic; color:#ffffff;\">Control signal color using the colormap tab...</span></p></body></html>", None))
        self.groupBox_34.setTitle(_translate("MainWindow", "Interpolation", None))
        self.label_118.setText(_translate("MainWindow", "Type", None))
        self._1dInterType.setItemText(0, _translate("MainWindow", "None", None))
        self._1dInterType.setItemText(1, _translate("MainWindow", "linear", None))
        self._1dInterType.setItemText(2, _translate("MainWindow", "nearest", None))
        self._1dInterType.setItemText(3, _translate("MainWindow", "zero", None))
        self._1dInterType.setItemText(4, _translate("MainWindow", "slinear", None))
        self._1dInterType.setItemText(5, _translate("MainWindow", "quadratic", None))
        self._1dInterType.setItemText(6, _translate("MainWindow", "cubic", None))
        self.label_119.setText(_translate("MainWindow", "Step", None))
        self.groupBox_31.setTitle(_translate("MainWindow", "Info", None))
        self.label_90.setText(_translate("MainWindow", "Y label", None))
        self.label_88.setText(_translate("MainWindow", "Title", None))
        self.label_89.setText(_translate("MainWindow", "X label", None))
        self._1dGridTog.setText(_translate("MainWindow", "Grid", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_SglPlt), _translate("MainWindow", "1d-plot", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_Plt2d), _translate("MainWindow", "Image", None))
        self.label_10.setText(_translate("MainWindow", "Colormap", None))
        self._cbInvert.setText(_translate("MainWindow", "Invert", None))
        self._cbAutoScale.setText(_translate("MainWindow", "Auto-scale", None))
        self.label_18.setText(_translate("MainWindow", "clim", None))
        self._cbVminChk.setToolTip(_translate("MainWindow", "Every values under vmin will be set to the \"under\" color", None))
        self._cbVminChk.setText(_translate("MainWindow", "vmin", None))
        self._cbVmaxChk.setText(_translate("MainWindow", "vmax", None))
        self.qUnder_txt.setText(_translate("MainWindow", "Under", None))
        self.qOver_txt.setText(_translate("MainWindow", "Over", None))
        self.label_11.setText(_translate("MainWindow", "Colorbar label: ", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_Cmap), _translate("MainWindow", "Colormap", None))
        self.menuFiles.setTitle(_translate("MainWindow", "Files", None))
        self.menuDisplay.setTitle(_translate("MainWindow", "Display", None))
        self.menuPanel.setTitle(_translate("MainWindow", "Panel", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))
        self.actionCortical_repartition.setText(_translate("MainWindow", "Cortical repartition", None))
        self.actionCortical.setText(_translate("MainWindow", "Cortical", None))
        self.actionSagittal.setText(_translate("MainWindow", "Sagittal", None))
        self.actionAxial.setText(_translate("MainWindow", "Axial", None))
        self.actionCamera.setText(_translate("MainWindow", "Camera", None))
        self.actionLeft.setText(_translate("MainWindow", "Left", None))
        self.actionRight.setText(_translate("MainWindow", "Right", None))
        self.actionQuick_settings.setText(_translate("MainWindow", "Quick settings", None))
        self.actionQuick_settings.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionProjection.setText(_translate("MainWindow", "Projection", None))
        self.actionProjection.setToolTip(_translate("MainWindow", "<html><head/><body><p>Find all vertices under a distance of t_radius with each source and project s_data to the surface</p></body></html>", None))
        self.actionProjection.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.actionRepartition.setText(_translate("MainWindow", "Repartition", None))
        self.actionRepartition.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.actionShortcuts.setText(_translate("MainWindow", "Shortcuts", None))
        self.actionShortcuts.setShortcut(_translate("MainWindow", "Ctrl+T", None))
        self.actionUi_settings.setText(_translate("MainWindow", "Ui settings", None))
        self.actionNdPlt.setText(_translate("MainWindow", "Nd-plot", None))
        self.actionOnedPlt.setText(_translate("MainWindow", "1d-plot", None))
        self.actionImage.setText(_translate("MainWindow", "Image", None))
        self.actionColormap.setText(_translate("MainWindow", "Colormap", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation", None))

