version: 2
jobs:
    build:
      branches:
        ignore:
          - gh-pages
      docker:
        - image: circleci/python:3.6-jessie
      steps:
        - checkout
        - run:
            name: Clean CircleCI
            command: |
              rm -rf ~/.pyenv;
              rm -rf ~/virtualenvs;
        - run:
            name: Spin up Xvfb
            command: |
              /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
              echo "export DISPLAY=:99" >> $BASH_ENV;
        - run: sudo apt-get update && sudo apt-get install libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6 qt5-default;
        - restore_cache:
            keys:
              - data-cache
              - pip-cache
              - miniconda-cache
        - run:
            name: Install miniconda
            command: |
              if [ ! -d "~/miniconda3" ]; then
                wget -q http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh;
                chmod +x ~/miniconda.sh;
                ~/miniconda.sh -b -p ~/miniconda3;
                echo "export PATH=~/miniconda3/bin:$PATH" >> $BASH_ENV;
              else
                echo "Miniconda3 already set up.";
              fi
        - save_cache:
            key: miniconda-cache
            paths:
              - ~/.cache/miniconda
        - run:
            name: Setup Python environment
            command: |
              conda update --yes --quiet conda;
              conda create -n testenv --yes python=3.6 numpy scipy pip cython qt==5.9.4 matplotlib==2.2.2 pyqt==5.9.2;
              source activate testenv;
              pip install -U pip;
              pip install git+https://github.com/vispy/vispy.git;
              pip install pytest pytest-travis-fold;
              pip install mne nibabel pandas openpyxl tensorpac xlrd;
              conda install -c conda-forge scikit-image;
              pip install git+https://github.com/hbldh/lspopt.git#egg=lspopt;
              pip install sphinx sphinx-gallery==0.4.0 sphinx_bootstrap_theme lxml;
              pip install numpydoc;
              echo $PATH;
              echo $CIRCLE_BRANCH;
              which python;
              which pip;
        - save_cache:
            key: pip-cache
            paths:
              - ~/.cache/pip
        - run:
            name: Install visbrain
            command: |
              source activate testenv;
              python setup.py develop;
        - run:
            name: Run the tests
            command: |
              source activate testenv;
              pytest;
        - run:
            name: Build the documentation
            command: |
                source activate testenv;
                cd docs
                make html
            no_output_timeout: 15m
        - store_artifacts:
            path: docs/_build/html/
            destination: html
        - add_ssh_keys:
            fingerprints:
                - "bd:69:fa:ba:71:1b:17:81:bd:be:75:5b:fb:20:64:f5"
        - deploy:
            name: github pages deployment
            command: |
              source activate testenv;
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                echo "Deploying dev docs.";
                git config --global user.email "e.combrisson@gmail.com";
                git config --global user.name "EtienneCmb";
                cd docs;
                make install;
              else
                echo "No deployment (build: ${CIRCLE_BRANCH}).";
              fi    
        - save_cache:
            key: data-cache
            paths:
              - ~/.visbrain_data
