# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/etienne/Toolbox/visbrain/visbrain/signal/gui/signal_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1197, 941)
        font = QtGui.QFont()
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        MainWindow.setFont(font)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setLineWidth(1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.q_widget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q_widget.sizePolicy().hasHeightForWidth())
        self.q_widget.setSizePolicy(sizePolicy)
        self.q_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.q_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.q_widget.setObjectName("q_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.q_widget)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.QuickSettings = QtWidgets.QTabWidget(self.q_widget)
        self.QuickSettings.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.QuickSettings.setAutoFillBackground(False)
        self.QuickSettings.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.QuickSettings.setMovable(True)
        self.QuickSettings.setObjectName("QuickSettings")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 414, 935))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.groupBox_3)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 3, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self._axis_color = QtWidgets.QLineEdit(self.groupBox_3)
        self._axis_color.setObjectName("_axis_color")
        self.gridLayout.addWidget(self._axis_color, 3, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 0, 1, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.groupBox_3)
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout.addWidget(self.line_21, 2, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.groupBox_3)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 4, 1, 1, 1)
        self._sig_color = QtWidgets.QLineEdit(self.groupBox_3)
        self._sig_color.setObjectName("_sig_color")
        self.gridLayout.addWidget(self._sig_color, 4, 2, 1, 1)
        self._sig_ax_picker = QtWidgets.QToolButton(self.groupBox_3)
        self._sig_ax_picker.setObjectName("_sig_ax_picker")
        self.gridLayout.addWidget(self._sig_ax_picker, 3, 3, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 1, 0, 1, 1)
        self._sig_title = QtWidgets.QLineEdit(self.groupBox_3)
        self._sig_title.setObjectName("_sig_title")
        self.gridLayout_2.addWidget(self._sig_title, 0, 1, 1, 1)
        self._sig_title_fz = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self._sig_title_fz.setDecimals(1)
        self._sig_title_fz.setMinimum(0.1)
        self._sig_title_fz.setObjectName("_sig_title_fz")
        self.gridLayout_2.addWidget(self._sig_title_fz, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 2, 1, 2)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_15.addWidget(self.label_23, 0, 0, 1, 1)
        self._sig_lab_fz = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self._sig_lab_fz.setDecimals(1)
        self._sig_lab_fz.setMinimum(0.1)
        self._sig_lab_fz.setObjectName("_sig_lab_fz")
        self.gridLayout_15.addWidget(self._sig_lab_fz, 2, 1, 1, 1)
        self._sig_xlab = QtWidgets.QLineEdit(self.groupBox_3)
        self._sig_xlab.setObjectName("_sig_xlab")
        self.gridLayout_15.addWidget(self._sig_xlab, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_15.addWidget(self.label_24, 2, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_15.addWidget(self.label_25, 1, 0, 1, 1)
        self._sig_ylab = QtWidgets.QLineEdit(self.groupBox_3)
        self._sig_ylab.setObjectName("_sig_ylab")
        self.gridLayout_15.addWidget(self._sig_ylab, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_15, 1, 2, 1, 2)
        self._sig_ticks_fz = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self._sig_ticks_fz.setDecimals(1)
        self._sig_ticks_fz.setMinimum(0.1)
        self._sig_ticks_fz.setObjectName("_sig_ticks_fz")
        self.gridLayout.addWidget(self._sig_ticks_fz, 2, 2, 1, 2)
        self._sig_sig_picker = QtWidgets.QToolButton(self.groupBox_3)
        self._sig_sig_picker.setObjectName("_sig_sig_picker")
        self.gridLayout.addWidget(self._sig_sig_picker, 4, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_12.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 0, 0, 1, 1)
        self._sig_form = QtWidgets.QComboBox(self.groupBox_5)
        self._sig_form.setObjectName("_sig_form")
        self._sig_form.addItem("")
        self._sig_form.addItem("")
        self._sig_form.addItem("")
        self._sig_form.addItem("")
        self._sig_form.addItem("")
        self._sig_form.addItem("")
        self.gridLayout_6.addWidget(self._sig_form, 0, 2, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.groupBox_5)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_6.addWidget(self.line_12, 0, 1, 1, 1)
        self._sig_amp = QtWidgets.QGroupBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setKerning(True)
        self._sig_amp.setFont(font)
        self._sig_amp.setCheckable(True)
        self._sig_amp.setChecked(False)
        self._sig_amp.setObjectName("_sig_amp")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self._sig_amp)
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.line_6 = QtWidgets.QFrame(self._sig_amp)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_5.addWidget(self.line_6, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self._sig_amp)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 3, 2, 1, 1)
        self._sig_amp_min = QtWidgets.QDoubleSpinBox(self._sig_amp)
        self._sig_amp_min.setObjectName("_sig_amp_min")
        self.gridLayout_5.addWidget(self._sig_amp_min, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self._sig_amp)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 1, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self._sig_amp)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_5.addWidget(self.line_2, 1, 1, 1, 1)
        self._sig_amp_max = QtWidgets.QDoubleSpinBox(self._sig_amp)
        self._sig_amp_max.setObjectName("_sig_amp_max")
        self.gridLayout_5.addWidget(self._sig_amp_max, 0, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_5)
        self.gridLayout_6.addWidget(self._sig_amp, 3, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 2, 2, 1, 1)
        self._PlottingForm = QtWidgets.QStackedWidget(self.groupBox_5)
        self._PlottingForm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self._PlottingForm.setObjectName("_PlottingForm")
        self.line = QtWidgets.QWidget()
        self.line.setObjectName("line")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.line)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self._sig_th = QtWidgets.QGroupBox(self.line)
        self._sig_th.setCheckable(True)
        self._sig_th.setChecked(False)
        self._sig_th.setObjectName("_sig_th")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self._sig_th)
        self.verticalLayout_10.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_30 = QtWidgets.QLabel(self._sig_th)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_7.addWidget(self.label_30, 1, 0, 1, 1)
        self.line_22 = QtWidgets.QFrame(self._sig_th)
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.gridLayout_7.addWidget(self.line_22, 1, 1, 1, 1)
        self._sig_th_min = QtWidgets.QDoubleSpinBox(self._sig_th)
        self._sig_th_min.setDecimals(1)
        self._sig_th_min.setMinimum(1.0)
        self._sig_th_min.setSingleStep(0.1)
        self._sig_th_min.setObjectName("_sig_th_min")
        self.gridLayout_7.addWidget(self._sig_th_min, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 3, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self._sig_th)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 0, 0, 1, 1)
        self.line_23 = QtWidgets.QFrame(self._sig_th)
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.gridLayout_7.addWidget(self.line_23, 0, 1, 1, 1)
        self._sig_th_max = QtWidgets.QDoubleSpinBox(self._sig_th)
        self._sig_th_max.setDecimals(1)
        self._sig_th_max.setMinimum(1.0)
        self._sig_th_max.setSingleStep(0.1)
        self._sig_th_max.setObjectName("_sig_th_max")
        self.gridLayout_7.addWidget(self._sig_th_max, 0, 2, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_7)
        self.gridLayout_9.addWidget(self._sig_th, 2, 0, 1, 3)
        self.label_15 = QtWidgets.QLabel(self.line)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_9.addWidget(self.label_15, 1, 0, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.line)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_9.addWidget(self.line_15, 1, 1, 1, 1)
        self._sig_lw = QtWidgets.QDoubleSpinBox(self.line)
        self._sig_lw.setDecimals(1)
        self._sig_lw.setMinimum(1.0)
        self._sig_lw.setSingleStep(0.1)
        self._sig_lw.setObjectName("_sig_lw")
        self.gridLayout_9.addWidget(self._sig_lw, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem3, 5, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem4, 4, 2, 1, 1)
        self._PlottingForm.addWidget(self.line)
        self.markers = QtWidgets.QWidget()
        self.markers.setObjectName("markers")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.markers)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem5, 2, 2, 1, 1)
        self.line_17 = QtWidgets.QFrame(self.markers)
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_13.addWidget(self.line_17, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.markers)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_13.addWidget(self.label_19, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem6, 3, 0, 1, 1)
        self._sig_size = QtWidgets.QDoubleSpinBox(self.markers)
        self._sig_size.setObjectName("_sig_size")
        self.gridLayout_13.addWidget(self._sig_size, 0, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.markers)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_13.addWidget(self.label_27, 1, 0, 1, 1)
        self.line_19 = QtWidgets.QFrame(self.markers)
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout_13.addWidget(self.line_19, 1, 1, 1, 1)
        self._sig_symbol = QtWidgets.QComboBox(self.markers)
        self._sig_symbol.setObjectName("_sig_symbol")
        self._sig_symbol.addItem("")
        self._sig_symbol.addItem("")
        self._sig_symbol.addItem("")
        self._sig_symbol.addItem("")
        self._sig_symbol.addItem("")
        self._sig_symbol.addItem("")
        self._sig_symbol.addItem("")
        self._sig_symbol.addItem("")
        self._sig_symbol.addItem("")
        self._sig_symbol.addItem("")
        self._sig_symbol.addItem("")
        self._sig_symbol.addItem("")
        self._sig_symbol.addItem("")
        self._sig_symbol.addItem("")
        self.gridLayout_13.addWidget(self._sig_symbol, 1, 2, 1, 1)
        self._PlottingForm.addWidget(self.markers)
        self.histogram = QtWidgets.QWidget()
        self.histogram.setObjectName("histogram")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.histogram)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_18 = QtWidgets.QLabel(self.histogram)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_12.addWidget(self.label_18, 0, 0, 1, 1)
        self._sig_nbins = QtWidgets.QSpinBox(self.histogram)
        self._sig_nbins.setMinimum(1)
        self._sig_nbins.setMaximum(10000)
        self._sig_nbins.setObjectName("_sig_nbins")
        self.gridLayout_12.addWidget(self._sig_nbins, 0, 2, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.histogram)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_12.addWidget(self.line_16, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem7, 1, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem8, 1, 0, 1, 1)
        self._PlottingForm.addWidget(self.histogram)
        self.TF = QtWidgets.QWidget()
        self.TF.setObjectName("TF")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.TF)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self._sig_tf_apply = QtWidgets.QPushButton(self.TF)
        self._sig_tf_apply.setObjectName("_sig_tf_apply")
        self.horizontalLayout_6.addWidget(self._sig_tf_apply)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 8, 0, 1, 3)
        self.line_14 = QtWidgets.QFrame(self.TF)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_3.addWidget(self.line_14, 0, 1, 1, 1)
        self._sig_tf_interp = QtWidgets.QComboBox(self.TF)
        self._sig_tf_interp.setObjectName("_sig_tf_interp")
        self._sig_tf_interp.addItem("")
        self._sig_tf_interp.addItem("")
        self._sig_tf_interp.addItem("")
        self._sig_tf_interp.addItem("")
        self._sig_tf_interp.addItem("")
        self._sig_tf_interp.addItem("")
        self._sig_tf_interp.addItem("")
        self._sig_tf_interp.addItem("")
        self._sig_tf_interp.addItem("")
        self._sig_tf_interp.addItem("")
        self._sig_tf_interp.addItem("")
        self._sig_tf_interp.addItem("")
        self._sig_tf_interp.addItem("")
        self._sig_tf_interp.addItem("")
        self._sig_tf_interp.addItem("")
        self._sig_tf_interp.addItem("")
        self._sig_tf_interp.addItem("")
        self.gridLayout_3.addWidget(self._sig_tf_interp, 1, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 4, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.TF)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.TF)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self._sig_baseline = QtWidgets.QGroupBox(self.TF)
        self._sig_baseline.setCheckable(True)
        self._sig_baseline.setChecked(False)
        self._sig_baseline.setObjectName("_sig_baseline")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self._sig_baseline)
        self.horizontalLayout_5.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self._sig_baseline)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.line_8 = QtWidgets.QFrame(self._sig_baseline)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_5.addWidget(self.line_8)
        self._sig_base_start = QtWidgets.QSpinBox(self._sig_baseline)
        self._sig_base_start.setObjectName("_sig_base_start")
        self.horizontalLayout_5.addWidget(self._sig_base_start)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.label_14 = QtWidgets.QLabel(self._sig_baseline)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.line_18 = QtWidgets.QFrame(self._sig_baseline)
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.horizontalLayout_5.addWidget(self.line_18)
        self._sig_base_end = QtWidgets.QSpinBox(self._sig_baseline)
        self._sig_base_end.setObjectName("_sig_base_end")
        self.horizontalLayout_5.addWidget(self._sig_base_end)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.gridLayout_3.addWidget(self._sig_baseline, 5, 0, 1, 3)
        self._sig_averaging = QtWidgets.QGroupBox(self.TF)
        self._sig_averaging.setCheckable(True)
        self._sig_averaging.setChecked(False)
        self._sig_averaging.setObjectName("_sig_averaging")
        self.gridLayout_11 = QtWidgets.QGridLayout(self._sig_averaging)
        self.gridLayout_11.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self._sig_av_overlap = QtWidgets.QDoubleSpinBox(self._sig_averaging)
        self._sig_av_overlap.setMaximum(0.8)
        self._sig_av_overlap.setSingleStep(0.1)
        self._sig_av_overlap.setObjectName("_sig_av_overlap")
        self.gridLayout_11.addWidget(self._sig_av_overlap, 1, 2, 1, 2)
        self.label_17 = QtWidgets.QLabel(self._sig_averaging)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_11.addWidget(self.label_17, 1, 0, 1, 1)
        self._sig_av_win = QtWidgets.QSpinBox(self._sig_averaging)
        self._sig_av_win.setObjectName("_sig_av_win")
        self.gridLayout_11.addWidget(self._sig_av_win, 0, 2, 1, 2)
        self.label_16 = QtWidgets.QLabel(self._sig_averaging)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_11.addWidget(self.label_16, 0, 0, 1, 1)
        self.line_25 = QtWidgets.QFrame(self._sig_averaging)
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.gridLayout_11.addWidget(self.line_25, 1, 1, 1, 1)
        self.line_24 = QtWidgets.QFrame(self._sig_averaging)
        self.line_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.gridLayout_11.addWidget(self.line_24, 0, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem14, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self._sig_averaging, 6, 0, 1, 3)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem15, 9, 0, 1, 1)
        self._sig_norm = QtWidgets.QComboBox(self.TF)
        self._sig_norm.setObjectName("_sig_norm")
        self._sig_norm.addItem("")
        self._sig_norm.addItem("")
        self._sig_norm.addItem("")
        self._sig_norm.addItem("")
        self._sig_norm.addItem("")
        self.gridLayout_3.addWidget(self._sig_norm, 0, 2, 1, 1)
        self.line_26 = QtWidgets.QFrame(self.TF)
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.gridLayout_3.addWidget(self.line_26, 1, 1, 1, 1)
        self._sig_tf_clim = QtWidgets.QGroupBox(self.TF)
        self._sig_tf_clim.setCheckable(True)
        self._sig_tf_clim.setChecked(False)
        self._sig_tf_clim.setObjectName("_sig_tf_clim")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self._sig_tf_clim)
        self.horizontalLayout_8.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_32 = QtWidgets.QLabel(self._sig_tf_clim)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_8.addWidget(self.label_32)
        self.line_27 = QtWidgets.QFrame(self._sig_tf_clim)
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.horizontalLayout_8.addWidget(self.line_27)
        self._sig_climin = QtWidgets.QDoubleSpinBox(self._sig_tf_clim)
        self._sig_climin.setMinimum(-1000000000.0)
        self._sig_climin.setMaximum(1000000000.0)
        self._sig_climin.setObjectName("_sig_climin")
        self.horizontalLayout_8.addWidget(self._sig_climin)
        spacerItem16 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.label_33 = QtWidgets.QLabel(self._sig_tf_clim)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_8.addWidget(self.label_33)
        self.line_28 = QtWidgets.QFrame(self._sig_tf_clim)
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.horizontalLayout_8.addWidget(self.line_28)
        self._sig_climax = QtWidgets.QDoubleSpinBox(self._sig_tf_clim)
        self._sig_climax.setMinimum(-1000000000.0)
        self._sig_climax.setMaximum(1000000000.0)
        self._sig_climax.setObjectName("_sig_climax")
        self.horizontalLayout_8.addWidget(self._sig_climax)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem17)
        self.gridLayout_3.addWidget(self._sig_tf_clim, 7, 0, 1, 3)
        self.label_34 = QtWidgets.QLabel(self.TF)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 2, 0, 1, 1)
        self.line_29 = QtWidgets.QFrame(self.TF)
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.gridLayout_3.addWidget(self.line_29, 2, 1, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self._sig_tf_rev = QtWidgets.QCheckBox(self.TF)
        self._sig_tf_rev.setObjectName("_sig_tf_rev")
        self.gridLayout_14.addWidget(self._sig_tf_rev, 0, 1, 1, 1)
        self._sig_tf_cmap = QtWidgets.QComboBox(self.TF)
        self._sig_tf_cmap.setObjectName("_sig_tf_cmap")
        self.gridLayout_14.addWidget(self._sig_tf_cmap, 0, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem18, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_14, 2, 2, 1, 1)
        self._PlottingForm.addWidget(self.TF)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.line_31 = QtWidgets.QFrame(self.page)
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.gridLayout_16.addWidget(self.line_31, 1, 1, 1, 1)
        self._sig_noverlap = QtWidgets.QSpinBox(self.page)
        self._sig_noverlap.setMaximum(10000000)
        self._sig_noverlap.setProperty("value", 128)
        self._sig_noverlap.setObjectName("_sig_noverlap")
        self.gridLayout_16.addWidget(self._sig_noverlap, 1, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem19, 3, 0, 1, 1)
        self._sig_nperseg = QtWidgets.QSpinBox(self.page)
        self._sig_nperseg.setMaximum(100000)
        self._sig_nperseg.setProperty("value", 256)
        self._sig_nperseg.setObjectName("_sig_nperseg")
        self.gridLayout_16.addWidget(self._sig_nperseg, 0, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_16.addWidget(self.label_36, 0, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_16.addWidget(self.label_37, 1, 0, 1, 1)
        self.line_30 = QtWidgets.QFrame(self.page)
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.gridLayout_16.addWidget(self.line_30, 0, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem20, 2, 2, 1, 1)
        self._PlottingForm.addWidget(self.page)
        self.gridLayout_6.addWidget(self._PlottingForm, 4, 0, 1, 3)
        self._sig_smooth = QtWidgets.QCheckBox(self.groupBox_5)
        self._sig_smooth.setObjectName("_sig_smooth")
        self.gridLayout_6.addWidget(self._sig_smooth, 1, 0, 1, 3)
        self.verticalLayout_12.addWidget(self.groupBox_5)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem21)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.QuickSettings.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self._grid_lw = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self._grid_lw.setDecimals(1)
        self._grid_lw.setMinimum(1.0)
        self._grid_lw.setObjectName("_grid_lw")
        self.gridLayout_21.addWidget(self._grid_lw, 0, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_4)
        self.label_45.setObjectName("label_45")
        self.gridLayout_21.addWidget(self.label_45, 0, 0, 1, 1)
        self._grid_smooth = QtWidgets.QCheckBox(self.groupBox_4)
        self._grid_smooth.setObjectName("_grid_smooth")
        self.gridLayout_21.addWidget(self._grid_smooth, 2, 0, 1, 3)
        self.line_40 = QtWidgets.QFrame(self.groupBox_4)
        self.line_40.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.gridLayout_21.addWidget(self.line_40, 0, 1, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem22, 1, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_43 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.gridLayout_20.addWidget(self.label_43, 0, 0, 1, 1)
        self._grid_ncols = QtWidgets.QSpinBox(self.groupBox)
        self._grid_ncols.setMinimum(1)
        self._grid_ncols.setObjectName("_grid_ncols")
        self.gridLayout_20.addWidget(self._grid_ncols, 1, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.gridLayout_20.addWidget(self.label_44, 1, 0, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem23, 3, 2, 1, 1)
        self._grid_nrows = QtWidgets.QSpinBox(self.groupBox)
        self._grid_nrows.setMinimum(1)
        self._grid_nrows.setObjectName("_grid_nrows")
        self.gridLayout_20.addWidget(self._grid_nrows, 0, 2, 1, 1)
        self.line_38 = QtWidgets.QFrame(self.groupBox)
        self.line_38.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.gridLayout_20.addWidget(self.line_38, 0, 1, 1, 1)
        self.line_39 = QtWidgets.QFrame(self.groupBox)
        self.line_39.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.gridLayout_20.addWidget(self.line_39, 1, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem24)
        self._grid_reorg_apply = QtWidgets.QPushButton(self.groupBox)
        self._grid_reorg_apply.setEnabled(False)
        self._grid_reorg_apply.setObjectName("_grid_reorg_apply")
        self.horizontalLayout_11.addWidget(self._grid_reorg_apply)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem25)
        self.gridLayout_20.addLayout(self.horizontalLayout_11, 2, 0, 1, 3)
        self.verticalLayout_5.addWidget(self.groupBox)
        self._grid_titles = QtWidgets.QGroupBox(self.tab_4)
        self._grid_titles.setCheckable(True)
        self._grid_titles.setObjectName("_grid_titles")
        self.gridLayout_19 = QtWidgets.QGridLayout(self._grid_titles)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.line_34 = QtWidgets.QFrame(self._grid_titles)
        self.line_34.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.gridLayout_19.addWidget(self.line_34, 0, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self._grid_titles)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_19.addWidget(self.label_39, 0, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem26, 2, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self._grid_titles)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_19.addWidget(self.label_41, 1, 0, 1, 1)
        self.line_36 = QtWidgets.QFrame(self._grid_titles)
        self.line_36.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_36.setObjectName("line_36")
        self.gridLayout_19.addWidget(self.line_36, 1, 1, 1, 1)
        self._grid_titles_color = QtWidgets.QLineEdit(self._grid_titles)
        self._grid_titles_color.setObjectName("_grid_titles_color")
        self.gridLayout_19.addWidget(self._grid_titles_color, 1, 2, 1, 1)
        self._grid_color_picker = QtWidgets.QToolButton(self._grid_titles)
        self._grid_color_picker.setObjectName("_grid_color_picker")
        self.gridLayout_19.addWidget(self._grid_color_picker, 1, 3, 1, 1)
        self._grid_titles_fz = QtWidgets.QDoubleSpinBox(self._grid_titles)
        self._grid_titles_fz.setDecimals(1)
        self._grid_titles_fz.setMinimum(1.0)
        self._grid_titles_fz.setProperty("value", 10.0)
        self._grid_titles_fz.setObjectName("_grid_titles_fz")
        self.gridLayout_19.addWidget(self._grid_titles_fz, 0, 2, 1, 2)
        self.verticalLayout_5.addWidget(self._grid_titles)
        self.QuickSettings.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_17.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.line_20 = QtWidgets.QFrame(self.groupBox_6)
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout_17.addWidget(self.line_20, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_17.addWidget(self.label_28, 0, 0, 1, 1)
        self._set_bgcolor = QtWidgets.QLineEdit(self.groupBox_6)
        self._set_bgcolor.setObjectName("_set_bgcolor")
        self.gridLayout_17.addWidget(self._set_bgcolor, 0, 2, 1, 1)
        self._set_bgd_picker = QtWidgets.QToolButton(self.groupBox_6)
        self._set_bgd_picker.setObjectName("_set_bgd_picker")
        self.gridLayout_17.addWidget(self._set_bgd_picker, 0, 3, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_6)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_11.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._sig_demean = QtWidgets.QCheckBox(self.groupBox_2)
        self._sig_demean.setObjectName("_sig_demean")
        self.horizontalLayout.addWidget(self._sig_demean)
        self._sig_detrend = QtWidgets.QCheckBox(self.groupBox_2)
        self._sig_detrend.setObjectName("_sig_detrend")
        self.horizontalLayout.addWidget(self._sig_detrend)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self._sig_filt = QtWidgets.QGroupBox(self.groupBox_2)
        self._sig_filt.setCheckable(True)
        self._sig_filt.setChecked(False)
        self._sig_filt.setObjectName("_sig_filt")
        self.gridLayout_4 = QtWidgets.QGridLayout(self._sig_filt)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self._sig_disp = QtWidgets.QComboBox(self._sig_filt)
        self._sig_disp.setObjectName("_sig_disp")
        self._sig_disp.addItem("")
        self._sig_disp.addItem("")
        self._sig_disp.addItem("")
        self._sig_disp.addItem("")
        self.gridLayout_4.addWidget(self._sig_disp, 0, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self._sig_filt)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_4.addWidget(self.label_42, 3, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.line_37 = QtWidgets.QFrame(self._sig_filt)
        self.line_37.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.gridLayout_10.addWidget(self.line_37, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self._sig_filt)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_10.addWidget(self.label_10, 0, 0, 1, 1)
        self._sig_fmin = QtWidgets.QDoubleSpinBox(self._sig_filt)
        self._sig_fmin.setMinimum(0.01)
        self._sig_fmin.setMaximum(10000.0)
        self._sig_fmin.setProperty("value", 8.0)
        self._sig_fmin.setObjectName("_sig_fmin")
        self.gridLayout_10.addWidget(self._sig_fmin, 0, 2, 1, 1)
        self._sig_fmax = QtWidgets.QDoubleSpinBox(self._sig_filt)
        self._sig_fmax.setMinimum(0.01)
        self._sig_fmax.setMaximum(10000.0)
        self._sig_fmax.setProperty("value", 13.0)
        self._sig_fmax.setObjectName("_sig_fmax")
        self.gridLayout_10.addWidget(self._sig_fmax, 1, 2, 1, 1)
        self.line_13 = QtWidgets.QFrame(self._sig_filt)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_10.addWidget(self.line_13, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self._sig_filt)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_10.addWidget(self.label_11, 1, 0, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem27, 2, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_10, 2, 2, 1, 1)
        self.line_11 = QtWidgets.QFrame(self._sig_filt)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_4.addWidget(self.line_11, 2, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self._sig_filt)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_4.addWidget(self.line_7, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self._sig_filt)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self._sig_filter = QtWidgets.QComboBox(self._sig_filt)
        self._sig_filter.setObjectName("_sig_filter")
        self._sig_filter.addItem("")
        self._sig_filter.addItem("")
        self._sig_filter.addItem("")
        self._sig_filter.addItem("")
        self.gridLayout_4.addWidget(self._sig_filter, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self._sig_filt)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.line_43 = QtWidgets.QFrame(self._sig_filt)
        self.line_43.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.gridLayout_4.addWidget(self.line_43, 3, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self._sig_filt)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_4.addWidget(self.line_5, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self._sig_filt)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.line_50 = QtWidgets.QFrame(self._sig_filt)
        self.line_50.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_50.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_50.setObjectName("line_50")
        self.gridLayout_25.addWidget(self.line_50, 1, 1, 1, 1)
        self._sig_order = QtWidgets.QSpinBox(self._sig_filt)
        self._sig_order.setProperty("value", 1)
        self._sig_order.setObjectName("_sig_order")
        self.gridLayout_25.addWidget(self._sig_order, 1, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self._sig_filt)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_25.addWidget(self.label_49, 1, 0, 1, 1)
        self._sig_meth = QtWidgets.QComboBox(self._sig_filt)
        self._sig_meth.setObjectName("_sig_meth")
        self._sig_meth.addItem("")
        self._sig_meth.addItem("")
        self.gridLayout_25.addWidget(self._sig_meth, 0, 2, 1, 1)
        self.line_51 = QtWidgets.QFrame(self._sig_filt)
        self.line_51.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_51.setObjectName("line_51")
        self.gridLayout_25.addWidget(self.line_51, 0, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self._sig_filt)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.gridLayout_25.addWidget(self.label_57, 0, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem28, 2, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_25, 3, 2, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem29, 4, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem30)
        self._sig_filt_apply = QtWidgets.QPushButton(self._sig_filt)
        self._sig_filt_apply.setObjectName("_sig_filt_apply")
        self.horizontalLayout_4.addWidget(self._sig_filt_apply)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem31)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 5, 0, 1, 3)
        self.verticalLayout_11.addWidget(self._sig_filt)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem32)
        self.QuickSettings.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self._annot_table = QtWidgets.QTableWidget(self.tab_3)
        self._annot_table.setAlternatingRowColors(True)
        self._annot_table.setObjectName("_annot_table")
        self._annot_table.setColumnCount(4)
        self._annot_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self._annot_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self._annot_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self._annot_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self._annot_table.setHorizontalHeaderItem(3, item)
        self.verticalLayout_6.addWidget(self._annot_table)
        self._annot_viz = QtWidgets.QGroupBox(self.tab_3)
        self._annot_viz.setCheckable(True)
        self._annot_viz.setChecked(False)
        self._annot_viz.setObjectName("_annot_viz")
        self.gridLayout_18 = QtWidgets.QGridLayout(self._annot_viz)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.line_33 = QtWidgets.QFrame(self._annot_viz)
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.gridLayout_18.addWidget(self.line_33, 1, 1, 1, 1)
        self._annot_color = QtWidgets.QLineEdit(self._annot_viz)
        self._annot_color.setObjectName("_annot_color")
        self.gridLayout_18.addWidget(self._annot_color, 2, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self._annot_viz)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_18.addWidget(self.label_35, 0, 0, 1, 1)
        self.line_35 = QtWidgets.QFrame(self._annot_viz)
        self.line_35.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.gridLayout_18.addWidget(self.line_35, 2, 1, 1, 1)
        self.line_32 = QtWidgets.QFrame(self._annot_viz)
        self.line_32.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.gridLayout_18.addWidget(self.line_32, 0, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self._annot_viz)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.gridLayout_18.addWidget(self.label_38, 1, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self._annot_viz)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_18.addWidget(self.label_40, 2, 0, 1, 1)
        self._sig_annot_picker = QtWidgets.QToolButton(self._annot_viz)
        self._sig_annot_picker.setObjectName("_sig_annot_picker")
        self.gridLayout_18.addWidget(self._sig_annot_picker, 2, 3, 1, 1)
        self._annot_marksz = QtWidgets.QDoubleSpinBox(self._annot_viz)
        self._annot_marksz.setMinimum(1.0)
        self._annot_marksz.setMaximum(500.0)
        self._annot_marksz.setProperty("value", 13.0)
        self._annot_marksz.setObjectName("_annot_marksz")
        self.gridLayout_18.addWidget(self._annot_marksz, 1, 2, 1, 2)
        self._annot_txtsz = QtWidgets.QDoubleSpinBox(self._annot_viz)
        self._annot_txtsz.setDecimals(1)
        self._annot_txtsz.setMinimum(1.0)
        self._annot_txtsz.setMaximum(500.0)
        self._annot_txtsz.setProperty("value", 14.0)
        self._annot_txtsz.setObjectName("_annot_txtsz")
        self.gridLayout_18.addWidget(self._annot_txtsz, 0, 2, 1, 2)
        self.verticalLayout_6.addWidget(self._annot_viz)
        self.QuickSettings.addTab(self.tab_3, "")
        self.verticalLayout_4.addWidget(self.QuickSettings)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self._GridWidget = QtWidgets.QWidget(self.widget1)
        self._GridWidget.setObjectName("_GridWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self._GridWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self._GridLayout = QtWidgets.QVBoxLayout()
        self._GridLayout.setContentsMargins(-1, 0, -1, -1)
        self._GridLayout.setObjectName("_GridLayout")
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._GridLayout.addItem(spacerItem33)
        self.verticalLayout_8.addLayout(self._GridLayout)
        self.horizontalLayout_7.addWidget(self._GridWidget)
        self._SignalWidget = QtWidgets.QWidget(self.widget1)
        self._SignalWidget.setObjectName("_SignalWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self._SignalWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self._SignalLayout = QtWidgets.QVBoxLayout()
        self._SignalLayout.setContentsMargins(-1, 0, 0, -1)
        self._SignalLayout.setObjectName("_SignalLayout")
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._SignalLayout.addItem(spacerItem34)
        self.verticalLayout_7.addLayout(self._SignalLayout)
        self.horizontalLayout_7.addWidget(self._SignalWidget)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self._sig_next = QtWidgets.QPushButton(self.widget1)
        self._sig_next.setObjectName("_sig_next")
        self.gridLayout_8.addWidget(self._sig_next, 0, 6, 1, 1)
        self._txt_shape = QtWidgets.QLabel(self.widget1)
        self._txt_shape.setObjectName("_txt_shape")
        self.gridLayout_8.addWidget(self._txt_shape, 0, 4, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem35, 0, 0, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem36, 0, 5, 1, 1)
        self._sig_prev = QtWidgets.QPushButton(self.widget1)
        self._sig_prev.setObjectName("_sig_prev")
        self.gridLayout_8.addWidget(self._sig_prev, 0, 1, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem37, 0, 2, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem38, 0, 7, 1, 1)
        self._sig_index = QtWidgets.QSpinBox(self.widget1)
        self._sig_index.setObjectName("_sig_index")
        self.gridLayout_8.addWidget(self._sig_index, 0, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_8)
        self.horizontalLayout_10.addWidget(self.splitter)
        self.q_widget.raise_()
        self.q_widget.raise_()
        self.horizontalLayout_2.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1197, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSave = QtWidgets.QMenu(self.menuFile)
        self.menuSave.setObjectName("menuSave")
        self.menuLoad = QtWidgets.QMenu(self.menuFile)
        self.menuLoad.setObjectName("menuLoad")
        self.menuDisplay = QtWidgets.QMenu(self.menubar)
        self.menuDisplay.setObjectName("menuDisplay")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionCortical_repartition = QtWidgets.QAction(MainWindow)
        self.actionCortical_repartition.setObjectName("actionCortical_repartition")
        self.actionCortical = QtWidgets.QAction(MainWindow)
        self.actionCortical.setObjectName("actionCortical")
        self.actionSagittal = QtWidgets.QAction(MainWindow)
        self.actionSagittal.setObjectName("actionSagittal")
        self.actionAxial = QtWidgets.QAction(MainWindow)
        self.actionAxial.setObjectName("actionAxial")
        self.actionCamera = QtWidgets.QAction(MainWindow)
        self.actionCamera.setObjectName("actionCamera")
        self.actionLeft = QtWidgets.QAction(MainWindow)
        self.actionLeft.setObjectName("actionLeft")
        self.actionRight = QtWidgets.QAction(MainWindow)
        self.actionRight.setObjectName("actionRight")
        self.menuDispSettings = QtWidgets.QAction(MainWindow)
        self.menuDispSettings.setCheckable(True)
        self.menuDispSettings.setChecked(True)
        self.menuDispSettings.setObjectName("menuDispSettings")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionProjection = QtWidgets.QAction(MainWindow)
        self.actionProjection.setObjectName("actionProjection")
        self.actionRepartition = QtWidgets.QAction(MainWindow)
        self.actionRepartition.setObjectName("actionRepartition")
        self.actionShortcuts = QtWidgets.QAction(MainWindow)
        self.actionShortcuts.setCheckable(True)
        self.actionShortcuts.setObjectName("actionShortcuts")
        self.actionUi_settings = QtWidgets.QAction(MainWindow)
        self.actionUi_settings.setCheckable(True)
        self.actionUi_settings.setChecked(False)
        self.actionUi_settings.setObjectName("actionUi_settings")
        self.actionNdPlt = QtWidgets.QAction(MainWindow)
        self.actionNdPlt.setCheckable(True)
        self.actionNdPlt.setObjectName("actionNdPlt")
        self.actionOnedPlt = QtWidgets.QAction(MainWindow)
        self.actionOnedPlt.setCheckable(True)
        self.actionOnedPlt.setObjectName("actionOnedPlt")
        self.actionImage = QtWidgets.QAction(MainWindow)
        self.actionImage.setCheckable(True)
        self.actionImage.setObjectName("actionImage")
        self.actionColormap = QtWidgets.QAction(MainWindow)
        self.actionColormap.setCheckable(True)
        self.actionColormap.setObjectName("actionColormap")
        self.menuShortcut = QtWidgets.QAction(MainWindow)
        self.menuShortcut.setObjectName("menuShortcut")
        self.menuDocumentation = QtWidgets.QAction(MainWindow)
        self.menuDocumentation.setObjectName("menuDocumentation")
        self.actionScreenshot = QtWidgets.QAction(MainWindow)
        self.actionScreenshot.setObjectName("actionScreenshot")
        self.actionSave_hypnogram = QtWidgets.QAction(MainWindow)
        self.actionSave_hypnogram.setObjectName("actionSave_hypnogram")
        self.actionSave_infos = QtWidgets.QAction(MainWindow)
        self.actionSave_infos.setObjectName("actionSave_infos")
        self.actionSave_scoring = QtWidgets.QAction(MainWindow)
        self.actionSave_scoring.setObjectName("actionSave_scoring")
        self.actionSave_detection = QtWidgets.QAction(MainWindow)
        self.actionSave_detection.setObjectName("actionSave_detection")
        self.actionSave_all = QtWidgets.QAction(MainWindow)
        self.actionSave_all.setObjectName("actionSave_all")
        self.menuExit = QtWidgets.QAction(MainWindow)
        self.menuExit.setObjectName("menuExit")
        self.actionLoad_hypnogram = QtWidgets.QAction(MainWindow)
        self.actionLoad_hypnogram.setObjectName("actionLoad_hypnogram")
        self.menuSaveInfoTable = QtWidgets.QAction(MainWindow)
        self.menuSaveInfoTable.setObjectName("menuSaveInfoTable")
        self.menuSaveScoringTable = QtWidgets.QAction(MainWindow)
        self.menuSaveScoringTable.setObjectName("menuSaveScoringTable")
        self.actionAll = QtWidgets.QAction(MainWindow)
        self.actionAll.setObjectName("actionAll")
        self.menuLoadHypno = QtWidgets.QAction(MainWindow)
        self.menuLoadHypno.setObjectName("menuLoadHypno")
        self.menuLoadData = QtWidgets.QAction(MainWindow)
        self.menuLoadData.setEnabled(False)
        self.menuLoadData.setObjectName("menuLoadData")
        self.actionHypnogram_figure = QtWidgets.QAction(MainWindow)
        self.actionHypnogram_figure.setObjectName("actionHypnogram_figure")
        self.menuLoadConfig = QtWidgets.QAction(MainWindow)
        self.menuLoadConfig.setObjectName("menuLoadConfig")
        self.menuSaveConfig = QtWidgets.QAction(MainWindow)
        self.menuSaveConfig.setObjectName("menuSaveConfig")
        self.menuDownload_pdf_doc = QtWidgets.QAction(MainWindow)
        self.menuDownload_pdf_doc.setObjectName("menuDownload_pdf_doc")
        self.menuSaveHypnogramFigure = QtWidgets.QAction(MainWindow)
        self.menuSaveHypnogramFigure.setObjectName("menuSaveHypnogramFigure")
        self.menuSaveHypnogramData = QtWidgets.QAction(MainWindow)
        self.menuSaveHypnogramData.setObjectName("menuSaveHypnogramData")
        self.menuSaveDetectAll = QtWidgets.QAction(MainWindow)
        self.menuSaveDetectAll.setObjectName("menuSaveDetectAll")
        self.menuSaveDetectSelected = QtWidgets.QAction(MainWindow)
        self.menuSaveDetectSelected.setObjectName("menuSaveDetectSelected")
        self.menuSaveScreenshotEntire = QtWidgets.QAction(MainWindow)
        self.menuSaveScreenshotEntire.setObjectName("menuSaveScreenshotEntire")
        self.menuSaveScreenshotSelected = QtWidgets.QAction(MainWindow)
        self.menuSaveScreenshotSelected.setEnabled(False)
        self.menuSaveScreenshotSelected.setObjectName("menuSaveScreenshotSelected")
        self.menuLoadDetectAll = QtWidgets.QAction(MainWindow)
        self.menuLoadDetectAll.setObjectName("menuLoadDetectAll")
        self.menuLoadDetectSelect = QtWidgets.QAction(MainWindow)
        self.menuLoadDetectSelect.setObjectName("menuLoadDetectSelect")
        self.menuDispSpec = QtWidgets.QAction(MainWindow)
        self.menuDispSpec.setCheckable(True)
        self.menuDispSpec.setChecked(True)
        self.menuDispSpec.setObjectName("menuDispSpec")
        self.menuDispHypno = QtWidgets.QAction(MainWindow)
        self.menuDispHypno.setCheckable(True)
        self.menuDispHypno.setChecked(True)
        self.menuDispHypno.setObjectName("menuDispHypno")
        self.menuDispNavbar = QtWidgets.QAction(MainWindow)
        self.menuDispNavbar.setCheckable(True)
        self.menuDispNavbar.setChecked(True)
        self.menuDispNavbar.setObjectName("menuDispNavbar")
        self.menuDispTimeax = QtWidgets.QAction(MainWindow)
        self.menuDispTimeax.setCheckable(True)
        self.menuDispTimeax.setChecked(True)
        self.menuDispTimeax.setObjectName("menuDispTimeax")
        self.menuDispTopo = QtWidgets.QAction(MainWindow)
        self.menuDispTopo.setCheckable(True)
        self.menuDispTopo.setObjectName("menuDispTopo")
        self.menuDispIndic = QtWidgets.QAction(MainWindow)
        self.menuDispIndic.setCheckable(True)
        self.menuDispIndic.setChecked(True)
        self.menuDispIndic.setObjectName("menuDispIndic")
        self.actionZoom_mode = QtWidgets.QAction(MainWindow)
        self.actionZoom_mode.setCheckable(True)
        self.actionZoom_mode.setObjectName("actionZoom_mode")
        self.menuDispZoom = QtWidgets.QAction(MainWindow)
        self.menuDispZoom.setCheckable(True)
        self.menuDispZoom.setObjectName("menuDispZoom")
        self.menuSettingCleanHyp = QtWidgets.QAction(MainWindow)
        self.menuSettingCleanHyp.setObjectName("menuSettingCleanHyp")
        self.menuSaveAnnotations = QtWidgets.QAction(MainWindow)
        self.menuSaveAnnotations.setObjectName("menuSaveAnnotations")
        self.menuLoadAnnotations = QtWidgets.QAction(MainWindow)
        self.menuLoadAnnotations.setObjectName("menuLoadAnnotations")
        self.menuScreenshot = QtWidgets.QAction(MainWindow)
        self.menuScreenshot.setObjectName("menuScreenshot")
        self.actionGrid = QtWidgets.QAction(MainWindow)
        self.actionGrid.setCheckable(True)
        self.actionGrid.setChecked(True)
        self.actionGrid.setObjectName("actionGrid")
        self.actionSignal = QtWidgets.QAction(MainWindow)
        self.actionSignal.setCheckable(True)
        self.actionSignal.setChecked(True)
        self.actionSignal.setObjectName("actionSignal")
        self.actionQSP = QtWidgets.QAction(MainWindow)
        self.actionQSP.setCheckable(True)
        self.actionQSP.setChecked(True)
        self.actionQSP.setObjectName("actionQSP")
        self.saveAnnotations = QtWidgets.QAction(MainWindow)
        self.saveAnnotations.setObjectName("saveAnnotations")
        self.loadAnnotations = QtWidgets.QAction(MainWindow)
        self.loadAnnotations.setObjectName("loadAnnotations")
        self.menuSave.addAction(self.saveAnnotations)
        self.menuLoad.addAction(self.loadAnnotations)
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addAction(self.menuLoad.menuAction())
        self.menuFile.addAction(self.menuScreenshot)
        self.menuDisplay.addAction(self.actionQSP)
        self.menuDisplay.addAction(self.actionGrid)
        self.menuDisplay.addAction(self.actionSignal)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())

        self.retranslateUi(MainWindow)
        self.QuickSettings.setCurrentIndex(0)
        self._PlottingForm.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Signal"))
        self.QuickSettings.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Axis and label"))
        self.label_4.setText(_translate("MainWindow", "title"))
        self.label_20.setText(_translate("MainWindow", "Axis\n"
"color"))
        self.label_29.setText(_translate("MainWindow", "ticks"))
        self.label_3.setText(_translate("MainWindow", "label"))
        self._axis_color.setPlaceholderText(_translate("MainWindow", "black, #ab4642, (0, 0, 0)..."))
        self.label_9.setText(_translate("MainWindow", "Signal\n"
"color"))
        self._sig_color.setPlaceholderText(_translate("MainWindow", "black, #ab4642, (0, 0, 0)..."))
        self._sig_ax_picker.setText(_translate("MainWindow", "..."))
        self.label_21.setText(_translate("MainWindow", "Text"))
        self.label_22.setText(_translate("MainWindow", "Font\n"
"size"))
        self._sig_title.setPlaceholderText(_translate("MainWindow", "Title for the signal layout"))
        self.label_23.setText(_translate("MainWindow", "x-label"))
        self._sig_xlab.setPlaceholderText(_translate("MainWindow", "X-label for the signal layout"))
        self.label_24.setText(_translate("MainWindow", "Font\n"
"size"))
        self.label_25.setText(_translate("MainWindow", "y-label"))
        self._sig_ylab.setPlaceholderText(_translate("MainWindow", "Y-label for the signal layout"))
        self._sig_sig_picker.setText(_translate("MainWindow", "..."))
        self.groupBox_5.setTitle(_translate("MainWindow", "Plotting form"))
        self.label_12.setText(_translate("MainWindow", "Form"))
        self._sig_form.setItemText(0, _translate("MainWindow", "line"))
        self._sig_form.setItemText(1, _translate("MainWindow", "marker"))
        self._sig_form.setItemText(2, _translate("MainWindow", "histogram"))
        self._sig_form.setItemText(3, _translate("MainWindow", "tf"))
        self._sig_form.setItemText(4, _translate("MainWindow", "psd"))
        self._sig_form.setItemText(5, _translate("MainWindow", "butterfly"))
        self._sig_amp.setTitle(_translate("MainWindow", "Amplitude"))
        self.label_2.setText(_translate("MainWindow", "Max"))
        self.label.setText(_translate("MainWindow", "Min"))
        self._sig_th.setTitle(_translate("MainWindow", "Threshold"))
        self.label_30.setText(_translate("MainWindow", "min"))
        self.label_31.setText(_translate("MainWindow", "max"))
        self.label_15.setText(_translate("MainWindow", "linewidth"))
        self.label_19.setText(_translate("MainWindow", "Size"))
        self.label_27.setText(_translate("MainWindow", "Symbol"))
        self._sig_symbol.setItemText(0, _translate("MainWindow", "disc"))
        self._sig_symbol.setItemText(1, _translate("MainWindow", "arrow"))
        self._sig_symbol.setItemText(2, _translate("MainWindow", "ring"))
        self._sig_symbol.setItemText(3, _translate("MainWindow", "clobber"))
        self._sig_symbol.setItemText(4, _translate("MainWindow", "square"))
        self._sig_symbol.setItemText(5, _translate("MainWindow", "diamond"))
        self._sig_symbol.setItemText(6, _translate("MainWindow", "vbar"))
        self._sig_symbol.setItemText(7, _translate("MainWindow", "hbar"))
        self._sig_symbol.setItemText(8, _translate("MainWindow", "cross"))
        self._sig_symbol.setItemText(9, _translate("MainWindow", "tailed_arrow"))
        self._sig_symbol.setItemText(10, _translate("MainWindow", "x"))
        self._sig_symbol.setItemText(11, _translate("MainWindow", "triangle_up"))
        self._sig_symbol.setItemText(12, _translate("MainWindow", "triangle_down"))
        self._sig_symbol.setItemText(13, _translate("MainWindow", "star"))
        self.label_18.setText(_translate("MainWindow", "nbins"))
        self._sig_tf_apply.setText(_translate("MainWindow", "Apply"))
        self._sig_tf_interp.setItemText(0, _translate("MainWindow", "gaussian"))
        self._sig_tf_interp.setItemText(1, _translate("MainWindow", "nearest"))
        self._sig_tf_interp.setItemText(2, _translate("MainWindow", "bilinear"))
        self._sig_tf_interp.setItemText(3, _translate("MainWindow", "quadric"))
        self._sig_tf_interp.setItemText(4, _translate("MainWindow", "bicubic"))
        self._sig_tf_interp.setItemText(5, _translate("MainWindow", "hanning"))
        self._sig_tf_interp.setItemText(6, _translate("MainWindow", "hamming"))
        self._sig_tf_interp.setItemText(7, _translate("MainWindow", "blackman"))
        self._sig_tf_interp.setItemText(8, _translate("MainWindow", "kaiser"))
        self._sig_tf_interp.setItemText(9, _translate("MainWindow", "hermite"))
        self._sig_tf_interp.setItemText(10, _translate("MainWindow", "catrom"))
        self._sig_tf_interp.setItemText(11, _translate("MainWindow", "mitchell"))
        self._sig_tf_interp.setItemText(12, _translate("MainWindow", "spline16"))
        self._sig_tf_interp.setItemText(13, _translate("MainWindow", "spline36"))
        self._sig_tf_interp.setItemText(14, _translate("MainWindow", "bessel"))
        self._sig_tf_interp.setItemText(15, _translate("MainWindow", "sinc"))
        self._sig_tf_interp.setItemText(16, _translate("MainWindow", "lanczos"))
        self.label_26.setText(_translate("MainWindow", "Interpolation"))
        self.label_6.setText(_translate("MainWindow", "Normalization"))
        self._sig_baseline.setTitle(_translate("MainWindow", "Baseline"))
        self.label_13.setText(_translate("MainWindow", "Start"))
        self.label_14.setText(_translate("MainWindow", "End"))
        self._sig_averaging.setTitle(_translate("MainWindow", "Averaging"))
        self.label_17.setText(_translate("MainWindow", "Overlap"))
        self.label_16.setText(_translate("MainWindow", "Window"))
        self._sig_norm.setItemText(0, _translate("MainWindow", "No normalization"))
        self._sig_norm.setItemText(1, _translate("MainWindow", "Subtract the mean"))
        self._sig_norm.setItemText(2, _translate("MainWindow", "Divide by the mean"))
        self._sig_norm.setItemText(3, _translate("MainWindow", "Subtract then divide by the mean"))
        self._sig_norm.setItemText(4, _translate("MainWindow", "Z-score"))
        self._sig_tf_clim.setTitle(_translate("MainWindow", "Colorbar limits"))
        self.label_32.setText(_translate("MainWindow", "Start"))
        self.label_33.setText(_translate("MainWindow", "End"))
        self.label_34.setText(_translate("MainWindow", "Colormap"))
        self._sig_tf_rev.setText(_translate("MainWindow", "Reversed"))
        self.label_36.setText(_translate("MainWindow", "nperseg"))
        self.label_37.setText(_translate("MainWindow", "noverlap"))
        self._sig_smooth.setText(_translate("MainWindow", "Use smooth lines"))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.tab), _translate("MainWindow", "Signal"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Settings"))
        self.label_45.setText(_translate("MainWindow", "Line\n"
"width"))
        self._grid_smooth.setText(_translate("MainWindow", "Use smooth lines"))
        self.groupBox.setTitle(_translate("MainWindow", "Grid organization"))
        self.label_43.setText(_translate("MainWindow", "Number of\n"
"rows"))
        self.label_44.setText(_translate("MainWindow", "Number of\n"
"columns"))
        self._grid_reorg_apply.setText(_translate("MainWindow", "Apply"))
        self._grid_titles.setTitle(_translate("MainWindow", "Titles"))
        self.label_39.setText(_translate("MainWindow", "Font\n"
"size"))
        self.label_41.setText(_translate("MainWindow", "Color"))
        self._grid_titles_color.setPlaceholderText(_translate("MainWindow", "black, #ab4642, (0, 0, 0)..."))
        self._grid_color_picker.setText(_translate("MainWindow", "..."))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.tab_4), _translate("MainWindow", "Grid"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Color"))
        self.label_28.setText(_translate("MainWindow", "Background"))
        self._set_bgcolor.setPlaceholderText(_translate("MainWindow", "black, #ab4642, (0, 0, 0)..."))
        self._set_bgd_picker.setText(_translate("MainWindow", "..."))
        self.groupBox_2.setTitle(_translate("MainWindow", "Signal processing"))
        self._sig_demean.setText(_translate("MainWindow", "Demean"))
        self._sig_detrend.setText(_translate("MainWindow", "Detrend"))
        self._sig_filt.setTitle(_translate("MainWindow", "Filtering"))
        self._sig_disp.setItemText(0, _translate("MainWindow", "filter"))
        self._sig_disp.setItemText(1, _translate("MainWindow", "amplitude"))
        self._sig_disp.setItemText(2, _translate("MainWindow", "power"))
        self._sig_disp.setItemText(3, _translate("MainWindow", "phase"))
        self.label_42.setText(_translate("MainWindow", "Settings"))
        self.label_10.setText(_translate("MainWindow", "Fmin"))
        self.label_11.setText(_translate("MainWindow", "Fmax"))
        self.label_8.setText(_translate("MainWindow", "Frequency"))
        self._sig_filter.setItemText(0, _translate("MainWindow", "bandpass"))
        self._sig_filter.setItemText(1, _translate("MainWindow", "bandstop"))
        self._sig_filter.setItemText(2, _translate("MainWindow", "lowpass"))
        self._sig_filter.setItemText(3, _translate("MainWindow", "highpass"))
        self.label_5.setText(_translate("MainWindow", "Display"))
        self.label_7.setText(_translate("MainWindow", "Filter\n"
"type"))
        self.label_49.setText(_translate("MainWindow", "Order"))
        self._sig_meth.setItemText(0, _translate("MainWindow", "butterworth"))
        self._sig_meth.setItemText(1, _translate("MainWindow", "bessel"))
        self.label_57.setText(_translate("MainWindow", "Method"))
        self._sig_filt_apply.setText(_translate("MainWindow", "Apply"))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.tab_2), _translate("MainWindow", "Settings"))
        item = self._annot_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time"))
        item = self._annot_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Amplitude"))
        item = self._annot_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Signal"))
        item = self._annot_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Text"))
        self._annot_viz.setTitle(_translate("MainWindow", "Appearance"))
        self._annot_color.setPlaceholderText(_translate("MainWindow", "black, #ab4642, (0, 0, 0)..."))
        self.label_35.setText(_translate("MainWindow", "Text size"))
        self.label_38.setText(_translate("MainWindow", "Marker size"))
        self.label_40.setText(_translate("MainWindow", "Color"))
        self._sig_annot_picker.setText(_translate("MainWindow", "..."))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.tab_3), _translate("MainWindow", "Annotations"))
        self._sig_next.setText(_translate("MainWindow", "Next >>"))
        self._txt_shape.setText(_translate("MainWindow", "[shape]"))
        self._sig_prev.setText(_translate("MainWindow", " << Previous"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.menuLoad.setTitle(_translate("MainWindow", "Load"))
        self.menuDisplay.setTitle(_translate("MainWindow", "Display"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionCortical_repartition.setText(_translate("MainWindow", "Cortical repartition"))
        self.actionCortical.setText(_translate("MainWindow", "Cortical"))
        self.actionSagittal.setText(_translate("MainWindow", "Sagittal"))
        self.actionAxial.setText(_translate("MainWindow", "Axial"))
        self.actionCamera.setText(_translate("MainWindow", "Camera"))
        self.actionLeft.setText(_translate("MainWindow", "Left"))
        self.actionRight.setText(_translate("MainWindow", "Right"))
        self.menuDispSettings.setText(_translate("MainWindow", "Quick settings"))
        self.menuDispSettings.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionProjection.setText(_translate("MainWindow", "Projection"))
        self.actionProjection.setToolTip(_translate("MainWindow", "<html><head/><body><p>Find all vertices under a distance of t_radius with each source and project s_data to the surface</p></body></html>"))
        self.actionProjection.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionRepartition.setText(_translate("MainWindow", "Repartition"))
        self.actionRepartition.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionShortcuts.setText(_translate("MainWindow", "Shortcuts"))
        self.actionShortcuts.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionUi_settings.setText(_translate("MainWindow", "Ui settings"))
        self.actionNdPlt.setText(_translate("MainWindow", "Nd-plot"))
        self.actionOnedPlt.setText(_translate("MainWindow", "1d-plot"))
        self.actionImage.setText(_translate("MainWindow", "Image"))
        self.actionColormap.setText(_translate("MainWindow", "Colormap"))
        self.menuShortcut.setText(_translate("MainWindow", "Shortcuts"))
        self.menuShortcut.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.menuDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.menuDocumentation.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionScreenshot.setText(_translate("MainWindow", "Screenshot"))
        self.actionScreenshot.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave_hypnogram.setText(_translate("MainWindow", "Save hypnogram data"))
        self.actionSave_infos.setText(_translate("MainWindow", "Save infos table"))
        self.actionSave_scoring.setText(_translate("MainWindow", "Save scoring table"))
        self.actionSave_detection.setText(_translate("MainWindow", "Save detection table"))
        self.actionSave_all.setText(_translate("MainWindow", "Save all"))
        self.menuExit.setText(_translate("MainWindow", "Exit"))
        self.menuExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionLoad_hypnogram.setText(_translate("MainWindow", "Load hypnogram"))
        self.menuSaveInfoTable.setText(_translate("MainWindow", "Stats info table"))
        self.menuSaveScoringTable.setText(_translate("MainWindow", "Scoring table"))
        self.actionAll.setText(_translate("MainWindow", "All"))
        self.actionAll.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.menuLoadHypno.setText(_translate("MainWindow", "Hypnogram"))
        self.menuLoadData.setText(_translate("MainWindow", "Data"))
        self.actionHypnogram_figure.setText(_translate("MainWindow", "Hypnogram figure"))
        self.menuLoadConfig.setText(_translate("MainWindow", "GUI config"))
        self.menuSaveConfig.setText(_translate("MainWindow", "GUI config"))
        self.menuDownload_pdf_doc.setText(_translate("MainWindow", "Download pdf doc"))
        self.menuSaveHypnogramFigure.setText(_translate("MainWindow", "Figure"))
        self.menuSaveHypnogramData.setText(_translate("MainWindow", "Data"))
        self.menuSaveDetectAll.setText(_translate("MainWindow", "All detections"))
        self.menuSaveDetectSelected.setText(_translate("MainWindow", "Selected detection"))
        self.menuSaveScreenshotEntire.setText(_translate("MainWindow", "Entire window"))
        self.menuSaveScreenshotSelected.setText(_translate("MainWindow", "Selected canvas"))
        self.menuLoadDetectAll.setText(_translate("MainWindow", "All"))
        self.menuLoadDetectSelect.setText(_translate("MainWindow", "Selected"))
        self.menuDispSpec.setText(_translate("MainWindow", "Spectrogram"))
        self.menuDispSpec.setShortcut(_translate("MainWindow", "S"))
        self.menuDispHypno.setText(_translate("MainWindow", "Hypnogram"))
        self.menuDispHypno.setShortcut(_translate("MainWindow", "H"))
        self.menuDispNavbar.setText(_translate("MainWindow", "Navigation bar"))
        self.menuDispNavbar.setShortcut(_translate("MainWindow", "P"))
        self.menuDispTimeax.setText(_translate("MainWindow", "Time axis"))
        self.menuDispTimeax.setShortcut(_translate("MainWindow", "X"))
        self.menuDispTopo.setText(_translate("MainWindow", "Topoplot"))
        self.menuDispTopo.setShortcut(_translate("MainWindow", "T"))
        self.menuDispIndic.setText(_translate("MainWindow", "Time indicators"))
        self.menuDispIndic.setShortcut(_translate("MainWindow", "I"))
        self.actionZoom_mode.setText(_translate("MainWindow", "Zoom mode"))
        self.actionZoom_mode.setShortcut(_translate("MainWindow", "Z"))
        self.menuDispZoom.setText(_translate("MainWindow", "Zoom mode"))
        self.menuDispZoom.setShortcut(_translate("MainWindow", "Z"))
        self.menuSettingCleanHyp.setText(_translate("MainWindow", "Clean hypnogram"))
        self.menuSaveAnnotations.setText(_translate("MainWindow", "Annotation"))
        self.menuLoadAnnotations.setText(_translate("MainWindow", "Annotations"))
        self.menuScreenshot.setText(_translate("MainWindow", "Screenshot"))
        self.menuScreenshot.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionGrid.setText(_translate("MainWindow", "Grid"))
        self.actionGrid.setShortcut(_translate("MainWindow", "G"))
        self.actionSignal.setText(_translate("MainWindow", "Signal"))
        self.actionSignal.setShortcut(_translate("MainWindow", "S"))
        self.actionQSP.setText(_translate("MainWindow", "Quick settings panel"))
        self.actionQSP.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.saveAnnotations.setText(_translate("MainWindow", "Annotations"))
        self.loadAnnotations.setText(_translate("MainWindow", "Annotations"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

