# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/etienne/Toolbox/visbrain/visbrain/sleep/interface/gui/sleep_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1328, 919)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.q_widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q_widget.sizePolicy().hasHeightForWidth())
        self.q_widget.setSizePolicy(sizePolicy)
        self.q_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.q_widget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.q_widget.setObjectName(_fromUtf8("q_widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.q_widget)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.QuickSettings = QtGui.QTabWidget(self.q_widget)
        self.QuickSettings.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.QuickSettings.setAutoFillBackground(False)
        self.QuickSettings.setTabShape(QtGui.QTabWidget.Rounded)
        self.QuickSettings.setMovable(True)
        self.QuickSettings.setObjectName(_fromUtf8("QuickSettings"))
        self.q_Panels = QtGui.QWidget()
        self.q_Panels.setObjectName(_fromUtf8("q_Panels"))
        self.verticalLayout = QtGui.QVBoxLayout(self.q_Panels)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.q_Panels)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 376, 787))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self._PanScrollChan = QtGui.QScrollArea(self.groupBox)
        self._PanScrollChan.setWidgetResizable(True)
        self._PanScrollChan.setObjectName(_fromUtf8("_PanScrollChan"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 330, 70))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self._PanChanLay = QtGui.QGridLayout()
        self._PanChanLay.setObjectName(_fromUtf8("_PanChanLay"))
        self.verticalLayout_14.addLayout(self._PanChanLay)
        self._PanScrollChan.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_13.addWidget(self._PanScrollChan)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self._PanChanSelectAll = QtGui.QPushButton(self.groupBox)
        self._PanChanSelectAll.setObjectName(_fromUtf8("_PanChanSelectAll"))
        self.horizontalLayout.addWidget(self._PanChanSelectAll)
        self._PanChanDeselectAll = QtGui.QPushButton(self.groupBox)
        self._PanChanDeselectAll.setObjectName(_fromUtf8("_PanChanDeselectAll"))
        self.horizontalLayout.addWidget(self._PanChanDeselectAll)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line.setMinimumSize(QtCore.QSize(200, 0))
        self.line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_5.addWidget(self.line)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self._PanSpecViz = QtGui.QCheckBox(self.groupBox_2)
        self._PanSpecViz.setChecked(True)
        self._PanSpecViz.setObjectName(_fromUtf8("_PanSpecViz"))
        self.gridLayout_6.addWidget(self._PanSpecViz, 0, 0, 1, 1)
        self._PanSpecZoom = QtGui.QCheckBox(self.groupBox_2)
        self._PanSpecZoom.setObjectName(_fromUtf8("_PanSpecZoom"))
        self.gridLayout_6.addWidget(self._PanSpecZoom, 0, 1, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_6)
        self._PanSpecW = QtGui.QWidget(self.groupBox_2)
        self._PanSpecW.setObjectName(_fromUtf8("_PanSpecW"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self._PanSpecW)
        self.verticalLayout_20.setMargin(0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSpacing(9)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_15 = QtGui.QLabel(self._PanSpecW)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 2, 0, 1, 1)
        self._PanSpecFstart = QtGui.QDoubleSpinBox(self._PanSpecW)
        self._PanSpecFstart.setDecimals(1)
        self._PanSpecFstart.setMinimum(0.5)
        self._PanSpecFstart.setMaximum(190.0)
        self._PanSpecFstart.setObjectName(_fromUtf8("_PanSpecFstart"))
        self.gridLayout_5.addWidget(self._PanSpecFstart, 3, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self._PanSpecW)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 1)
        self._PanSpecChan = QtGui.QComboBox(self._PanSpecW)
        self._PanSpecChan.setObjectName(_fromUtf8("_PanSpecChan"))
        self.gridLayout_5.addWidget(self._PanSpecChan, 0, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self._PanSpecW)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 3, 0, 1, 1)
        self._PanSpecFend = QtGui.QDoubleSpinBox(self._PanSpecW)
        self._PanSpecFend.setDecimals(1)
        self._PanSpecFend.setMinimum(0.1)
        self._PanSpecFend.setMaximum(200.0)
        self._PanSpecFend.setProperty("value", 25.0)
        self._PanSpecFend.setObjectName(_fromUtf8("_PanSpecFend"))
        self.gridLayout_5.addWidget(self._PanSpecFend, 3, 6, 1, 1)
        self.label_14 = QtGui.QLabel(self._PanSpecW)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self._PanSpecW)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_5.addWidget(self.label_29, 5, 0, 1, 1)
        self._PanSpecCmap = QtGui.QComboBox(self._PanSpecW)
        self._PanSpecCmap.setObjectName(_fromUtf8("_PanSpecCmap"))
        self.gridLayout_5.addWidget(self._PanSpecCmap, 5, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self._PanSpecW)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_5.addWidget(self.label_23, 2, 3, 1, 1)
        self._PanSpecNfft = QtGui.QDoubleSpinBox(self._PanSpecW)
        self._PanSpecNfft.setDecimals(1)
        self._PanSpecNfft.setMinimum(0.1)
        self._PanSpecNfft.setMaximum(1000.0)
        self._PanSpecNfft.setProperty("value", 30.0)
        self._PanSpecNfft.setObjectName(_fromUtf8("_PanSpecNfft"))
        self.gridLayout_5.addWidget(self._PanSpecNfft, 1, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 3, 3, 1, 1)
        self._PanSpecStep = QtGui.QDoubleSpinBox(self._PanSpecW)
        self._PanSpecStep.setObjectName(_fromUtf8("_PanSpecStep"))
        self.gridLayout_5.addWidget(self._PanSpecStep, 2, 2, 1, 1)
        self._PanSpecApply = QtGui.QPushButton(self._PanSpecW)
        self._PanSpecApply.setObjectName(_fromUtf8("_PanSpecApply"))
        self.gridLayout_5.addWidget(self._PanSpecApply, 6, 2, 1, 3)
        self.label_2 = QtGui.QLabel(self._PanSpecW)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 1, 3, 1, 1)
        self.label_17 = QtGui.QLabel(self._PanSpecW)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_5.addWidget(self.label_17, 3, 4, 1, 1)
        self.label_24 = QtGui.QLabel(self._PanSpecW)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_5.addWidget(self.label_24, 4, 0, 1, 1)
        self._PanSpecClimMin = QtGui.QDoubleSpinBox(self._PanSpecW)
        self._PanSpecClimMin.setDecimals(1)
        self._PanSpecClimMin.setObjectName(_fromUtf8("_PanSpecClimMin"))
        self.gridLayout_5.addWidget(self._PanSpecClimMin, 4, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self._PanSpecW)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_5.addWidget(self.label_25, 4, 4, 1, 1)
        self._PanSpecClimMax = QtGui.QDoubleSpinBox(self._PanSpecW)
        self._PanSpecClimMax.setObjectName(_fromUtf8("_PanSpecClimMax"))
        self.gridLayout_5.addWidget(self._PanSpecClimMax, 4, 6, 1, 1)
        self.verticalLayout_20.addLayout(self.gridLayout_5)
        self.verticalLayout_12.addWidget(self._PanSpecW)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setMinimumSize(QtCore.QSize(200, 0))
        self.line_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_6.addWidget(self.line_2)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self._PanHypGrp = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self._PanHypGrp.setObjectName(_fromUtf8("_PanHypGrp"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self._PanHypGrp)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self._PanHypViz = QtGui.QCheckBox(self._PanHypGrp)
        self._PanHypViz.setChecked(True)
        self._PanHypViz.setObjectName(_fromUtf8("_PanHypViz"))
        self.gridLayout_4.addWidget(self._PanHypViz, 0, 0, 1, 1)
        self._PanHypZoom = QtGui.QCheckBox(self._PanHypGrp)
        self._PanHypZoom.setObjectName(_fromUtf8("_PanHypZoom"))
        self.gridLayout_4.addWidget(self._PanHypZoom, 0, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_4)
        self.verticalLayout_2.addWidget(self._PanHypGrp)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.line_7 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setMinimumSize(QtCore.QSize(200, 0))
        self.line_7.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout_11.addWidget(self.line_7)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.groupBox_10 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self._PanTimeViz = QtGui.QCheckBox(self.groupBox_10)
        self._PanTimeViz.setChecked(True)
        self._PanTimeViz.setObjectName(_fromUtf8("_PanTimeViz"))
        self.verticalLayout_27.addWidget(self._PanTimeViz)
        self.verticalLayout_2.addWidget(self.groupBox_10)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.QuickSettings.addTab(self.q_Panels, _fromUtf8(""))
        self.q_Signal = QtGui.QWidget()
        self.q_Signal.setObjectName(_fromUtf8("q_Signal"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.q_Signal)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.scrollArea_2 = QtGui.QScrollArea(self.q_Signal)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 358, 801))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_5 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self._SigMean = QtGui.QCheckBox(self.groupBox_5)
        self._SigMean.setObjectName(_fromUtf8("_SigMean"))
        self.gridLayout_2.addWidget(self._SigMean, 0, 0, 1, 1)
        self._SigTrend = QtGui.QCheckBox(self.groupBox_5)
        self._SigTrend.setObjectName(_fromUtf8("_SigTrend"))
        self.gridLayout_2.addWidget(self._SigTrend, 1, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.line_5 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.line_5.setMinimumSize(QtCore.QSize(200, 0))
        self.line_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout_9.addWidget(self.line_5)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.groupBox_6 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self._SigFilt = QtGui.QCheckBox(self.groupBox_6)
        self._SigFilt.setObjectName(_fromUtf8("_SigFilt"))
        self.verticalLayout_8.addWidget(self._SigFilt)
        self._SigFiltW = QtGui.QWidget(self.groupBox_6)
        self._SigFiltW.setEnabled(False)
        self._SigFiltW.setObjectName(_fromUtf8("_SigFiltW"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self._SigFiltW)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSpacing(9)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_7 = QtGui.QLabel(self._SigFiltW)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self._SigFiltFrom = QtGui.QDoubleSpinBox(self._SigFiltW)
        self._SigFiltFrom.setDecimals(1)
        self._SigFiltFrom.setMinimum(0.1)
        self._SigFiltFrom.setMaximum(1000.0)
        self._SigFiltFrom.setProperty("value", 12.0)
        self._SigFiltFrom.setObjectName(_fromUtf8("_SigFiltFrom"))
        self.gridLayout_3.addWidget(self._SigFiltFrom, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self._SigFiltW)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 2, 1, 1)
        self._SigFiltTo = QtGui.QDoubleSpinBox(self._SigFiltW)
        self._SigFiltTo.setDecimals(1)
        self._SigFiltTo.setMinimum(0.1)
        self._SigFiltTo.setMaximum(1000.0)
        self._SigFiltTo.setProperty("value", 16.0)
        self._SigFiltTo.setObjectName(_fromUtf8("_SigFiltTo"))
        self.gridLayout_3.addWidget(self._SigFiltTo, 0, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self._SigFiltW)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 4, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 0, 5, 1, 1)
        self.label_10 = QtGui.QLabel(self._SigFiltW)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self._SigFiltMeth = QtGui.QComboBox(self._SigFiltW)
        self._SigFiltMeth.setObjectName(_fromUtf8("_SigFiltMeth"))
        self._SigFiltMeth.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self._SigFiltMeth, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self._SigFiltW)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 1, 2, 1, 1)
        self._SigFiltOrder = QtGui.QSpinBox(self._SigFiltW)
        self._SigFiltOrder.setMinimum(1)
        self._SigFiltOrder.setMaximum(20)
        self._SigFiltOrder.setProperty("value", 3)
        self._SigFiltOrder.setObjectName(_fromUtf8("_SigFiltOrder"))
        self.gridLayout_3.addWidget(self._SigFiltOrder, 1, 3, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_3)
        self.verticalLayout_8.addWidget(self._SigFiltW)
        self.verticalLayout_5.addWidget(self.groupBox_6)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem13)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.QuickSettings.addTab(self.q_Signal, _fromUtf8(""))
        self.q_Tools = QtGui.QWidget()
        self.q_Tools.setObjectName(_fromUtf8("q_Tools"))
        self.QuickSettings.addTab(self.q_Tools, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.QuickSettings)
        self.horizontalLayout_2.addWidget(self.q_widget)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self._chanGrid = QtGui.QGridLayout()
        self._chanGrid.setContentsMargins(-1, -1, -1, 6)
        self._chanGrid.setSpacing(6)
        self._chanGrid.setObjectName(_fromUtf8("_chanGrid"))
        self.verticalLayout_18.addLayout(self._chanGrid)
        self._TimeAxisW = QtGui.QWidget(self.centralwidget)
        self._TimeAxisW.setMinimumSize(QtCore.QSize(0, 0))
        self._TimeAxisW.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self._TimeAxisW.setObjectName(_fromUtf8("_TimeAxisW"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self._TimeAxisW)
        self.verticalLayout_21.setMargin(0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self._TimeLayout = QtGui.QVBoxLayout()
        self._TimeLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self._TimeLayout.setContentsMargins(9, -1, 9, -1)
        self._TimeLayout.setSpacing(0)
        self._TimeLayout.setObjectName(_fromUtf8("_TimeLayout"))
        self.verticalLayout_21.addLayout(self._TimeLayout)
        self.verticalLayout_18.addWidget(self._TimeAxisW)
        self._SpecW = QtGui.QWidget(self.centralwidget)
        self._SpecW.setMinimumSize(QtCore.QSize(0, 0))
        self._SpecW.setObjectName(_fromUtf8("_SpecW"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self._SpecW)
        self.verticalLayout_17.setMargin(0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self._SpecLayout = QtGui.QVBoxLayout()
        self._SpecLayout.setContentsMargins(9, -1, 9, -1)
        self._SpecLayout.setSpacing(0)
        self._SpecLayout.setObjectName(_fromUtf8("_SpecLayout"))
        self.verticalLayout_17.addLayout(self._SpecLayout)
        self.verticalLayout_18.addWidget(self._SpecW)
        self._HypW = QtGui.QWidget(self.centralwidget)
        self._HypW.setMinimumSize(QtCore.QSize(0, 0))
        self._HypW.setObjectName(_fromUtf8("_HypW"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self._HypW)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self._HypLayout = QtGui.QVBoxLayout()
        self._HypLayout.setContentsMargins(9, -1, 9, -1)
        self._HypLayout.setSpacing(0)
        self._HypLayout.setObjectName(_fromUtf8("_HypLayout"))
        self.verticalLayout_16.addLayout(self._HypLayout)
        self.verticalLayout_18.addWidget(self._HypW)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self._slFrame = QtGui.QFrame(self.centralwidget)
        self._slFrame.setMinimumSize(QtCore.QSize(0, 0))
        self._slFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self._slFrame.setFrameShadow(QtGui.QFrame.Raised)
        self._slFrame.setObjectName(_fromUtf8("_slFrame"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self._slFrame)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_7.setHorizontalSpacing(7)
        self.gridLayout_7.setVerticalSpacing(9)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_3 = QtGui.QLabel(self._slFrame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_7.addWidget(self.label_3, 1, 4, 1, 1)
        self._SigSlStep = QtGui.QSpinBox(self._slFrame)
        self._SigSlStep.setMinimum(1)
        self._SigSlStep.setMaximum(10000)
        self._SigSlStep.setObjectName(_fromUtf8("_SigSlStep"))
        self.gridLayout_7.addWidget(self._SigSlStep, 1, 10, 1, 1)
        self._SlWin = QtGui.QSpinBox(self._slFrame)
        self._SlWin.setObjectName(_fromUtf8("_SlWin"))
        self.gridLayout_7.addWidget(self._SlWin, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self._slFrame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_7.addWidget(self.label_6, 1, 11, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem15, 1, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self._slFrame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_7.addWidget(self.label_5, 1, 9, 1, 1)
        self.checkBox = QtGui.QCheckBox(self._slFrame)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_7.addWidget(self.checkBox, 1, 13, 1, 1)
        self.label_4 = QtGui.QLabel(self._slFrame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_7.addWidget(self.label_4, 1, 6, 1, 1)
        self._SigWin = QtGui.QDoubleSpinBox(self._slFrame)
        self._SigWin.setDecimals(1)
        self._SigWin.setMaximum(1000.0)
        self._SigWin.setProperty("value", 30.0)
        self._SigWin.setObjectName(_fromUtf8("_SigWin"))
        self.gridLayout_7.addWidget(self._SigWin, 1, 5, 1, 1)
        self.label_12 = QtGui.QLabel(self._slFrame)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_7.addWidget(self.label_12, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self._slFrame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 1, 0, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem16, 1, 7, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem17, 1, 12, 1, 1)
        self._SlVal = QtGui.QSlider(self._slFrame)
        self._SlVal.setOrientation(QtCore.Qt.Horizontal)
        self._SlVal.setTickPosition(QtGui.QSlider.NoTicks)
        self._SlVal.setTickInterval(10)
        self._SlVal.setObjectName(_fromUtf8("_SlVal"))
        self.gridLayout_7.addWidget(self._SlVal, 0, 0, 1, 14)
        self.verticalLayout_15.addLayout(self.gridLayout_7)
        self.horizontalLayout_3.addWidget(self._slFrame)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem18)
        self.verticalLayout_18.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_18)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1328, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFiles = QtGui.QMenu(self.menubar)
        self.menuFiles.setObjectName(_fromUtf8("menuFiles"))
        self.menuDisplay = QtGui.QMenu(self.menubar)
        self.menuDisplay.setObjectName(_fromUtf8("menuDisplay"))
        self.menuPanel = QtGui.QMenu(self.menuDisplay)
        self.menuPanel.setObjectName(_fromUtf8("menuPanel"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionCortical_repartition = QtGui.QAction(MainWindow)
        self.actionCortical_repartition.setObjectName(_fromUtf8("actionCortical_repartition"))
        self.actionCortical = QtGui.QAction(MainWindow)
        self.actionCortical.setObjectName(_fromUtf8("actionCortical"))
        self.actionSagittal = QtGui.QAction(MainWindow)
        self.actionSagittal.setObjectName(_fromUtf8("actionSagittal"))
        self.actionAxial = QtGui.QAction(MainWindow)
        self.actionAxial.setObjectName(_fromUtf8("actionAxial"))
        self.actionCamera = QtGui.QAction(MainWindow)
        self.actionCamera.setObjectName(_fromUtf8("actionCamera"))
        self.actionLeft = QtGui.QAction(MainWindow)
        self.actionLeft.setObjectName(_fromUtf8("actionLeft"))
        self.actionRight = QtGui.QAction(MainWindow)
        self.actionRight.setObjectName(_fromUtf8("actionRight"))
        self.actionQuick_settings = QtGui.QAction(MainWindow)
        self.actionQuick_settings.setCheckable(True)
        self.actionQuick_settings.setChecked(True)
        self.actionQuick_settings.setObjectName(_fromUtf8("actionQuick_settings"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionProjection = QtGui.QAction(MainWindow)
        self.actionProjection.setObjectName(_fromUtf8("actionProjection"))
        self.actionRepartition = QtGui.QAction(MainWindow)
        self.actionRepartition.setObjectName(_fromUtf8("actionRepartition"))
        self.actionShortcuts = QtGui.QAction(MainWindow)
        self.actionShortcuts.setCheckable(True)
        self.actionShortcuts.setObjectName(_fromUtf8("actionShortcuts"))
        self.actionUi_settings = QtGui.QAction(MainWindow)
        self.actionUi_settings.setCheckable(True)
        self.actionUi_settings.setChecked(False)
        self.actionUi_settings.setObjectName(_fromUtf8("actionUi_settings"))
        self.actionNdPlt = QtGui.QAction(MainWindow)
        self.actionNdPlt.setCheckable(True)
        self.actionNdPlt.setObjectName(_fromUtf8("actionNdPlt"))
        self.actionOnedPlt = QtGui.QAction(MainWindow)
        self.actionOnedPlt.setCheckable(True)
        self.actionOnedPlt.setObjectName(_fromUtf8("actionOnedPlt"))
        self.actionImage = QtGui.QAction(MainWindow)
        self.actionImage.setCheckable(True)
        self.actionImage.setObjectName(_fromUtf8("actionImage"))
        self.actionColormap = QtGui.QAction(MainWindow)
        self.actionColormap.setCheckable(True)
        self.actionColormap.setObjectName(_fromUtf8("actionColormap"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.menuDisplay.addAction(self.actionQuick_settings)
        self.menuDisplay.addAction(self.menuPanel.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.menuFiles.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.QuickSettings.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Sleep", None))
        self.QuickSettings.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.groupBox.setTitle(_translate("MainWindow", "Visible channels", None))
        self._PanChanSelectAll.setText(_translate("MainWindow", "Select all", None))
        self._PanChanDeselectAll.setText(_translate("MainWindow", "Deselect all", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Spectrogram", None))
        self._PanSpecViz.setText(_translate("MainWindow", "Visible", None))
        self._PanSpecZoom.setText(_translate("MainWindow", "Zooming", None))
        self.label_15.setText(_translate("MainWindow", "Overlap", None))
        self.label_13.setText(_translate("MainWindow", "Channel", None))
        self.label_16.setText(_translate("MainWindow", "f start", None))
        self.label_14.setText(_translate("MainWindow", "Length", None))
        self.label_29.setText(_translate("MainWindow", "Colormap", None))
        self.label_23.setText(_translate("MainWindow", "seconds", None))
        self._PanSpecApply.setText(_translate("MainWindow", "Apply", None))
        self.label_2.setText(_translate("MainWindow", "seconds", None))
        self.label_17.setText(_translate("MainWindow", "f end", None))
        self.label_24.setText(_translate("MainWindow", "Clim min", None))
        self.label_25.setText(_translate("MainWindow", "Clim max", None))
        self._PanHypGrp.setTitle(_translate("MainWindow", "Hypnogram", None))
        self._PanHypViz.setText(_translate("MainWindow", "Visible", None))
        self._PanHypZoom.setText(_translate("MainWindow", "Zooming", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Time axis", None))
        self._PanTimeViz.setText(_translate("MainWindow", "Visible", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_Panels), _translate("MainWindow", "Panels", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Mean and trend", None))
        self._SigMean.setText(_translate("MainWindow", "Remove the mean", None))
        self._SigTrend.setText(_translate("MainWindow", "Remove the linear trend", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Filtering", None))
        self._SigFilt.setText(_translate("MainWindow", "Enable", None))
        self.label_7.setText(_translate("MainWindow", "From", None))
        self.label_8.setText(_translate("MainWindow", "to", None))
        self.label_9.setText(_translate("MainWindow", "hz", None))
        self.label_10.setText(_translate("MainWindow", "Filter", None))
        self._SigFiltMeth.setItemText(0, _translate("MainWindow", "butterworth", None))
        self.label_11.setText(_translate("MainWindow", "order", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_Signal), _translate("MainWindow", "Signal", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_Tools), _translate("MainWindow", "Tools", None))
        self.label_3.setText(_translate("MainWindow", "Window", None))
        self.label_6.setText(_translate("MainWindow", " seconds", None))
        self.label_5.setText(_translate("MainWindow", "Slider step", None))
        self.checkBox.setText(_translate("MainWindow", "Grid", None))
        self.label_4.setText(_translate("MainWindow", " seconds", None))
        self.label_12.setText(_translate("MainWindow", " / nb_win", None))
        self.label.setText(_translate("MainWindow", "Go to", None))
        self.menuFiles.setTitle(_translate("MainWindow", "Files", None))
        self.menuDisplay.setTitle(_translate("MainWindow", "Display", None))
        self.menuPanel.setTitle(_translate("MainWindow", "Panel", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))
        self.actionCortical_repartition.setText(_translate("MainWindow", "Cortical repartition", None))
        self.actionCortical.setText(_translate("MainWindow", "Cortical", None))
        self.actionSagittal.setText(_translate("MainWindow", "Sagittal", None))
        self.actionAxial.setText(_translate("MainWindow", "Axial", None))
        self.actionCamera.setText(_translate("MainWindow", "Camera", None))
        self.actionLeft.setText(_translate("MainWindow", "Left", None))
        self.actionRight.setText(_translate("MainWindow", "Right", None))
        self.actionQuick_settings.setText(_translate("MainWindow", "Quick settings", None))
        self.actionQuick_settings.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionProjection.setText(_translate("MainWindow", "Projection", None))
        self.actionProjection.setToolTip(_translate("MainWindow", "<html><head/><body><p>Find all vertices under a distance of t_radius with each source and project s_data to the surface</p></body></html>", None))
        self.actionProjection.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.actionRepartition.setText(_translate("MainWindow", "Repartition", None))
        self.actionRepartition.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.actionShortcuts.setText(_translate("MainWindow", "Shortcuts", None))
        self.actionShortcuts.setShortcut(_translate("MainWindow", "Ctrl+T", None))
        self.actionUi_settings.setText(_translate("MainWindow", "Ui settings", None))
        self.actionNdPlt.setText(_translate("MainWindow", "Nd-plot", None))
        self.actionOnedPlt.setText(_translate("MainWindow", "1d-plot", None))
        self.actionImage.setText(_translate("MainWindow", "Image", None))
        self.actionColormap.setText(_translate("MainWindow", "Colormap", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation", None))

