# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/etienne/Toolbox/visbrain/visbrain/sleep/interface/gui/sleep_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1328, 1017)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.q_widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q_widget.sizePolicy().hasHeightForWidth())
        self.q_widget.setSizePolicy(sizePolicy)
        self.q_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.q_widget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.q_widget.setObjectName(_fromUtf8("q_widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.q_widget)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.QuickSettings = QtGui.QTabWidget(self.q_widget)
        self.QuickSettings.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.QuickSettings.setAutoFillBackground(False)
        self.QuickSettings.setTabShape(QtGui.QTabWidget.Rounded)
        self.QuickSettings.setMovable(True)
        self.QuickSettings.setObjectName(_fromUtf8("QuickSettings"))
        self.q_Panels = QtGui.QWidget()
        self.q_Panels.setObjectName(_fromUtf8("q_Panels"))
        self.verticalLayout = QtGui.QVBoxLayout(self.q_Panels)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(self.q_Panels)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_10.setContentsMargins(-1, 3, -1, 3)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_41 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.verticalLayout_10.addWidget(self.label_41)
        self.verticalLayout.addWidget(self.frame)
        self.groupBox = QtGui.QGroupBox(self.q_Panels)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_13.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.line_13 = QtGui.QFrame(self.groupBox)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.verticalLayout_13.addWidget(self.line_13)
        self._PanScrollChan = QtGui.QScrollArea(self.groupBox)
        self._PanScrollChan.setMinimumSize(QtCore.QSize(0, 300))
        self._PanScrollChan.setFrameShape(QtGui.QFrame.Box)
        self._PanScrollChan.setFrameShadow(QtGui.QFrame.Sunken)
        self._PanScrollChan.setWidgetResizable(True)
        self._PanScrollChan.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self._PanScrollChan.setObjectName(_fromUtf8("_PanScrollChan"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 350, 299))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.widget = QtGui.QWidget(self.scrollAreaWidgetContents_3)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self._PanChanLay = QtGui.QGridLayout()
        self._PanChanLay.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self._PanChanLay.setHorizontalSpacing(6)
        self._PanChanLay.setVerticalSpacing(9)
        self._PanChanLay.setObjectName(_fromUtf8("_PanChanLay"))
        self.verticalLayout_5.addLayout(self._PanChanLay)
        self.verticalLayout_14.addWidget(self.widget)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem)
        self._PanScrollChan.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_13.addWidget(self._PanScrollChan)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self._PanChanSelectAll = QtGui.QPushButton(self.groupBox)
        self._PanChanSelectAll.setObjectName(_fromUtf8("_PanChanSelectAll"))
        self.horizontalLayout.addWidget(self._PanChanSelectAll)
        self._PanChanDeselectAll = QtGui.QPushButton(self.groupBox)
        self._PanChanDeselectAll.setObjectName(_fromUtf8("_PanChanDeselectAll"))
        self.horizontalLayout.addWidget(self._PanChanDeselectAll)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_35 = QtGui.QLabel(self.groupBox)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_7.addWidget(self.label_35)
        spacerItem3 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self._PanAllAmpMin = QtGui.QDoubleSpinBox(self.groupBox)
        self._PanAllAmpMin.setObjectName(_fromUtf8("_PanAllAmpMin"))
        self.horizontalLayout_7.addWidget(self._PanAllAmpMin)
        self._PanAllAmpMax = QtGui.QDoubleSpinBox(self.groupBox)
        self._PanAllAmpMax.setObjectName(_fromUtf8("_PanAllAmpMax"))
        self.horizontalLayout_7.addWidget(self._PanAllAmpMax)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.q_Panels)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_12.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.line_14 = QtGui.QFrame(self.groupBox_2)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.verticalLayout_12.addWidget(self.line_14)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self._PanSpecViz = QtGui.QCheckBox(self.groupBox_2)
        self._PanSpecViz.setChecked(True)
        self._PanSpecViz.setObjectName(_fromUtf8("_PanSpecViz"))
        self.gridLayout_6.addWidget(self._PanSpecViz, 0, 0, 1, 1)
        self._PanSpecIndic = QtGui.QCheckBox(self.groupBox_2)
        self._PanSpecIndic.setChecked(True)
        self._PanSpecIndic.setObjectName(_fromUtf8("_PanSpecIndic"))
        self.gridLayout_6.addWidget(self._PanSpecIndic, 0, 1, 1, 1)
        self._PanSpecZoom = QtGui.QCheckBox(self.groupBox_2)
        self._PanSpecZoom.setObjectName(_fromUtf8("_PanSpecZoom"))
        self.gridLayout_6.addWidget(self._PanSpecZoom, 0, 2, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_6)
        self._PanSpecW = QtGui.QWidget(self.groupBox_2)
        self._PanSpecW.setObjectName(_fromUtf8("_PanSpecW"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self._PanSpecW)
        self.verticalLayout_20.setMargin(0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSpacing(9)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_17 = QtGui.QLabel(self._PanSpecW)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_5.addWidget(self.label_17, 3, 4, 1, 1)
        self.label_15 = QtGui.QLabel(self._PanSpecW)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 2, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self._PanSpecW)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 3, 2, 1, 1)
        self._PanSpecCon = QtGui.QDoubleSpinBox(self._PanSpecW)
        self._PanSpecCon.setDecimals(1)
        self._PanSpecCon.setMinimum(0.0)
        self._PanSpecCon.setMaximum(1.0)
        self._PanSpecCon.setSingleStep(0.1)
        self._PanSpecCon.setProperty("value", 0.5)
        self._PanSpecCon.setObjectName(_fromUtf8("_PanSpecCon"))
        self.gridLayout_5.addWidget(self._PanSpecCon, 4, 5, 1, 1)
        self.label_24 = QtGui.QLabel(self._PanSpecW)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_5.addWidget(self.label_24, 4, 4, 1, 1)
        self.label_13 = QtGui.QLabel(self._PanSpecW)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 0, 2, 1, 1)
        self._PanSpecStep = QtGui.QDoubleSpinBox(self._PanSpecW)
        self._PanSpecStep.setDecimals(1)
        self._PanSpecStep.setProperty("value", 0.5)
        self._PanSpecStep.setObjectName(_fromUtf8("_PanSpecStep"))
        self.gridLayout_5.addWidget(self._PanSpecStep, 2, 3, 1, 1)
        self._PanSpecNfft = QtGui.QDoubleSpinBox(self._PanSpecW)
        self._PanSpecNfft.setDecimals(1)
        self._PanSpecNfft.setMinimum(0.1)
        self._PanSpecNfft.setMaximum(1000.0)
        self._PanSpecNfft.setProperty("value", 30.0)
        self._PanSpecNfft.setObjectName(_fromUtf8("_PanSpecNfft"))
        self.gridLayout_5.addWidget(self._PanSpecNfft, 1, 3, 1, 1)
        self._PanSpecFstart = QtGui.QDoubleSpinBox(self._PanSpecW)
        self._PanSpecFstart.setDecimals(1)
        self._PanSpecFstart.setMinimum(0.5)
        self._PanSpecFstart.setMaximum(190.0)
        self._PanSpecFstart.setObjectName(_fromUtf8("_PanSpecFstart"))
        self.gridLayout_5.addWidget(self._PanSpecFstart, 3, 3, 1, 1)
        self._PanSpecFend = QtGui.QDoubleSpinBox(self._PanSpecW)
        self._PanSpecFend.setDecimals(1)
        self._PanSpecFend.setMinimum(0.1)
        self._PanSpecFend.setMaximum(200.0)
        self._PanSpecFend.setProperty("value", 20.0)
        self._PanSpecFend.setObjectName(_fromUtf8("_PanSpecFend"))
        self.gridLayout_5.addWidget(self._PanSpecFend, 3, 5, 1, 1)
        self.label_14 = QtGui.QLabel(self._PanSpecW)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self._PanSpecW)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 1, 4, 1, 2)
        self._PanSpecCmap = QtGui.QComboBox(self._PanSpecW)
        self._PanSpecCmap.setObjectName(_fromUtf8("_PanSpecCmap"))
        self.gridLayout_5.addWidget(self._PanSpecCmap, 4, 2, 1, 2)
        self.line_17 = QtGui.QFrame(self._PanSpecW)
        self.line_17.setMinimumSize(QtCore.QSize(10, 0))
        self.line_17.setFrameShape(QtGui.QFrame.VLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.gridLayout_5.addWidget(self.line_17, 1, 1, 3, 1)
        self.label_55 = QtGui.QLabel(self._PanSpecW)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_5.addWidget(self.label_55, 1, 0, 3, 1)
        self.label_54 = QtGui.QLabel(self._PanSpecW)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_5.addWidget(self.label_54, 0, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self._PanSpecW)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_5.addWidget(self.label_23, 2, 4, 1, 2)
        self.line_18 = QtGui.QFrame(self._PanSpecW)
        self.line_18.setMinimumSize(QtCore.QSize(10, 0))
        self.line_18.setFrameShape(QtGui.QFrame.VLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.gridLayout_5.addWidget(self.line_18, 4, 1, 1, 1)
        self.line_8 = QtGui.QFrame(self._PanSpecW)
        self.line_8.setMinimumSize(QtCore.QSize(10, 0))
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_5.addWidget(self.line_8, 0, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self._PanSpecW)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_5.addWidget(self.label_29, 4, 0, 1, 1)
        self.widget_2 = QtGui.QWidget(self._PanSpecW)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setContentsMargins(0, 3, 0, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self._PanSpecApply = QtGui.QPushButton(self.widget_2)
        self._PanSpecApply.setObjectName(_fromUtf8("_PanSpecApply"))
        self.horizontalLayout_5.addWidget(self._PanSpecApply)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.gridLayout_5.addWidget(self.widget_2, 5, 0, 1, 6)
        self._PanSpecChan = QtGui.QComboBox(self._PanSpecW)
        self._PanSpecChan.setObjectName(_fromUtf8("_PanSpecChan"))
        self.gridLayout_5.addWidget(self._PanSpecChan, 0, 3, 1, 3)
        self.verticalLayout_20.addLayout(self.gridLayout_5)
        self.verticalLayout_12.addWidget(self._PanSpecW)
        self.verticalLayout.addWidget(self.groupBox_2)
        self._PanHypGrp = QtGui.QGroupBox(self.q_Panels)
        self._PanHypGrp.setObjectName(_fromUtf8("_PanHypGrp"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self._PanHypGrp)
        self.verticalLayout_11.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.line_15 = QtGui.QFrame(self._PanHypGrp)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.verticalLayout_11.addWidget(self.line_15)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self._PanHypViz = QtGui.QCheckBox(self._PanHypGrp)
        self._PanHypViz.setChecked(True)
        self._PanHypViz.setObjectName(_fromUtf8("_PanHypViz"))
        self.gridLayout_4.addWidget(self._PanHypViz, 1, 0, 1, 1)
        self._PanHypIndic = QtGui.QCheckBox(self._PanHypGrp)
        self._PanHypIndic.setChecked(True)
        self._PanHypIndic.setObjectName(_fromUtf8("_PanHypIndic"))
        self.gridLayout_4.addWidget(self._PanHypIndic, 1, 1, 1, 1)
        self._PanHypZoom = QtGui.QCheckBox(self._PanHypGrp)
        self._PanHypZoom.setObjectName(_fromUtf8("_PanHypZoom"))
        self.gridLayout_4.addWidget(self._PanHypZoom, 1, 2, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self._PanHypGrp)
        self.groupBox_10 = QtGui.QGroupBox(self.q_Panels)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_27.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.line_16 = QtGui.QFrame(self.groupBox_10)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.verticalLayout_27.addWidget(self.line_16)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self._PanTimeIndic = QtGui.QCheckBox(self.groupBox_10)
        self._PanTimeIndic.setChecked(True)
        self._PanTimeIndic.setObjectName(_fromUtf8("_PanTimeIndic"))
        self.gridLayout_12.addWidget(self._PanTimeIndic, 0, 1, 1, 1)
        self._PanTimeViz = QtGui.QCheckBox(self.groupBox_10)
        self._PanTimeViz.setChecked(True)
        self._PanTimeViz.setObjectName(_fromUtf8("_PanTimeViz"))
        self.gridLayout_12.addWidget(self._PanTimeViz, 0, 0, 1, 1)
        self._PanTimeZoom = QtGui.QCheckBox(self.groupBox_10)
        self._PanTimeZoom.setObjectName(_fromUtf8("_PanTimeZoom"))
        self.gridLayout_12.addWidget(self._PanTimeZoom, 0, 2, 1, 1)
        self.verticalLayout_27.addLayout(self.gridLayout_12)
        self.verticalLayout.addWidget(self.groupBox_10)
        self.QuickSettings.addTab(self.q_Panels, _fromUtf8(""))
        self.q_Tools = QtGui.QWidget()
        self.q_Tools.setObjectName(_fromUtf8("q_Tools"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.q_Tools)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.frame_2 = QtGui.QFrame(self.q_Tools)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_19.setContentsMargins(-1, 3, -1, 3)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_42 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.verticalLayout_19.addWidget(self.label_42)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.groupBox_5 = QtGui.QGroupBox(self.q_Tools)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.line_12 = QtGui.QFrame(self.groupBox_5)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.verticalLayout_7.addWidget(self.line_12)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self._SigMean = QtGui.QCheckBox(self.groupBox_5)
        self._SigMean.setObjectName(_fromUtf8("_SigMean"))
        self.gridLayout_2.addWidget(self._SigMean, 0, 0, 1, 1)
        self._SigTrend = QtGui.QCheckBox(self.groupBox_5)
        self._SigTrend.setObjectName(_fromUtf8("_SigTrend"))
        self.gridLayout_2.addWidget(self._SigTrend, 1, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.q_Tools)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.line_11 = QtGui.QFrame(self.groupBox_6)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.verticalLayout_8.addWidget(self.line_11)
        self._SigFilt = QtGui.QCheckBox(self.groupBox_6)
        self._SigFilt.setObjectName(_fromUtf8("_SigFilt"))
        self.verticalLayout_8.addWidget(self._SigFilt)
        self._SigFiltW = QtGui.QWidget(self.groupBox_6)
        self._SigFiltW.setEnabled(False)
        self._SigFiltW.setObjectName(_fromUtf8("_SigFiltW"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self._SigFiltW)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSpacing(9)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_10 = QtGui.QLabel(self._SigFiltW)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self._SigFiltW)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 4, 1, 1)
        self._SigFiltFrom = QtGui.QDoubleSpinBox(self._SigFiltW)
        self._SigFiltFrom.setDecimals(1)
        self._SigFiltFrom.setMinimum(0.1)
        self._SigFiltFrom.setMaximum(200.0)
        self._SigFiltFrom.setProperty("value", 12.0)
        self._SigFiltFrom.setObjectName(_fromUtf8("_SigFiltFrom"))
        self.gridLayout_3.addWidget(self._SigFiltFrom, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self._SigFiltW)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 3, 0, 1, 5)
        self.label_11 = QtGui.QLabel(self._SigFiltW)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 2, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self._SigFiltW)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 1, 2, 1, 1)
        self._SigFiltMeth = QtGui.QComboBox(self._SigFiltW)
        self._SigFiltMeth.setObjectName(_fromUtf8("_SigFiltMeth"))
        self._SigFiltMeth.addItem(_fromUtf8(""))
        self._SigFiltMeth.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self._SigFiltMeth, 2, 1, 1, 1)
        self._SigFiltBand = QtGui.QComboBox(self._SigFiltW)
        self._SigFiltBand.setObjectName(_fromUtf8("_SigFiltBand"))
        self._SigFiltBand.addItem(_fromUtf8(""))
        self._SigFiltBand.addItem(_fromUtf8(""))
        self._SigFiltBand.addItem(_fromUtf8(""))
        self._SigFiltBand.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self._SigFiltBand, 0, 1, 1, 1)
        self._SigFiltOrder = QtGui.QSpinBox(self._SigFiltW)
        self._SigFiltOrder.setMinimum(1)
        self._SigFiltOrder.setMaximum(20)
        self._SigFiltOrder.setProperty("value", 3)
        self._SigFiltOrder.setObjectName(_fromUtf8("_SigFiltOrder"))
        self.gridLayout_3.addWidget(self._SigFiltOrder, 2, 3, 1, 2)
        self._SigFiltTo = QtGui.QDoubleSpinBox(self._SigFiltW)
        self._SigFiltTo.setDecimals(1)
        self._SigFiltTo.setMinimum(0.1)
        self._SigFiltTo.setMaximum(200.0)
        self._SigFiltTo.setProperty("value", 16.0)
        self._SigFiltTo.setObjectName(_fromUtf8("_SigFiltTo"))
        self.gridLayout_3.addWidget(self._SigFiltTo, 1, 3, 1, 1)
        self.label_18 = QtGui.QLabel(self._SigFiltW)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 0, 0, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self._SigFiltApply = QtGui.QPushButton(self._SigFiltW)
        self._SigFiltApply.setObjectName(_fromUtf8("_SigFiltApply"))
        self.horizontalLayout_4.addWidget(self._SigFiltApply)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8.addWidget(self._SigFiltW)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem10)
        self.QuickSettings.addTab(self.q_Tools, _fromUtf8(""))
        self.q_Info = QtGui.QWidget()
        self.q_Info.setObjectName(_fromUtf8("q_Info"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.q_Info)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_4 = QtGui.QFrame(self.q_Info)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_23.setContentsMargins(-1, 3, -1, 3)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.label_44 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.verticalLayout_23.addWidget(self.label_44)
        self.verticalLayout_3.addWidget(self.frame_4)
        self._infoTable = QtGui.QTableWidget(self.q_Info)
        self._infoTable.setObjectName(_fromUtf8("_infoTable"))
        self._infoTable.setColumnCount(2)
        self._infoTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self._infoTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self._infoTable.setHorizontalHeaderItem(1, item)
        self._infoTable.horizontalHeader().setStretchLastSection(True)
        self._infoTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self._infoTable)
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_32 = QtGui.QLabel(self.q_Info)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_14.addWidget(self.label_32, 0, 1, 1, 1)
        self._infoExport = QtGui.QPushButton(self.q_Info)
        self._infoExport.setObjectName(_fromUtf8("_infoExport"))
        self.gridLayout_14.addWidget(self._infoExport, 1, 3, 1, 1)
        self._infoTime = QtGui.QDoubleSpinBox(self.q_Info)
        self._infoTime.setDecimals(1)
        self._infoTime.setMaximum(100000.0)
        self._infoTime.setProperty("value", 30.0)
        self._infoTime.setObjectName(_fromUtf8("_infoTime"))
        self.gridLayout_14.addWidget(self._infoTime, 0, 2, 1, 1)
        self.label_33 = QtGui.QLabel(self.q_Info)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_14.addWidget(self.label_33, 0, 3, 1, 1)
        self._infoExportAs = QtGui.QComboBox(self.q_Info)
        self._infoExportAs.setObjectName(_fromUtf8("_infoExportAs"))
        self._infoExportAs.addItem(_fromUtf8(""))
        self._infoExportAs.addItem(_fromUtf8(""))
        self.gridLayout_14.addWidget(self._infoExportAs, 1, 2, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem11, 0, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.q_Info)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_14.addWidget(self.label_34, 1, 1, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem12, 0, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_14)
        self.QuickSettings.addTab(self.q_Info, _fromUtf8(""))
        self.q_Score = QtGui.QWidget()
        self.q_Score.setObjectName(_fromUtf8("q_Score"))
        self.verticalLayout_29 = QtGui.QVBoxLayout(self.q_Score)
        self.verticalLayout_29.setObjectName(_fromUtf8("verticalLayout_29"))
        self.frame_3 = QtGui.QFrame(self.q_Score)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_24.setContentsMargins(-1, 3, -1, 3)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.label_43 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.verticalLayout_24.addWidget(self.label_43)
        self.verticalLayout_29.addWidget(self.frame_3)
        self._scoreTable = QtGui.QTableWidget(self.q_Score)
        self._scoreTable.setObjectName(_fromUtf8("_scoreTable"))
        self._scoreTable.setColumnCount(3)
        self._scoreTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self._scoreTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self._scoreTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self._scoreTable.setHorizontalHeaderItem(2, item)
        self._scoreTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_29.addWidget(self._scoreTable)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem13)
        self._scoreAdd = QtGui.QPushButton(self.q_Score)
        self._scoreAdd.setObjectName(_fromUtf8("_scoreAdd"))
        self.horizontalLayout_13.addWidget(self._scoreAdd)
        spacerItem14 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem14)
        self._scoreRm = QtGui.QPushButton(self.q_Score)
        self._scoreRm.setObjectName(_fromUtf8("_scoreRm"))
        self.horizontalLayout_13.addWidget(self._scoreRm)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem15)
        self.verticalLayout_29.addLayout(self.horizontalLayout_13)
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self._scoreExportAs = QtGui.QComboBox(self.q_Score)
        self._scoreExportAs.setObjectName(_fromUtf8("_scoreExportAs"))
        self._scoreExportAs.addItem(_fromUtf8(""))
        self._scoreExportAs.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self._scoreExportAs, 0, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.q_Score)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_15.addWidget(self.label_36, 0, 0, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem16, 0, 3, 1, 1)
        self._scoreExport = QtGui.QPushButton(self.q_Score)
        self._scoreExport.setObjectName(_fromUtf8("_scoreExport"))
        self.gridLayout_15.addWidget(self._scoreExport, 0, 2, 1, 1)
        self.verticalLayout_29.addLayout(self.gridLayout_15)
        self.QuickSettings.addTab(self.q_Score, _fromUtf8(""))
        self.q_Detection = QtGui.QWidget()
        self.q_Detection.setObjectName(_fromUtf8("q_Detection"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.q_Detection)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.frame_5 = QtGui.QFrame(self.q_Detection)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayout_37 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_37.setContentsMargins(0, 3, 0, 0)
        self.verticalLayout_37.setSpacing(3)
        self.verticalLayout_37.setObjectName(_fromUtf8("verticalLayout_37"))
        self.label_45 = QtGui.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.verticalLayout_37.addWidget(self.label_45)
        self.verticalLayout_22.addWidget(self.frame_5)
        self._DetectionTab = QtGui.QTabWidget(self.q_Detection)
        self._DetectionTab.setObjectName(_fromUtf8("_DetectionTab"))
        self.q_DetectSettings = QtGui.QWidget()
        self.q_DetectSettings.setObjectName(_fromUtf8("q_DetectSettings"))
        self.verticalLayout_38 = QtGui.QVBoxLayout(self.q_DetectSettings)
        self.verticalLayout_38.setObjectName(_fromUtf8("verticalLayout_38"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem17)
        self._ToolDetecVisible = QtGui.QCheckBox(self.q_DetectSettings)
        self._ToolDetecVisible.setChecked(True)
        self._ToolDetecVisible.setObjectName(_fromUtf8("_ToolDetecVisible"))
        self.horizontalLayout_10.addWidget(self._ToolDetecVisible)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem18)
        self.verticalLayout_38.addLayout(self.horizontalLayout_10)
        self.groupBox_3 = QtGui.QGroupBox(self.q_DetectSettings)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_33 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_33.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_33.setObjectName(_fromUtf8("verticalLayout_33"))
        self.line_3 = QtGui.QFrame(self.groupBox_3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_33.addWidget(self.line_3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_39 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout.addWidget(self.label_39, 0, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 2, 3, 1, 1)
        self._ToolDetecReport = QtGui.QCheckBox(self.groupBox_3)
        self._ToolDetecReport.setChecked(True)
        self._ToolDetecReport.setObjectName(_fromUtf8("_ToolDetecReport"))
        self.gridLayout.addWidget(self._ToolDetecReport, 3, 3, 1, 3)
        self._ToolDetectType = QtGui.QComboBox(self.groupBox_3)
        self._ToolDetectType.setObjectName(_fromUtf8("_ToolDetectType"))
        self._ToolDetectType.addItem(_fromUtf8(""))
        self._ToolDetectType.addItem(_fromUtf8(""))
        self._ToolDetectType.addItem(_fromUtf8(""))
        self._ToolDetectType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self._ToolDetectType, 0, 3, 1, 3)
        self.line_9 = QtGui.QFrame(self.groupBox_3)
        self.line_9.setMinimumSize(QtCore.QSize(10, 0))
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout.addWidget(self.line_9, 1, 2, 3, 1)
        self._ToolRdViz = QtGui.QRadioButton(self.groupBox_3)
        self._ToolRdViz.setObjectName(_fromUtf8("_ToolRdViz"))
        self.gridLayout.addWidget(self._ToolRdViz, 1, 4, 1, 1)
        self.line_10 = QtGui.QFrame(self.groupBox_3)
        self.line_10.setMinimumSize(QtCore.QSize(10, 0))
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.gridLayout.addWidget(self.line_10, 0, 2, 1, 1)
        self.label_49 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout.addWidget(self.label_49, 1, 1, 3, 1)
        self._ToolRdSelected = QtGui.QRadioButton(self.groupBox_3)
        self._ToolRdSelected.setChecked(True)
        self._ToolRdSelected.setObjectName(_fromUtf8("_ToolRdSelected"))
        self.gridLayout.addWidget(self._ToolRdSelected, 1, 3, 1, 1)
        self._ToolRdAll = QtGui.QRadioButton(self.groupBox_3)
        self._ToolRdAll.setObjectName(_fromUtf8("_ToolRdAll"))
        self.gridLayout.addWidget(self._ToolRdAll, 1, 5, 1, 1)
        self._ToolDetectChan = QtGui.QComboBox(self.groupBox_3)
        self._ToolDetectChan.setObjectName(_fromUtf8("_ToolDetectChan"))
        self.gridLayout.addWidget(self._ToolDetectChan, 2, 4, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem19, 2, 5, 1, 1)
        self.verticalLayout_33.addLayout(self.gridLayout)
        self.verticalLayout_38.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.q_DetectSettings)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_26.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.line_4 = QtGui.QFrame(self.groupBox_4)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_26.addWidget(self.line_4)
        self._ToolPeakPanel = QtGui.QWidget(self.groupBox_4)
        self._ToolPeakPanel.setMinimumSize(QtCore.QSize(0, 0))
        self._ToolPeakPanel.setObjectName(_fromUtf8("_ToolPeakPanel"))
        self.verticalLayout_34 = QtGui.QVBoxLayout(self._ToolPeakPanel)
        self.verticalLayout_34.setMargin(0)
        self.verticalLayout_34.setObjectName(_fromUtf8("verticalLayout_34"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_26 = QtGui.QLabel(self._ToolPeakPanel)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_11.addWidget(self.label_26, 0, 2, 1, 1)
        self._ToolPeakLook = QtGui.QDoubleSpinBox(self._ToolPeakPanel)
        self._ToolPeakLook.setDecimals(1)
        self._ToolPeakLook.setProperty("value", 0.5)
        self._ToolPeakLook.setObjectName(_fromUtf8("_ToolPeakLook"))
        self.gridLayout_11.addWidget(self._ToolPeakLook, 0, 3, 1, 1)
        self.label_28 = QtGui.QLabel(self._ToolPeakPanel)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_11.addWidget(self.label_28, 1, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self._ToolPeakPanel)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_11.addWidget(self.label_27, 0, 4, 1, 1)
        self._ToolPeakMinMax = QtGui.QComboBox(self._ToolPeakPanel)
        self._ToolPeakMinMax.setObjectName(_fromUtf8("_ToolPeakMinMax"))
        self._ToolPeakMinMax.addItem(_fromUtf8(""))
        self._ToolPeakMinMax.addItem(_fromUtf8(""))
        self._ToolPeakMinMax.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self._ToolPeakMinMax, 1, 3, 1, 2)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem20, 0, 5, 1, 1)
        self.label_50 = QtGui.QLabel(self._ToolPeakPanel)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_50.setFont(font)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_11.addWidget(self.label_50, 0, 0, 2, 1)
        self.line = QtGui.QFrame(self._ToolPeakPanel)
        self.line.setMinimumSize(QtCore.QSize(10, 0))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_11.addWidget(self.line, 0, 1, 2, 1)
        self.verticalLayout_34.addLayout(self.gridLayout_11)
        self.verticalLayout_26.addWidget(self._ToolPeakPanel)
        self._ToolRemPanel = QtGui.QWidget(self.groupBox_4)
        self._ToolRemPanel.setMinimumSize(QtCore.QSize(0, 0))
        self._ToolRemPanel.setObjectName(_fromUtf8("_ToolRemPanel"))
        self.verticalLayout_35 = QtGui.QVBoxLayout(self._ToolRemPanel)
        self.verticalLayout_35.setMargin(0)
        self.verticalLayout_35.setObjectName(_fromUtf8("verticalLayout_35"))
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self._ToolRemTh = QtGui.QDoubleSpinBox(self._ToolRemPanel)
        self._ToolRemTh.setProperty("value", 2.0)
        self._ToolRemTh.setObjectName(_fromUtf8("_ToolRemTh"))
        self.gridLayout_17.addWidget(self._ToolRemTh, 0, 3, 1, 1)
        self.label_38 = QtGui.QLabel(self._ToolRemPanel)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_17.addWidget(self.label_38, 0, 2, 1, 1)
        self._ToolRemOnly = QtGui.QCheckBox(self._ToolRemPanel)
        self._ToolRemOnly.setObjectName(_fromUtf8("_ToolRemOnly"))
        self.gridLayout_17.addWidget(self._ToolRemOnly, 1, 2, 1, 4)
        self.line_2 = QtGui.QFrame(self._ToolRemPanel)
        self.line_2.setMinimumSize(QtCore.QSize(10, 0))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_17.addWidget(self.line_2, 0, 1, 2, 1)
        self.label_51 = QtGui.QLabel(self._ToolRemPanel)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_17.addWidget(self.label_51, 0, 0, 2, 1)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem21, 0, 4, 1, 1)
        self.verticalLayout_35.addLayout(self.gridLayout_17)
        self.verticalLayout_26.addWidget(self._ToolRemPanel)
        self._ToolSpinPanel = QtGui.QWidget(self.groupBox_4)
        self._ToolSpinPanel.setObjectName(_fromUtf8("_ToolSpinPanel"))
        self.verticalLayout_36 = QtGui.QVBoxLayout(self._ToolSpinPanel)
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_36.setObjectName(_fromUtf8("verticalLayout_36"))
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.label_40 = QtGui.QLabel(self._ToolSpinPanel)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_18.addWidget(self.label_40, 2, 2, 1, 1)
        self._ToolSpinTmin = QtGui.QDoubleSpinBox(self._ToolSpinPanel)
        self._ToolSpinTmin.setDecimals(1)
        self._ToolSpinTmin.setMaximum(10000.0)
        self._ToolSpinTmin.setProperty("value", 500.0)
        self._ToolSpinTmin.setObjectName(_fromUtf8("_ToolSpinTmin"))
        self.gridLayout_18.addWidget(self._ToolSpinTmin, 1, 3, 1, 1)
        self.label_37 = QtGui.QLabel(self._ToolSpinPanel)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_18.addWidget(self.label_37, 1, 6, 1, 1)
        self._ToolSpinRemOnly = QtGui.QCheckBox(self._ToolSpinPanel)
        self._ToolSpinRemOnly.setObjectName(_fromUtf8("_ToolSpinRemOnly"))
        self.gridLayout_18.addWidget(self._ToolSpinRemOnly, 3, 2, 1, 5)
        self._ToolSpinFmin = QtGui.QDoubleSpinBox(self._ToolSpinPanel)
        self._ToolSpinFmin.setDecimals(1)
        self._ToolSpinFmin.setMaximum(200.0)
        self._ToolSpinFmin.setProperty("value", 12.0)
        self._ToolSpinFmin.setObjectName(_fromUtf8("_ToolSpinFmin"))
        self.gridLayout_18.addWidget(self._ToolSpinFmin, 0, 3, 1, 1)
        self.line_5 = QtGui.QFrame(self._ToolSpinPanel)
        self.line_5.setMinimumSize(QtCore.QSize(10, 0))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_18.addWidget(self.line_5, 0, 1, 4, 1)
        self.label_30 = QtGui.QLabel(self._ToolSpinPanel)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_18.addWidget(self.label_30, 1, 4, 1, 1)
        self.label_22 = QtGui.QLabel(self._ToolSpinPanel)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_18.addWidget(self.label_22, 1, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self._ToolSpinPanel)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_18.addWidget(self.label_19, 0, 2, 1, 1)
        self._ToolSpinFmax = QtGui.QDoubleSpinBox(self._ToolSpinPanel)
        self._ToolSpinFmax.setDecimals(1)
        self._ToolSpinFmax.setMaximum(200.0)
        self._ToolSpinFmax.setProperty("value", 14.0)
        self._ToolSpinFmax.setObjectName(_fromUtf8("_ToolSpinFmax"))
        self.gridLayout_18.addWidget(self._ToolSpinFmax, 0, 5, 1, 1)
        self.label_21 = QtGui.QLabel(self._ToolSpinPanel)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_18.addWidget(self.label_21, 0, 6, 1, 1)
        self.label_52 = QtGui.QLabel(self._ToolSpinPanel)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_52.setFont(font)
        self.label_52.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_18.addWidget(self.label_52, 0, 0, 4, 1)
        self._ToolSpinTmax = QtGui.QDoubleSpinBox(self._ToolSpinPanel)
        self._ToolSpinTmax.setDecimals(1)
        self._ToolSpinTmax.setMaximum(10000.0)
        self._ToolSpinTmax.setProperty("value", 2000.0)
        self._ToolSpinTmax.setObjectName(_fromUtf8("_ToolSpinTmax"))
        self.gridLayout_18.addWidget(self._ToolSpinTmax, 1, 5, 1, 1)
        self.label_20 = QtGui.QLabel(self._ToolSpinPanel)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_18.addWidget(self.label_20, 0, 4, 1, 1)
        self._ToolSpinTh = QtGui.QDoubleSpinBox(self._ToolSpinPanel)
        self._ToolSpinTh.setProperty("value", 2.0)
        self._ToolSpinTh.setObjectName(_fromUtf8("_ToolSpinTh"))
        self.gridLayout_18.addWidget(self._ToolSpinTh, 2, 3, 1, 2)
        self.verticalLayout_36.addLayout(self.gridLayout_18)
        self._ToolSpinTable = QtGui.QTableWidget(self._ToolSpinPanel)
        self._ToolSpinTable.setMaximumSize(QtCore.QSize(16777215, 100))
        self._ToolSpinTable.setObjectName(_fromUtf8("_ToolSpinTable"))
        self._ToolSpinTable.setColumnCount(2)
        self._ToolSpinTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self._ToolSpinTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self._ToolSpinTable.setHorizontalHeaderItem(1, item)
        self._ToolSpinTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_36.addWidget(self._ToolSpinTable)
        self.verticalLayout_26.addWidget(self._ToolSpinPanel)
        self._ToolWavePanel = QtGui.QWidget(self.groupBox_4)
        self._ToolWavePanel.setMinimumSize(QtCore.QSize(0, 0))
        self._ToolWavePanel.setObjectName(_fromUtf8("_ToolWavePanel"))
        self.verticalLayout_40 = QtGui.QVBoxLayout(self._ToolWavePanel)
        self.verticalLayout_40.setMargin(0)
        self.verticalLayout_40.setSpacing(0)
        self.verticalLayout_40.setObjectName(_fromUtf8("verticalLayout_40"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_53 = QtGui.QLabel(self._ToolWavePanel)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_53.setFont(font)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_9.addWidget(self.label_53, 0, 0, 2, 1)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem22, 0, 5, 1, 1)
        self._ToolWaveAmp = QtGui.QDoubleSpinBox(self._ToolWavePanel)
        self._ToolWaveAmp.setMinimum(0.0)
        self._ToolWaveAmp.setMaximum(200.0)
        self._ToolWaveAmp.setProperty("value", 70.0)
        self._ToolWaveAmp.setObjectName(_fromUtf8("_ToolWaveAmp"))
        self.gridLayout_9.addWidget(self._ToolWaveAmp, 1, 4, 1, 1)
        self._ToolWaveTh = QtGui.QDoubleSpinBox(self._ToolWavePanel)
        self._ToolWaveTh.setMaximum(10.0)
        self._ToolWaveTh.setSingleStep(0.5)
        self._ToolWaveTh.setProperty("value", 1.0)
        self._ToolWaveTh.setObjectName(_fromUtf8("_ToolWaveTh"))
        self.gridLayout_9.addWidget(self._ToolWaveTh, 0, 4, 1, 1)
        self.label_46 = QtGui.QLabel(self._ToolWavePanel)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_9.addWidget(self.label_46, 0, 2, 1, 1)
        self.line_7 = QtGui.QFrame(self._ToolWavePanel)
        self.line_7.setMinimumSize(QtCore.QSize(10, 0))
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_9.addWidget(self.line_7, 0, 1, 2, 1)
        self.label_47 = QtGui.QLabel(self._ToolWavePanel)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_9.addWidget(self.label_47, 1, 2, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem23, 0, 3, 1, 1)
        self.verticalLayout_40.addLayout(self.gridLayout_9)
        self.verticalLayout_26.addWidget(self._ToolWavePanel)
        self.verticalLayout_38.addWidget(self.groupBox_4)
        spacerItem24 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_38.addItem(spacerItem24)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem25)
        self._ToolDetectApply = QtGui.QPushButton(self.q_DetectSettings)
        self._ToolDetectApply.setObjectName(_fromUtf8("_ToolDetectApply"))
        self.horizontalLayout_8.addWidget(self._ToolDetectApply)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem26)
        self.verticalLayout_38.addLayout(self.horizontalLayout_8)
        self._ToolDetectProgress = QtGui.QProgressBar(self.q_DetectSettings)
        self._ToolDetectProgress.setProperty("value", 24)
        self._ToolDetectProgress.setInvertedAppearance(False)
        self._ToolDetectProgress.setObjectName(_fromUtf8("_ToolDetectProgress"))
        self.verticalLayout_38.addWidget(self._ToolDetectProgress)
        self._DetectionTab.addTab(self.q_DetectSettings, _fromUtf8(""))
        self.q_DetectLoc = QtGui.QWidget()
        self.q_DetectLoc.setObjectName(_fromUtf8("q_DetectLoc"))
        self.verticalLayout_39 = QtGui.QVBoxLayout(self.q_DetectLoc)
        self.verticalLayout_39.setObjectName(_fromUtf8("verticalLayout_39"))
        self._DetectLocHead = QtGui.QLabel(self.q_DetectLoc)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self._DetectLocHead.setFont(font)
        self._DetectLocHead.setAlignment(QtCore.Qt.AlignCenter)
        self._DetectLocHead.setObjectName(_fromUtf8("_DetectLocHead"))
        self.verticalLayout_39.addWidget(self._DetectLocHead)
        self._DetectLocations = QtGui.QTableWidget(self.q_DetectLoc)
        self._DetectLocations.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self._DetectLocations.setAlternatingRowColors(True)
        self._DetectLocations.setObjectName(_fromUtf8("_DetectLocations"))
        self._DetectLocations.setColumnCount(3)
        self._DetectLocations.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self._DetectLocations.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self._DetectLocations.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self._DetectLocations.setHorizontalHeaderItem(2, item)
        self._DetectLocations.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_39.addWidget(self._DetectLocations)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_48 = QtGui.QLabel(self.q_DetectLoc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_10.addWidget(self.label_48, 0, 0, 1, 1)
        self._DetectLocExport = QtGui.QPushButton(self.q_DetectLoc)
        self._DetectLocExport.setObjectName(_fromUtf8("_DetectLocExport"))
        self.gridLayout_10.addWidget(self._DetectLocExport, 0, 3, 1, 1)
        self._DetectLocExportAs = QtGui.QComboBox(self.q_DetectLoc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._DetectLocExportAs.sizePolicy().hasHeightForWidth())
        self._DetectLocExportAs.setSizePolicy(sizePolicy)
        self._DetectLocExportAs.setObjectName(_fromUtf8("_DetectLocExportAs"))
        self._DetectLocExportAs.addItem(_fromUtf8(""))
        self._DetectLocExportAs.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self._DetectLocExportAs, 0, 1, 1, 1)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem27, 0, 2, 1, 1)
        self.verticalLayout_39.addLayout(self.gridLayout_10)
        self._DetectionTab.addTab(self.q_DetectLoc, _fromUtf8(""))
        self.verticalLayout_22.addWidget(self._DetectionTab)
        self.QuickSettings.addTab(self.q_Detection, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.QuickSettings)
        self.horizontalLayout_2.addWidget(self.q_widget)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_18.addItem(spacerItem28)
        self._chanGrid = QtGui.QGridLayout()
        self._chanGrid.setContentsMargins(-1, -1, -1, 6)
        self._chanGrid.setSpacing(3)
        self._chanGrid.setObjectName(_fromUtf8("_chanGrid"))
        self.verticalLayout_18.addLayout(self._chanGrid)
        self._TimeAxisW = QtGui.QWidget(self.centralwidget)
        self._TimeAxisW.setMinimumSize(QtCore.QSize(0, 0))
        self._TimeAxisW.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self._TimeAxisW.setObjectName(_fromUtf8("_TimeAxisW"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self._TimeAxisW)
        self.verticalLayout_21.setMargin(0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self._TimeLayout = QtGui.QVBoxLayout()
        self._TimeLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self._TimeLayout.setContentsMargins(9, -1, 9, -1)
        self._TimeLayout.setSpacing(0)
        self._TimeLayout.setObjectName(_fromUtf8("_TimeLayout"))
        self.verticalLayout_21.addLayout(self._TimeLayout)
        self.verticalLayout_18.addWidget(self._TimeAxisW)
        self._SpecW = QtGui.QWidget(self.centralwidget)
        self._SpecW.setMinimumSize(QtCore.QSize(0, 0))
        self._SpecW.setObjectName(_fromUtf8("_SpecW"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self._SpecW)
        self.verticalLayout_17.setMargin(0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self._SpecLayout = QtGui.QVBoxLayout()
        self._SpecLayout.setContentsMargins(9, -1, 9, -1)
        self._SpecLayout.setSpacing(0)
        self._SpecLayout.setObjectName(_fromUtf8("_SpecLayout"))
        self.verticalLayout_17.addLayout(self._SpecLayout)
        self.verticalLayout_18.addWidget(self._SpecW)
        self._HypW = QtGui.QWidget(self.centralwidget)
        self._HypW.setMinimumSize(QtCore.QSize(0, 0))
        self._HypW.setObjectName(_fromUtf8("_HypW"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self._HypW)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self._HypLayout = QtGui.QVBoxLayout()
        self._HypLayout.setContentsMargins(9, -1, 9, -1)
        self._HypLayout.setSpacing(0)
        self._HypLayout.setObjectName(_fromUtf8("_HypLayout"))
        self.verticalLayout_16.addLayout(self._HypLayout)
        self.verticalLayout_18.addWidget(self._HypW)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem29)
        self._slFrame = QtGui.QFrame(self.centralwidget)
        self._slFrame.setMinimumSize(QtCore.QSize(0, 0))
        self._slFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self._slFrame.setFrameShadow(QtGui.QFrame.Raised)
        self._slFrame.setObjectName(_fromUtf8("_slFrame"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self._slFrame)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_7.setHorizontalSpacing(7)
        self.gridLayout_7.setVerticalSpacing(9)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self._SlGoto = QtGui.QDoubleSpinBox(self._slFrame)
        self._SlGoto.setDecimals(1)
        self._SlGoto.setObjectName(_fromUtf8("_SlGoto"))
        self.gridLayout_7.addWidget(self._SlGoto, 2, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self._slFrame)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_7.addWidget(self.label_31, 2, 12, 1, 1)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem30, 2, 14, 1, 1)
        self.label = QtGui.QLabel(self._slFrame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 2, 0, 1, 1)
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem31, 2, 7, 1, 1)
        self._slGrid = QtGui.QCheckBox(self._slFrame)
        self._slGrid.setChecked(True)
        self._slGrid.setObjectName(_fromUtf8("_slGrid"))
        self.gridLayout_7.addWidget(self._slGrid, 2, 15, 1, 1)
        self.label_4 = QtGui.QLabel(self._slFrame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_7.addWidget(self.label_4, 2, 6, 1, 1)
        self._SlVal = QtGui.QSlider(self._slFrame)
        self._SlVal.setOrientation(QtCore.Qt.Horizontal)
        self._SlVal.setTickPosition(QtGui.QSlider.NoTicks)
        self._SlVal.setTickInterval(10)
        self._SlVal.setObjectName(_fromUtf8("_SlVal"))
        self.gridLayout_7.addWidget(self._SlVal, 1, 0, 1, 16)
        self._SigSlStep = QtGui.QDoubleSpinBox(self._slFrame)
        self._SigSlStep.setDecimals(1)
        self._SigSlStep.setMinimum(0.1)
        self._SigSlStep.setProperty("value", 30.0)
        self._SigSlStep.setObjectName(_fromUtf8("_SigSlStep"))
        self.gridLayout_7.addWidget(self._SigSlStep, 2, 9, 1, 1)
        self.label_3 = QtGui.QLabel(self._slFrame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_7.addWidget(self.label_3, 2, 4, 1, 1)
        self._SigWin = QtGui.QDoubleSpinBox(self._slFrame)
        self._SigWin.setDecimals(1)
        self._SigWin.setMaximum(1000.0)
        self._SigWin.setProperty("value", 30.0)
        self._SigWin.setObjectName(_fromUtf8("_SigWin"))
        self.gridLayout_7.addWidget(self._SigWin, 2, 5, 1, 1)
        self._slRules = QtGui.QComboBox(self._slFrame)
        self._slRules.setObjectName(_fromUtf8("_slRules"))
        self._slRules.addItem(_fromUtf8(""))
        self._slRules.addItem(_fromUtf8(""))
        self._slRules.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self._slRules, 2, 13, 1, 1)
        spacerItem32 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem32, 2, 11, 1, 1)
        self.label_12 = QtGui.QLabel(self._slFrame)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_7.addWidget(self.label_12, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self._slFrame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_7.addWidget(self.label_5, 2, 8, 1, 1)
        self._SlText = QtGui.QLabel(self._slFrame)
        self._SlText.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self._SlText.setObjectName(_fromUtf8("_SlText"))
        self.gridLayout_7.addWidget(self._SlText, 0, 0, 1, 16)
        self.label_6 = QtGui.QLabel(self._slFrame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_7.addWidget(self.label_6, 2, 10, 1, 1)
        spacerItem33 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem33, 2, 3, 1, 1)
        self.verticalLayout_15.addLayout(self.gridLayout_7)
        self.horizontalLayout_3.addWidget(self._slFrame)
        spacerItem34 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem34)
        self.verticalLayout_18.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_18)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1328, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFiles = QtGui.QMenu(self.menubar)
        self.menuFiles.setObjectName(_fromUtf8("menuFiles"))
        self.menuDisplay = QtGui.QMenu(self.menubar)
        self.menuDisplay.setObjectName(_fromUtf8("menuDisplay"))
        self.menuPanel = QtGui.QMenu(self.menuDisplay)
        self.menuPanel.setObjectName(_fromUtf8("menuPanel"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionCortical_repartition = QtGui.QAction(MainWindow)
        self.actionCortical_repartition.setObjectName(_fromUtf8("actionCortical_repartition"))
        self.actionCortical = QtGui.QAction(MainWindow)
        self.actionCortical.setObjectName(_fromUtf8("actionCortical"))
        self.actionSagittal = QtGui.QAction(MainWindow)
        self.actionSagittal.setObjectName(_fromUtf8("actionSagittal"))
        self.actionAxial = QtGui.QAction(MainWindow)
        self.actionAxial.setObjectName(_fromUtf8("actionAxial"))
        self.actionCamera = QtGui.QAction(MainWindow)
        self.actionCamera.setObjectName(_fromUtf8("actionCamera"))
        self.actionLeft = QtGui.QAction(MainWindow)
        self.actionLeft.setObjectName(_fromUtf8("actionLeft"))
        self.actionRight = QtGui.QAction(MainWindow)
        self.actionRight.setObjectName(_fromUtf8("actionRight"))
        self.actionQuick_settings = QtGui.QAction(MainWindow)
        self.actionQuick_settings.setCheckable(True)
        self.actionQuick_settings.setChecked(True)
        self.actionQuick_settings.setObjectName(_fromUtf8("actionQuick_settings"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionProjection = QtGui.QAction(MainWindow)
        self.actionProjection.setObjectName(_fromUtf8("actionProjection"))
        self.actionRepartition = QtGui.QAction(MainWindow)
        self.actionRepartition.setObjectName(_fromUtf8("actionRepartition"))
        self.actionShortcuts = QtGui.QAction(MainWindow)
        self.actionShortcuts.setCheckable(True)
        self.actionShortcuts.setObjectName(_fromUtf8("actionShortcuts"))
        self.actionUi_settings = QtGui.QAction(MainWindow)
        self.actionUi_settings.setCheckable(True)
        self.actionUi_settings.setChecked(False)
        self.actionUi_settings.setObjectName(_fromUtf8("actionUi_settings"))
        self.actionNdPlt = QtGui.QAction(MainWindow)
        self.actionNdPlt.setCheckable(True)
        self.actionNdPlt.setObjectName(_fromUtf8("actionNdPlt"))
        self.actionOnedPlt = QtGui.QAction(MainWindow)
        self.actionOnedPlt.setCheckable(True)
        self.actionOnedPlt.setObjectName(_fromUtf8("actionOnedPlt"))
        self.actionImage = QtGui.QAction(MainWindow)
        self.actionImage.setCheckable(True)
        self.actionImage.setObjectName(_fromUtf8("actionImage"))
        self.actionColormap = QtGui.QAction(MainWindow)
        self.actionColormap.setCheckable(True)
        self.actionColormap.setObjectName(_fromUtf8("actionColormap"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.menuDisplay.addAction(self.actionQuick_settings)
        self.menuDisplay.addAction(self.menuPanel.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.menuFiles.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.QuickSettings.setCurrentIndex(3)
        self._DetectionTab.setCurrentIndex(1)
        self._slRules.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Sleep", None))
        self.QuickSettings.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_41.setText(_translate("MainWindow", "Manage visible channels, amplitude, \n"
"spectrogram, hypnogram and the time axis", None))
        self.groupBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the channels to be displayed and control the amplitudes of each one of them.</p></body></html>", None))
        self.groupBox.setTitle(_translate("MainWindow", "Visible channels", None))
        self._PanScrollChan.setToolTip(_translate("MainWindow", "<html><head/><body><p/></body></html>", None))
        self._PanChanSelectAll.setToolTip(_translate("MainWindow", "<html><head/><body><p>Display all channels</p></body></html>", None))
        self._PanChanSelectAll.setText(_translate("MainWindow", "Select all", None))
        self._PanChanDeselectAll.setToolTip(_translate("MainWindow", "<html><head/><body><p>Hide all channels</p></body></html>", None))
        self._PanChanDeselectAll.setText(_translate("MainWindow", "Deselect all", None))
        self.label_35.setText(_translate("MainWindow", "Set all amplitudes to: ", None))
        self._PanAllAmpMin.setToolTip(_translate("MainWindow", "<html><head/><body><p>Change minimum amplitude for all channels</p></body></html>", None))
        self._PanAllAmpMax.setToolTip(_translate("MainWindow", "<html><head/><body><p>Change maximum amplitude for all channels</p></body></html>", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Spectrogram", None))
        self._PanSpecViz.setToolTip(_translate("MainWindow", "<html><head/><body><p>Display / hide the spectrogram</p></body></html>", None))
        self._PanSpecViz.setText(_translate("MainWindow", "Visible", None))
        self._PanSpecIndic.setToolTip(_translate("MainWindow", "<html><head/><body><p>Display / hide the time window indicator</p></body></html>", None))
        self._PanSpecIndic.setText(_translate("MainWindow", "Indicator", None))
        self._PanSpecZoom.setToolTip(_translate("MainWindow", "<html><head/><body><p>Zoom over the spectrogram</p></body></html>", None))
        self._PanSpecZoom.setText(_translate("MainWindow", "Zoom", None))
        self.label_17.setText(_translate("MainWindow", "f end", None))
        self.label_15.setText(_translate("MainWindow", "Overlap", None))
        self.label_16.setText(_translate("MainWindow", "f start", None))
        self._PanSpecCon.setToolTip(_translate("MainWindow", "<html><head/><body><p>Change the contrast of the spectrogram</p></body></html>", None))
        self.label_24.setText(_translate("MainWindow", "Contraste", None))
        self.label_13.setText(_translate("MainWindow", "Channel", None))
        self._PanSpecStep.setToolTip(_translate("MainWindow", "<html><head/><body><p>Overlap between each  consecutive windows.</p></body></html>", None))
        self._PanSpecNfft.setToolTip(_translate("MainWindow", "<html><head/><body><p>Length of each time window for computing the spectrogram</p></body></html>", None))
        self._PanSpecFstart.setToolTip(_translate("MainWindow", "<html><head/><body><p>Starting frequency for the spectrogram</p></body></html>", None))
        self._PanSpecFend.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ending frequency for the spectrogram</p></body></html>", None))
        self.label_14.setText(_translate("MainWindow", "Length", None))
        self.label_2.setText(_translate("MainWindow", "sec", None))
        self._PanSpecCmap.setToolTip(_translate("MainWindow", "<html><head/><body><p>Colormap for the spectrogram</p></body></html>", None))
        self.label_55.setText(_translate("MainWindow", "Settings", None))
        self.label_54.setText(_translate("MainWindow", "Apply\n"
"on", None))
        self.label_23.setText(_translate("MainWindow", "sec", None))
        self.label_29.setText(_translate("MainWindow", "Colormap", None))
        self._PanSpecApply.setToolTip(_translate("MainWindow", "<html><head/><body><p>Compute the spectrogram on the selected channel and using the time length, overlap, [fstart, fend], colormap and contrast.</p></body></html>", None))
        self._PanSpecApply.setText(_translate("MainWindow", "Apply", None))
        self._PanSpecChan.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select to channel used for the spectrogram</p></body></html>", None))
        self._PanHypGrp.setTitle(_translate("MainWindow", "Hypnogram", None))
        self._PanHypViz.setToolTip(_translate("MainWindow", "<html><head/><body><p>Display / hide the hypnogram</p></body></html>", None))
        self._PanHypViz.setText(_translate("MainWindow", "Visible", None))
        self._PanHypIndic.setToolTip(_translate("MainWindow", "<html><head/><body><p>Display / hide the time window indicator</p></body></html>", None))
        self._PanHypIndic.setText(_translate("MainWindow", "Indicator", None))
        self._PanHypZoom.setToolTip(_translate("MainWindow", "<html><head/><body><p>Zoom over the hypnogram</p></body></html>", None))
        self._PanHypZoom.setText(_translate("MainWindow", "Zoom", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Time axis", None))
        self._PanTimeIndic.setToolTip(_translate("MainWindow", "<html><head/><body><p>Display / hide the time window indicator</p></body></html>", None))
        self._PanTimeIndic.setText(_translate("MainWindow", "Indicator", None))
        self._PanTimeViz.setToolTip(_translate("MainWindow", "<html><head/><body><p>Display / hide the time axis</p></body></html>", None))
        self._PanTimeViz.setText(_translate("MainWindow", "Visible", None))
        self._PanTimeZoom.setToolTip(_translate("MainWindow", "<html><head/><body><p>Zoom over the time axis</p></body></html>", None))
        self._PanTimeZoom.setText(_translate("MainWindow", "Zoom", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_Panels), _translate("MainWindow", "Panels", None))
        self.label_42.setText(_translate("MainWindow", "Set of signal processing tools (remove the mean and \n"
"trend, filtering)", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Mean and trend", None))
        self._SigMean.setText(_translate("MainWindow", "Remove the mean", None))
        self._SigTrend.setText(_translate("MainWindow", "Remove the linear trend", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Filtering", None))
        self._SigFilt.setToolTip(_translate("MainWindow", "<html><head/><body><p>Filter your data and spectrogram :</p><p>- Select the filter type (bandpass / bandstop / highpass / lowpass)</p><p>- Select the frequencies for filtering</p><p>- Select the filter method (butterworth or bessel) and its order</p></body></html>", None))
        self._SigFilt.setText(_translate("MainWindow", "Enable", None))
        self.label_10.setText(_translate("MainWindow", "Method", None))
        self.label_9.setText(_translate("MainWindow", "hz", None))
        self.label_7.setText(_translate("MainWindow", "Fmin", None))
        self.label_11.setText(_translate("MainWindow", "order", None))
        self.label_8.setText(_translate("MainWindow", "Fmax", None))
        self._SigFiltMeth.setItemText(0, _translate("MainWindow", "butterworth", None))
        self._SigFiltMeth.setItemText(1, _translate("MainWindow", "bessel", None))
        self._SigFiltBand.setToolTip(_translate("MainWindow", "<html><head/><body><p>- bandpass: keep only frequencies between [fmin, fmax]</p><p>- bandstop: remove frequencies between [fmin, fmax]</p><p>- lowpass: keep only frequencies under fmax</p><p>- highpass: keep only frequencies over fmin</p></body></html>", None))
        self._SigFiltBand.setItemText(0, _translate("MainWindow", "bandpass", None))
        self._SigFiltBand.setItemText(1, _translate("MainWindow", "bandstop", None))
        self._SigFiltBand.setItemText(2, _translate("MainWindow", "lowpass", None))
        self._SigFiltBand.setItemText(3, _translate("MainWindow", "highpass", None))
        self._SigFiltOrder.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose filter order and control narrow band. It is not recommended to use filter order over 3 (can provoc distorsion).</p></body></html>", None))
        self.label_18.setText(_translate("MainWindow", "Type", None))
        self._SigFiltApply.setText(_translate("MainWindow", "Apply", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_Tools), _translate("MainWindow", "Tools", None))
        self.label_44.setText(_translate("MainWindow", "Get and export usefull informations about the \n"
"hypnogram. Those informations change while editing it.", None))
        item = self._infoTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Infos", None))
        item = self._infoTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Values", None))
        self.label_32.setText(_translate("MainWindow", "Time window", None))
        self._infoExport.setText(_translate("MainWindow", "Export", None))
        self.label_33.setText(_translate("MainWindow", "seconds", None))
        self._infoExportAs.setItemText(0, _translate("MainWindow", "CSV file (*.csv)", None))
        self._infoExportAs.setItemText(1, _translate("MainWindow", "Text file (*.txt)", None))
        self.label_34.setText(_translate("MainWindow", "Export as", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_Info), _translate("MainWindow", "Infos", None))
        self.label_43.setText(_translate("MainWindow", "Score the hypnogram by manually adding / removing\n"
" lines. Alternatively, you can directly edit it from the grah.", None))
        self._scoreTable.setSortingEnabled(True)
        item = self._scoreTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "From (minutes)", None))
        item = self._scoreTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "To (minutes)", None))
        item = self._scoreTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Stage", None))
        self._scoreAdd.setText(_translate("MainWindow", "Add line", None))
        self._scoreRm.setText(_translate("MainWindow", "Remove line", None))
        self._scoreExportAs.setItemText(0, _translate("MainWindow", "CSV file (*.csv)", None))
        self._scoreExportAs.setItemText(1, _translate("MainWindow", "Text file (*.txt)", None))
        self.label_36.setText(_translate("MainWindow", "Export as: ", None))
        self._scoreExport.setText(_translate("MainWindow", "Export", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_Score), _translate("MainWindow", "Scoring", None))
        self.label_45.setText(_translate("MainWindow", "Perform a REM, spindles or peak detection either on \n"
"selected, visible or all channels.", None))
        self._ToolDetecVisible.setText(_translate("MainWindow", "Display detection", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Detection type", None))
        self.label_39.setText(_translate("MainWindow", "Type", None))
        self.label_25.setText(_translate("MainWindow", "On channel", None))
        self._ToolDetecReport.setToolTip(_translate("MainWindow", "<html><head/><body><p>Report the detection on the hypnogram. Only avaible for selected channel.</p></body></html>", None))
        self._ToolDetecReport.setText(_translate("MainWindow", "Report detection on hypnogram", None))
        self._ToolDetectType.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose the detection type</p></body></html>", None))
        self._ToolDetectType.setItemText(0, _translate("MainWindow", "REM", None))
        self._ToolDetectType.setItemText(1, _translate("MainWindow", "Spindles", None))
        self._ToolDetectType.setItemText(2, _translate("MainWindow", "Peaks", None))
        self._ToolDetectType.setItemText(3, _translate("MainWindow", "Slow waves", None))
        self._ToolRdViz.setText(_translate("MainWindow", "Visible", None))
        self.label_49.setText(_translate("MainWindow", "Apply\n"
"on", None))
        self._ToolRdSelected.setText(_translate("MainWindow", "Selected", None))
        self._ToolRdAll.setText(_translate("MainWindow", "All", None))
        self._ToolDetectChan.setToolTip(_translate("MainWindow", "<html><head/><body><p>Pick up a channel to run the detection (only avaible with &quot;Selected&quot; option)</p></body></html>", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Settings", None))
        self.label_26.setText(_translate("MainWindow", "Lookahead", None))
        self._ToolPeakLook.setToolTip(_translate("MainWindow", "<html><head/><body><p>Minimum distance between two peaks</p></body></html>", None))
        self.label_28.setText(_translate("MainWindow", "Display", None))
        self.label_27.setText(_translate("MainWindow", "seconds", None))
        self._ToolPeakMinMax.setToolTip(_translate("MainWindow", "<html><head/><body><p>Search either for maximum / minimum / both</p></body></html>", None))
        self._ToolPeakMinMax.setItemText(0, _translate("MainWindow", "Max only", None))
        self._ToolPeakMinMax.setItemText(1, _translate("MainWindow", "Min only", None))
        self._ToolPeakMinMax.setItemText(2, _translate("MainWindow", "Min and Max", None))
        self.label_50.setText(_translate("MainWindow", "Peak", None))
        self._ToolRemTh.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of standard deviation of the derivative signal</p></body></html>", None))
        self.label_38.setText(_translate("MainWindow", "Threshold", None))
        self._ToolRemOnly.setText(_translate("MainWindow", "Perform detection only for REM sleep", None))
        self.label_51.setText(_translate("MainWindow", "REM", None))
        self.label_40.setText(_translate("MainWindow", "Threshold", None))
        self._ToolSpinTmin.setToolTip(_translate("MainWindow", "<html><head/><body><p>Minimum spindle\'s duration</p></body></html>", None))
        self.label_37.setText(_translate("MainWindow", "ms", None))
        self._ToolSpinRemOnly.setText(_translate("MainWindow", "Perform detection only for NREM sleep", None))
        self._ToolSpinFmin.setToolTip(_translate("MainWindow", "High-pass cutoff frequency", None))
        self.label_30.setText(_translate("MainWindow", "Tmax", None))
        self.label_22.setText(_translate("MainWindow", "Tmin", None))
        self.label_19.setText(_translate("MainWindow", "Fmin", None))
        self._ToolSpinFmax.setToolTip(_translate("MainWindow", "Low-pass cutoff frequency", None))
        self.label_21.setText(_translate("MainWindow", "Hz", None))
        self.label_52.setText(_translate("MainWindow", "Spindles", None))
        self._ToolSpinTmax.setToolTip(_translate("MainWindow", "<html><head/><body><p>Maximum spindle\'s duration</p></body></html>", None))
        self.label_20.setText(_translate("MainWindow", "Fmax", None))
        self._ToolSpinTh.setToolTip(_translate("MainWindow", "<html><head/><body><p>Look for signals having an amplitude \'Threshold\' times superior to the deviation of the filtered signal amplitude</p></body></html>", None))
        item = self._ToolSpinTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Number", None))
        item = self._ToolSpinTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Density ( / min )", None))
        self.label_53.setText(_translate("MainWindow", "Slow\n"
"waves", None))
        self._ToolWaveAmp.setToolTip(_translate("MainWindow", "<html><head/><body><p>Minimum amplitude (mV) of Slow Wave (0 for no amplitude criteria)</p></body></html>", None))
        self._ToolWaveTh.setToolTip(_translate("MainWindow", "<html><head/><body><p>Number of standard deviations of delta power</p></body></html>", None))
        self.label_46.setText(_translate("MainWindow", "Power (std)", None))
        self.label_47.setText(_translate("MainWindow", "Amplitude (mV)", None))
        self._ToolDetectApply.setToolTip(_translate("MainWindow", "<html><head/><body><p>Apply detection either on :</p><p>- Selected channels via the channel selection box above</p><p>- Visible channels</p><p>- All channels</p></body></html>", None))
        self._ToolDetectApply.setText(_translate("MainWindow", "Apply", None))
        self._DetectionTab.setTabText(self._DetectionTab.indexOf(self.q_DetectSettings), _translate("MainWindow", "Settings", None))
        self._DetectLocHead.setText(_translate("MainWindow", "HEADER_chan", None))
        self._DetectLocations.setSortingEnabled(True)
        item = self._DetectLocations.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Start (seconds)", None))
        item = self._DetectLocations.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Duration (ms)", None))
        item = self._DetectLocations.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Stage", None))
        self.label_48.setText(_translate("MainWindow", "Export as", None))
        self._DetectLocExport.setText(_translate("MainWindow", "Export", None))
        self._DetectLocExportAs.setItemText(0, _translate("MainWindow", "CSV file (*.csv)", None))
        self._DetectLocExportAs.setItemText(1, _translate("MainWindow", "TXT file (*.txt)", None))
        self._DetectionTab.setTabText(self._DetectionTab.indexOf(self.q_DetectLoc), _translate("MainWindow", "Locations", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_Detection), _translate("MainWindow", "Detection", None))
        self.label_31.setText(_translate("MainWindow", "Rule", None))
        self.label.setText(_translate("MainWindow", "Go to", None))
        self._slGrid.setText(_translate("MainWindow", "Grid", None))
        self.label_4.setText(_translate("MainWindow", " seconds", None))
        self.label_3.setText(_translate("MainWindow", "Window", None))
        self._slRules.setItemText(0, _translate("MainWindow", "seconds", None))
        self._slRules.setItemText(1, _translate("MainWindow", "minutes", None))
        self._slRules.setItemText(2, _translate("MainWindow", "hours", None))
        self.label_12.setText(_translate("MainWindow", " seconds", None))
        self.label_5.setText(_translate("MainWindow", "Slider step", None))
        self._SlText.setText(_translate("MainWindow", "TextLabel", None))
        self.label_6.setText(_translate("MainWindow", " seconds", None))
        self.menuFiles.setTitle(_translate("MainWindow", "Files", None))
        self.menuDisplay.setTitle(_translate("MainWindow", "Display", None))
        self.menuPanel.setTitle(_translate("MainWindow", "Panel", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))
        self.actionCortical_repartition.setText(_translate("MainWindow", "Cortical repartition", None))
        self.actionCortical.setText(_translate("MainWindow", "Cortical", None))
        self.actionSagittal.setText(_translate("MainWindow", "Sagittal", None))
        self.actionAxial.setText(_translate("MainWindow", "Axial", None))
        self.actionCamera.setText(_translate("MainWindow", "Camera", None))
        self.actionLeft.setText(_translate("MainWindow", "Left", None))
        self.actionRight.setText(_translate("MainWindow", "Right", None))
        self.actionQuick_settings.setText(_translate("MainWindow", "Quick settings", None))
        self.actionQuick_settings.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionProjection.setText(_translate("MainWindow", "Projection", None))
        self.actionProjection.setToolTip(_translate("MainWindow", "<html><head/><body><p>Find all vertices under a distance of t_radius with each source and project s_data to the surface</p></body></html>", None))
        self.actionProjection.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.actionRepartition.setText(_translate("MainWindow", "Repartition", None))
        self.actionRepartition.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.actionShortcuts.setText(_translate("MainWindow", "Shortcuts", None))
        self.actionShortcuts.setShortcut(_translate("MainWindow", "Ctrl+T", None))
        self.actionUi_settings.setText(_translate("MainWindow", "Ui settings", None))
        self.actionNdPlt.setText(_translate("MainWindow", "Nd-plot", None))
        self.actionOnedPlt.setText(_translate("MainWindow", "1d-plot", None))
        self.actionImage.setText(_translate("MainWindow", "Image", None))
        self.actionColormap.setText(_translate("MainWindow", "Colormap", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation", None))

