# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/etienne/Toolbox/visbrain/visbrain/colorbar/gui/cbar_gui.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 871)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(300, 0))
        self.frame.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout.addWidget(self.label_18)
        self.cbObject = QtWidgets.QComboBox(self.frame)
        self.cbObject.setObjectName("cbObject")
        self.horizontalLayout.addWidget(self.cbObject)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.cbLimTxt = QtWidgets.QCheckBox(self.groupBox_3)
        self.cbLimTxt.setChecked(True)
        self.cbLimTxt.setObjectName("cbLimTxt")
        self.gridLayout_7.addWidget(self.cbLimTxt, 5, 0, 1, 3)
        self.line_9 = QtWidgets.QFrame(self.groupBox_3)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_7.addWidget(self.line_9, 2, 1, 1, 1)
        self.cbDigits = QtWidgets.QSpinBox(self.groupBox_3)
        self.cbDigits.setMinimum(1)
        self.cbDigits.setMaximum(6)
        self.cbDigits.setProperty("value", 2)
        self.cbDigits.setObjectName("cbDigits")
        self.gridLayout_7.addWidget(self.cbDigits, 2, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 3, 0, 1, 1)
        self.cbBckCol = QtWidgets.QLineEdit(self.groupBox_3)
        self.cbBckCol.setObjectName("cbBckCol")
        self.gridLayout_7.addWidget(self.cbBckCol, 0, 2, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.groupBox_3)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_7.addWidget(self.line_10, 3, 1, 1, 1)
        self.cbTxtCol = QtWidgets.QLineEdit(self.groupBox_3)
        self.cbTxtCol.setObjectName("cbTxtCol")
        self.gridLayout_7.addWidget(self.cbTxtCol, 1, 2, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.groupBox_3)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_7.addWidget(self.line_7, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 2, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.groupBox_3)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_7.addWidget(self.line_6, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 0, 1, 1)
        self.cbWidth = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.cbWidth.setSingleStep(0.01)
        self.cbWidth.setObjectName("cbWidth")
        self.gridLayout_7.addWidget(self.cbWidth, 3, 2, 1, 1)
        self.cbBorder = QtWidgets.QCheckBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.cbBorder.setFont(font)
        self.cbBorder.setObjectName("cbBorder")
        self.gridLayout_7.addWidget(self.cbBorder, 4, 0, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.groupBox_3)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_7.addWidget(self.line_11, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 1, 0, 1, 1)
        self.cbBw = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.cbBw.setDecimals(1)
        self.cbBw.setMinimum(0.1)
        self.cbBw.setObjectName("cbBw")
        self.gridLayout_7.addWidget(self.cbBw, 4, 2, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_7)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cbVmaxW = QtWidgets.QWidget(self.groupBox_2)
        self.cbVmaxW.setObjectName("cbVmaxW")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cbVmaxW)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cbVmaxOver = QtWidgets.QLineEdit(self.cbVmaxW)
        self.cbVmaxOver.setObjectName("cbVmaxOver")
        self.gridLayout_3.addWidget(self.cbVmaxOver, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.cbVmaxW)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.cbVmaxVal = QtWidgets.QDoubleSpinBox(self.cbVmaxW)
        self.cbVmaxVal.setObjectName("cbVmaxVal")
        self.gridLayout_3.addWidget(self.cbVmaxVal, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.cbVmaxW)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.gridLayout.addWidget(self.cbVmaxW, 3, 2, 1, 2)
        self.cbCmap = QtWidgets.QComboBox(self.groupBox_2)
        self.cbCmap.setObjectName("cbCmap")
        self.gridLayout.addWidget(self.cbCmap, 0, 2, 1, 1)
        self.cbCmapRev = QtWidgets.QCheckBox(self.groupBox_2)
        self.cbCmapRev.setObjectName("cbCmapRev")
        self.gridLayout.addWidget(self.cbCmapRev, 0, 3, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 0, 1, 1, 1)
        self.cbVminW = QtWidgets.QWidget(self.groupBox_2)
        self.cbVminW.setObjectName("cbVminW")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.cbVminW)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.cbVminW)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.cbVminVal = QtWidgets.QDoubleSpinBox(self.cbVminW)
        self.cbVminVal.setDecimals(3)
        self.cbVminVal.setObjectName("cbVminVal")
        self.gridLayout_2.addWidget(self.cbVminVal, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.cbVminW)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.cbVminUnder = QtWidgets.QLineEdit(self.cbVminW)
        self.cbVminUnder.setObjectName("cbVminUnder")
        self.gridLayout_2.addWidget(self.cbVminUnder, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.cbVminW, 2, 2, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 2, 1, 1)
        self.cbVmaxChk = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setItalic(True)
        self.cbVmaxChk.setFont(font)
        self.cbVmaxChk.setObjectName("cbVmaxChk")
        self.gridLayout.addWidget(self.cbVmaxChk, 3, 0, 1, 1)
        self.cbVminChk = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setItalic(True)
        self.cbVminChk.setFont(font)
        self.cbVminChk.setObjectName("cbVminChk")
        self.gridLayout.addWidget(self.cbVminChk, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbClimm = QtWidgets.QDoubleSpinBox(self.widget)
        self.cbClimm.setMinimum(-16777215.0)
        self.cbClimm.setMaximum(16777215.0)
        self.cbClimm.setObjectName("cbClimm")
        self.horizontalLayout_3.addWidget(self.cbClimm)
        self.cbClimM = QtWidgets.QDoubleSpinBox(self.widget)
        self.cbClimM.setMinimum(-16777215.0)
        self.cbClimM.setMaximum(16777215.0)
        self.cbClimM.setObjectName("cbClimM")
        self.horizontalLayout_3.addWidget(self.cbClimM)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.widget, 1, 2, 1, 2)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line_5 = QtWidgets.QFrame(self.groupBox)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_4.addWidget(self.line_5, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.groupBox)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cbCblabel = QtWidgets.QLineEdit(self.widget_3)
        self.cbCblabel.setObjectName("cbCblabel")
        self.gridLayout_5.addWidget(self.cbCblabel, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.cbCbTxtSz = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.cbCbTxtSz.setDecimals(1)
        self.cbCbTxtSz.setObjectName("cbCbTxtSz")
        self.gridLayout_5.addWidget(self.cbCbTxtSz, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 2, 0, 1, 1)
        self.cbCbTxtSh = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.cbCbTxtSh.setDecimals(1)
        self.cbCbTxtSh.setSingleStep(0.1)
        self.cbCbTxtSh.setObjectName("cbCbTxtSh")
        self.gridLayout_5.addWidget(self.cbCbTxtSh, 2, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_5)
        self.gridLayout_4.addWidget(self.widget_3, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.groupBox)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_4.addWidget(self.line_8, 1, 1, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.groupBox)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.cbTxtSh = QtWidgets.QDoubleSpinBox(self.widget_4)
        self.cbTxtSh.setDecimals(1)
        self.cbTxtSh.setSingleStep(0.1)
        self.cbTxtSh.setObjectName("cbTxtSh")
        self.gridLayout_6.addWidget(self.cbTxtSh, 1, 1, 1, 1)
        self.cbTxtSz = QtWidgets.QDoubleSpinBox(self.widget_4)
        self.cbTxtSz.setDecimals(1)
        self.cbTxtSz.setObjectName("cbTxtSz")
        self.gridLayout_6.addWidget(self.cbTxtSz, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 2, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_6)
        self.gridLayout_4.addWidget(self.widget_4, 1, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_2.addWidget(self.frame)
        self.CbarLayout = QtWidgets.QHBoxLayout()
        self.CbarLayout.setObjectName("CbarLayout")
        self.horizontalLayout_2.addLayout(self.CbarLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1110, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuConfiguration = QtWidgets.QMenu(self.menuFile)
        self.menuConfiguration.setObjectName("menuConfiguration")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionScreenshot = QtWidgets.QAction(MainWindow)
        self.actionScreenshot.setObjectName("actionScreenshot")
        self.actionSaveConfig = QtWidgets.QAction(MainWindow)
        self.actionSaveConfig.setObjectName("actionSaveConfig")
        self.actionLoadConfig = QtWidgets.QAction(MainWindow)
        self.actionLoadConfig.setObjectName("actionLoadConfig")
        self.menuConfiguration.addAction(self.actionSaveConfig)
        self.menuConfiguration.addAction(self.actionLoadConfig)
        self.menuFile.addAction(self.menuConfiguration.menuAction())
        self.menuFile.addAction(self.actionScreenshot)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Colorbar editor"))
        self.label_18.setText(_translate("MainWindow", "Colorbar of"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Settings"))
        self.cbLimTxt.setText(_translate("MainWindow", "Display vmin/vmax text"))
        self.label_17.setText(_translate("MainWindow", "Colorbar\n"
"width"))
        self.label_16.setText(_translate("MainWindow", "Number of\n"
"digits"))
        self.label_8.setText(_translate("MainWindow", "Background\n"
"color"))
        self.cbBorder.setText(_translate("MainWindow", "Border"))
        self.label_9.setText(_translate("MainWindow", "Textcolor"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Color properties"))
        self.label_5.setText(_translate("MainWindow", "Value"))
        self.label_6.setText(_translate("MainWindow", "Over\n"
"color"))
        self.cbCmapRev.setText(_translate("MainWindow", "Reversed"))
        self.label_3.setText(_translate("MainWindow", "Value"))
        self.label_4.setText(_translate("MainWindow", "Under\n"
"color"))
        self.cbVmaxChk.setText(_translate("MainWindow", "Vmax"))
        self.cbVminChk.setText(_translate("MainWindow", "Vmin"))
        self.label_2.setText(_translate("MainWindow", "Clim"))
        self.label.setText(_translate("MainWindow", "Colormap"))
        self.groupBox.setTitle(_translate("MainWindow", "Text properties"))
        self.label_11.setText(_translate("MainWindow", "Size"))
        self.label_10.setText(_translate("MainWindow", "Value"))
        self.label_13.setText(_translate("MainWindow", "Shift"))
        self.label_7.setText(_translate("MainWindow", "Title"))
        self.label_12.setText(_translate("MainWindow", "Limits"))
        self.label_14.setText(_translate("MainWindow", "Size"))
        self.label_15.setText(_translate("MainWindow", "Shift"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuConfiguration.setTitle(_translate("MainWindow", "Configuration"))
        self.actionScreenshot.setText(_translate("MainWindow", "Screenshot"))
        self.actionSaveConfig.setText(_translate("MainWindow", "Save"))
        self.actionLoadConfig.setText(_translate("MainWindow", "Load"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

