.. raw:: html

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
     <!-- Indicators -->
     <ol class="carousel-indicators">
       <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
       <li data-target="#myCarousel" data-slide-to="1"></li>
       <li data-target="#myCarousel" data-slide-to="2"></li>
       <li data-target="#myCarousel" data-slide-to="3"></li>
       <li data-target="#myCarousel" data-slide-to="4"></li>
       <li data-target="#myCarousel" data-slide-to="5"></li>
       <li data-target="#myCarousel" data-slide-to="6"></li>
     </ol>

     <!----------------------------------------------------------------------->
     <!----------------------------   SLIDES   ------------------------------->
     <!----------------------------------------------------------------------->

     <!-- 0 - PIP INSTALLATION -->
     <div class="carousel-inner">
       <div class="item active">
         <img src="_static/carousel/pip_install.png" alt="Installation">
         <div class="carousel-caption">
           <h3><a href="introduction.html#install-visbrain">Install visbrain</a></h3>
           <p>Run <a href="introduction.html#installation">pip install visbrain</a> in a terminal</p>
         </div>
       </div>


     <!-- 1 - DEEP SOURCES -->
     <div class="item">
       <img src="_static/carousel/deep_sources.png" alt="Deep sources">
       <div class="carousel-caption">
         <h3>[<a href="brain.html">Brain</a>] Display deep sources</h3>
         <p>Checkout the <a href="brain.html">documentation</a> and
          <a href="auto_examples/index.html#brain-examples">examples</a></p>
         </p>
       </div>
     </div>


     <!-- 2 - 3D CONNECTIVITY -->
     <div class="item">
       <img src="_static/carousel/connect.png" alt="3D Connectivity">
       <div class="carousel-caption">
         <h3>[<a href="brain.html">Brain</a>] Display 3D connectivity</h3>
         <p>Checkout the <a href="brain.html">documentation</a> and
          <a href="auto_examples/index.html#brain-examples">examples</a>
        </p>
       </div>
     </div>


     <!-- 3 - PLOT SOURCE ESTIMATION -->
     <!--
     <div class="item">
       <img src="ny.png" alt="New York">
       <div class="carousel-caption">
         <h3>[<a href="brain.html">Brain</a>]</h3>
         <p>We love the Big Apple!
          Checkout the <a href="brain.html">documentation</a> and
          <a href="auto_examples/index.html#brain-examples">examples</a>
        </p>
       </div>
     </div>
     -->

     <!-- 4 - SLEEP -->
     <div class="item">
         <img src="_static/carousel/sleep.png" alt="Sleep spindles">
         <div class="carousel-caption">
           <h3>[<a href="sleep.html">Sleep</a>] Polysomnographic sleep data</h3>
           <p>Visualize, analyse and score of polysomnographic sleep data.
           Checkout the <a href="sleep.html">documentation</a> and
           <a href="auto_examples/index.html#sleep-examples">examples</a></p>
         </div>
       </div>

     <!-- 5 - TOPO -->
     <div class="item">
         <img src="_static/carousel/topo.png" alt="Topo">
         <div class="carousel-caption">
           <h3>[<a href="topo.html">Topo</a>] Topographic representations</h3>
           <p>Checkout the <a href="topo.html">documentation</a> and
           <a href="auto_examples/index.html#topoplot-examples">examples</a></p>
         </div>
       </div>

     <!-- 6 - SIGNAL -->
     <div class="item">
         <img src="_static/carousel/signal.png" alt="Signal">
         <div class="carousel-caption">
           <h3>[<a href="signal.html">Signal</a>] Explore electrophysiological data</h3>
           <p>Checkout the <a href="signal.html">documentation</a> and
           <a href="auto_examples/index.html#signal-examples">examples</a></p>
         </div>
       </div>

    <!-- 7 - OBJECTS -->
    <div class="item">
        <img src="_static/carousel/objects.png" alt="Objects">
        <div class="carousel-caption">
          <h3>[<a href="objects.html">Objects</a>] Create complex scenes with multiple objects</h3>
          <p>Checkout the <a href="objects.html">documentation</a> and
          <a href="auto_examples/index.html#objects-examples">examples</a></p>
        </div>
      </div>
    </div>

    <!----------------------------------------------------------------------->
     <!-- Left and right controls -->
    <!----------------------------------------------------------------------->
     <a class="left carousel-control" href="#myCarousel" data-slide="prev">
       <span class="glyphicon glyphicon-chevron-left"></span>
       <span class="sr-only">Previous</span>
     </a>
     <a class="right carousel-control" href="#myCarousel" data-slide="next">
       <span class="glyphicon glyphicon-chevron-right"></span>
       <span class="sr-only">Next</span>
     </a>
   </div>