# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visbrain_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1328, 919)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.q_widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q_widget.sizePolicy().hasHeightForWidth())
        self.q_widget.setSizePolicy(sizePolicy)
        self.q_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.q_widget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.q_widget.setObjectName(_fromUtf8("q_widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.q_widget)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.QuickSettings = QtGui.QTabWidget(self.q_widget)
        self.QuickSettings.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.QuickSettings.setObjectName(_fromUtf8("QuickSettings"))
        self.q_UI = QtGui.QWidget()
        self.q_UI.setObjectName(_fromUtf8("q_UI"))
        self.verticalLayout = QtGui.QVBoxLayout(self.q_UI)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.toolBox_4 = QtGui.QToolBox(self.q_UI)
        self.toolBox_4.setObjectName(_fromUtf8("toolBox_4"))
        self.ui_Settings = QtGui.QWidget()
        self.ui_Settings.setGeometry(QtCore.QRect(0, 0, 332, 85))
        self.ui_Settings.setObjectName(_fromUtf8("ui_Settings"))
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.ui_Settings)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.verticalLayout_33 = QtGui.QVBoxLayout()
        self.verticalLayout_33.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_33.setObjectName(_fromUtf8("verticalLayout_33"))
        self.groupBox_3 = QtGui.QGroupBox(self.ui_Settings)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 70))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_6.addWidget(self.label)
        self.bgd_red = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.bgd_red.setDecimals(1)
        self.bgd_red.setMaximum(1.0)
        self.bgd_red.setSingleStep(0.1)
        self.bgd_red.setObjectName(_fromUtf8("bgd_red"))
        self.horizontalLayout_6.addWidget(self.bgd_red)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.bgd_green = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.bgd_green.setDecimals(1)
        self.bgd_green.setMaximum(1.0)
        self.bgd_green.setSingleStep(0.1)
        self.bgd_green.setObjectName(_fromUtf8("bgd_green"))
        self.horizontalLayout_6.addWidget(self.bgd_green)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.bgd_blue = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.bgd_blue.setDecimals(1)
        self.bgd_blue.setMaximum(1.0)
        self.bgd_blue.setSingleStep(0.1)
        self.bgd_blue.setObjectName(_fromUtf8("bgd_blue"))
        self.horizontalLayout_6.addWidget(self.bgd_blue)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_33.addWidget(self.groupBox_3)
        self.verticalLayout_25.addLayout(self.verticalLayout_33)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem2)
        self.toolBox_4.addItem(self.ui_Settings, _fromUtf8(""))
        self.ui_Opacity = QtGui.QWidget()
        self.ui_Opacity.setGeometry(QtCore.QRect(0, 0, 228, 332))
        self.ui_Opacity.setObjectName(_fromUtf8("ui_Opacity"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.ui_Opacity)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.groupBox = QtGui.QGroupBox(self.ui_Opacity)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.o_Brain = QtGui.QCheckBox(self.groupBox)
        self.o_Brain.setChecked(True)
        self.o_Brain.setObjectName(_fromUtf8("o_Brain"))
        self.gridLayout_2.addWidget(self.o_Brain, 0, 0, 1, 1)
        self.o_Sources = QtGui.QCheckBox(self.groupBox)
        self.o_Sources.setObjectName(_fromUtf8("o_Sources"))
        self.gridLayout_2.addWidget(self.o_Sources, 0, 1, 1, 1)
        self.o_Connect = QtGui.QCheckBox(self.groupBox)
        self.o_Connect.setObjectName(_fromUtf8("o_Connect"))
        self.gridLayout_2.addWidget(self.o_Connect, 1, 0, 1, 1)
        self.o_Text = QtGui.QCheckBox(self.groupBox)
        self.o_Text.setObjectName(_fromUtf8("o_Text"))
        self.gridLayout_2.addWidget(self.o_Text, 1, 1, 1, 1)
        self.o_Areas = QtGui.QCheckBox(self.groupBox)
        self.o_Areas.setObjectName(_fromUtf8("o_Areas"))
        self.gridLayout_2.addWidget(self.o_Areas, 2, 0, 1, 1)
        self.verticalLayout_27.addLayout(self.gridLayout_2)
        self.verticalLayout_19.addWidget(self.groupBox)
        self.groupBox_9 = QtGui.QGroupBox(self.ui_Opacity)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_32 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_32.setObjectName(_fromUtf8("verticalLayout_32"))
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.OpacitySlider = QtGui.QSlider(self.groupBox_9)
        self.OpacitySlider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.OpacitySlider.setAutoFillBackground(False)
        self.OpacitySlider.setMinimum(-5)
        self.OpacitySlider.setMaximum(105)
        self.OpacitySlider.setPageStep(1)
        self.OpacitySlider.setProperty("value", 1)
        self.OpacitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.OpacitySlider.setInvertedAppearance(False)
        self.OpacitySlider.setInvertedControls(False)
        self.OpacitySlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.OpacitySlider.setObjectName(_fromUtf8("OpacitySlider"))
        self.verticalLayout_24.addWidget(self.OpacitySlider)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_3 = QtGui.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_15.addWidget(self.label_3)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.label_4 = QtGui.QLabel(self.groupBox_9)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setUnderline(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_15.addWidget(self.label_4)
        self.verticalLayout_24.addLayout(self.horizontalLayout_15)
        self.verticalLayout_32.addLayout(self.verticalLayout_24)
        self.verticalLayout_19.addWidget(self.groupBox_9)
        self.groupBox_10 = QtGui.QGroupBox(self.ui_Opacity)
        self.groupBox_10.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_34 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_34.setObjectName(_fromUtf8("verticalLayout_34"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_6 = QtGui.QLabel(self.groupBox_10)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.xSlices = QtGui.QSlider(self.groupBox_10)
        self.xSlices.setMinimum(-110)
        self.xSlices.setMaximum(110)
        self.xSlices.setSingleStep(1)
        self.xSlices.setPageStep(1)
        self.xSlices.setProperty("value", 110)
        self.xSlices.setOrientation(QtCore.Qt.Horizontal)
        self.xSlices.setObjectName(_fromUtf8("xSlices"))
        self.horizontalLayout_12.addWidget(self.xSlices)
        self.xInvert = QtGui.QCheckBox(self.groupBox_10)
        self.xInvert.setObjectName(_fromUtf8("xInvert"))
        self.horizontalLayout_12.addWidget(self.xInvert)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.label_7 = QtGui.QLabel(self.groupBox_10)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.ySlices = QtGui.QSlider(self.groupBox_10)
        self.ySlices.setMinimum(-140)
        self.ySlices.setMaximum(140)
        self.ySlices.setPageStep(1)
        self.ySlices.setProperty("value", 140)
        self.ySlices.setOrientation(QtCore.Qt.Horizontal)
        self.ySlices.setObjectName(_fromUtf8("ySlices"))
        self.horizontalLayout_13.addWidget(self.ySlices)
        self.yInvert = QtGui.QCheckBox(self.groupBox_10)
        self.yInvert.setObjectName(_fromUtf8("yInvert"))
        self.horizontalLayout_13.addWidget(self.yInvert)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.label_8 = QtGui.QLabel(self.groupBox_10)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.zSlices = QtGui.QSlider(self.groupBox_10)
        self.zSlices.setMinimum(-110)
        self.zSlices.setMaximum(110)
        self.zSlices.setPageStep(1)
        self.zSlices.setProperty("value", 110)
        self.zSlices.setOrientation(QtCore.Qt.Horizontal)
        self.zSlices.setObjectName(_fromUtf8("zSlices"))
        self.horizontalLayout_14.addWidget(self.zSlices)
        self.zInvert = QtGui.QCheckBox(self.groupBox_10)
        self.zInvert.setObjectName(_fromUtf8("zInvert"))
        self.horizontalLayout_14.addWidget(self.zInvert)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.verticalLayout_34.addLayout(self.verticalLayout_2)
        self.verticalLayout_19.addWidget(self.groupBox_10)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem4)
        self.verticalLayout_17.addLayout(self.verticalLayout_19)
        self.toolBox_4.addItem(self.ui_Opacity, _fromUtf8(""))
        self.ui_Camera = QtGui.QWidget()
        self.ui_Camera.setGeometry(QtCore.QRect(0, 0, 327, 157))
        self.ui_Camera.setObjectName(_fromUtf8("ui_Camera"))
        self.verticalLayout_30 = QtGui.QVBoxLayout(self.ui_Camera)
        self.verticalLayout_30.setObjectName(_fromUtf8("verticalLayout_30"))
        self.verticalLayout_29 = QtGui.QVBoxLayout()
        self.verticalLayout_29.setObjectName(_fromUtf8("verticalLayout_29"))
        self.groupBox_8 = QtGui.QGroupBox(self.ui_Camera)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_31 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_31.setObjectName(_fromUtf8("verticalLayout_31"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.q_coronal = QtGui.QPushButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.q_coronal.setFont(font)
        self.q_coronal.setAutoDefault(True)
        self.q_coronal.setDefault(True)
        self.q_coronal.setFlat(False)
        self.q_coronal.setObjectName(_fromUtf8("q_coronal"))
        self.horizontalLayout.addWidget(self.q_coronal)
        self.q_axial = QtGui.QPushButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.q_axial.setFont(font)
        self.q_axial.setObjectName(_fromUtf8("q_axial"))
        self.horizontalLayout.addWidget(self.q_axial)
        self.q_sagittal = QtGui.QPushButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.q_sagittal.setFont(font)
        self.q_sagittal.setObjectName(_fromUtf8("q_sagittal"))
        self.horizontalLayout.addWidget(self.q_sagittal)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_31.addLayout(self.horizontalLayout)
        self.verticalLayout_29.addWidget(self.groupBox_8)
        self.groupBox_4 = QtGui.QGroupBox(self.ui_Camera)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.c_Fly = QtGui.QRadioButton(self.groupBox_4)
        self.c_Fly.setMaximumSize(QtCore.QSize(100, 16777215))
        self.c_Fly.setObjectName(_fromUtf8("c_Fly"))
        self.gridLayout.addWidget(self.c_Fly, 0, 1, 1, 1)
        self.c_Turnable = QtGui.QRadioButton(self.groupBox_4)
        self.c_Turnable.setMaximumSize(QtCore.QSize(100, 16777215))
        self.c_Turnable.setChecked(True)
        self.c_Turnable.setObjectName(_fromUtf8("c_Turnable"))
        self.gridLayout.addWidget(self.c_Turnable, 0, 0, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem7)
        self.verticalLayout_29.addWidget(self.groupBox_4)
        self.verticalLayout_30.addLayout(self.verticalLayout_29)
        self.toolBox_4.addItem(self.ui_Camera, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 276, 307))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.page_5)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.grpLightPos = QtGui.QGroupBox(self.page_5)
        self.grpLightPos.setObjectName(_fromUtf8("grpLightPos"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.grpLightPos)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.uil_posX = QtGui.QDoubleSpinBox(self.grpLightPos)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.uil_posX.setFont(font)
        self.uil_posX.setMaximum(1000.0)
        self.uil_posX.setProperty("value", 10.0)
        self.uil_posX.setObjectName(_fromUtf8("uil_posX"))
        self.horizontalLayout_4.addWidget(self.uil_posX)
        self.uil_posY = QtGui.QDoubleSpinBox(self.grpLightPos)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.uil_posY.setFont(font)
        self.uil_posY.setMaximum(1000.0)
        self.uil_posY.setProperty("value", 10.0)
        self.uil_posY.setObjectName(_fromUtf8("uil_posY"))
        self.horizontalLayout_4.addWidget(self.uil_posY)
        self.uil_posZ = QtGui.QDoubleSpinBox(self.grpLightPos)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.uil_posZ.setFont(font)
        self.uil_posZ.setMaximum(1000.0)
        self.uil_posZ.setProperty("value", 10.0)
        self.uil_posZ.setObjectName(_fromUtf8("uil_posZ"))
        self.horizontalLayout_4.addWidget(self.uil_posZ)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_4)
        self.verticalLayout_26.addWidget(self.grpLightPos)
        self.grpLightColor = QtGui.QGroupBox(self.page_5)
        self.grpLightColor.setObjectName(_fromUtf8("grpLightColor"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.grpLightColor)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.uil_colR = QtGui.QDoubleSpinBox(self.grpLightColor)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.uil_colR.setFont(font)
        self.uil_colR.setMaximum(1.0)
        self.uil_colR.setSingleStep(0.1)
        self.uil_colR.setProperty("value", 1.0)
        self.uil_colR.setObjectName(_fromUtf8("uil_colR"))
        self.horizontalLayout_29.addWidget(self.uil_colR)
        self.uil_colG = QtGui.QDoubleSpinBox(self.grpLightColor)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.uil_colG.setFont(font)
        self.uil_colG.setMaximum(1.0)
        self.uil_colG.setSingleStep(0.1)
        self.uil_colG.setProperty("value", 1.0)
        self.uil_colG.setObjectName(_fromUtf8("uil_colG"))
        self.horizontalLayout_29.addWidget(self.uil_colG)
        self.uil_colB = QtGui.QDoubleSpinBox(self.grpLightColor)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.uil_colB.setFont(font)
        self.uil_colB.setMaximum(1.0)
        self.uil_colB.setSingleStep(0.1)
        self.uil_colB.setProperty("value", 1.0)
        self.uil_colB.setObjectName(_fromUtf8("uil_colB"))
        self.horizontalLayout_29.addWidget(self.uil_colB)
        self.uil_colA = QtGui.QDoubleSpinBox(self.grpLightColor)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.uil_colA.setFont(font)
        self.uil_colA.setDecimals(2)
        self.uil_colA.setMaximum(1.0)
        self.uil_colA.setSingleStep(0.1)
        self.uil_colA.setProperty("value", 1.0)
        self.uil_colA.setObjectName(_fromUtf8("uil_colA"))
        self.horizontalLayout_29.addWidget(self.uil_colA)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_29)
        self.verticalLayout_26.addWidget(self.grpLightColor)
        self.grpLightIntensity = QtGui.QGroupBox(self.page_5)
        self.grpLightIntensity.setObjectName(_fromUtf8("grpLightIntensity"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout(self.grpLightIntensity)
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.uil_intX = QtGui.QDoubleSpinBox(self.grpLightIntensity)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.uil_intX.setFont(font)
        self.uil_intX.setMaximum(1.0)
        self.uil_intX.setSingleStep(0.1)
        self.uil_intX.setProperty("value", 1.0)
        self.uil_intX.setObjectName(_fromUtf8("uil_intX"))
        self.horizontalLayout_31.addWidget(self.uil_intX)
        self.uil_intY = QtGui.QDoubleSpinBox(self.grpLightIntensity)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.uil_intY.setFont(font)
        self.uil_intY.setMaximum(1.0)
        self.uil_intY.setSingleStep(0.1)
        self.uil_intY.setProperty("value", 1.0)
        self.uil_intY.setObjectName(_fromUtf8("uil_intY"))
        self.horizontalLayout_31.addWidget(self.uil_intY)
        self.uil_intZ = QtGui.QDoubleSpinBox(self.grpLightIntensity)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.uil_intZ.setFont(font)
        self.uil_intZ.setMaximum(1.0)
        self.uil_intZ.setSingleStep(0.1)
        self.uil_intZ.setProperty("value", 1.0)
        self.uil_intZ.setObjectName(_fromUtf8("uil_intZ"))
        self.horizontalLayout_31.addWidget(self.uil_intZ)
        self.horizontalLayout_32.addLayout(self.horizontalLayout_31)
        self.verticalLayout_26.addWidget(self.grpLightIntensity)
        self.grpLightCoefficient = QtGui.QGroupBox(self.page_5)
        self.grpLightCoefficient.setObjectName(_fromUtf8("grpLightCoefficient"))
        self.verticalLayout_36 = QtGui.QVBoxLayout(self.grpLightCoefficient)
        self.verticalLayout_36.setObjectName(_fromUtf8("verticalLayout_36"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_9 = QtGui.QLabel(self.grpLightCoefficient)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.uil_AmbCoef = QtGui.QDoubleSpinBox(self.grpLightCoefficient)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.uil_AmbCoef.setFont(font)
        self.uil_AmbCoef.setMaximum(1.0)
        self.uil_AmbCoef.setSingleStep(0.1)
        self.uil_AmbCoef.setProperty("value", 0.13)
        self.uil_AmbCoef.setObjectName(_fromUtf8("uil_AmbCoef"))
        self.gridLayout_3.addWidget(self.uil_AmbCoef, 0, 1, 1, 1)
        self.uil_SpecCoef = QtGui.QDoubleSpinBox(self.grpLightCoefficient)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.uil_SpecCoef.setFont(font)
        self.uil_SpecCoef.setSingleStep(0.1)
        self.uil_SpecCoef.setProperty("value", 0.5)
        self.uil_SpecCoef.setObjectName(_fromUtf8("uil_SpecCoef"))
        self.gridLayout_3.addWidget(self.uil_SpecCoef, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.grpLightCoefficient)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.verticalLayout_36.addLayout(self.gridLayout_3)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_36.addItem(spacerItem8)
        self.verticalLayout_26.addWidget(self.grpLightCoefficient)
        self.verticalLayout_22.addLayout(self.verticalLayout_26)
        self.toolBox_4.addItem(self.page_5, _fromUtf8(""))
        self.verticalLayout.addWidget(self.toolBox_4)
        self.QuickSettings.addTab(self.q_UI, _fromUtf8(""))
        self.q_MNI = QtGui.QWidget()
        self.q_MNI.setObjectName(_fromUtf8("q_MNI"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.q_MNI)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.show_MNI = QtGui.QCheckBox(self.q_MNI)
        self.show_MNI.setChecked(True)
        self.show_MNI.setObjectName(_fromUtf8("show_MNI"))
        self.horizontalLayout_9.addWidget(self.show_MNI)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.toolBox_2 = QtGui.QToolBox(self.q_MNI)
        self.toolBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.toolBox_2.setFont(font)
        self.toolBox_2.setObjectName(_fromUtf8("toolBox_2"))
        self.pOpacity = QtGui.QWidget()
        self.pOpacity.setGeometry(QtCore.QRect(0, 0, 240, 231))
        self.pOpacity.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pOpacity.setFont(font)
        self.pOpacity.setObjectName(_fromUtf8("pOpacity"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.pOpacity)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.groupBox_14 = QtGui.QGroupBox(self.pOpacity)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.horizontalLayout_37 = QtGui.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem11)
        self.Lhemi_only = QtGui.QRadioButton(self.groupBox_14)
        self.Lhemi_only.setObjectName(_fromUtf8("Lhemi_only"))
        self.horizontalLayout_26.addWidget(self.Lhemi_only)
        self.Both_only = QtGui.QRadioButton(self.groupBox_14)
        self.Both_only.setChecked(True)
        self.Both_only.setObjectName(_fromUtf8("Both_only"))
        self.horizontalLayout_26.addWidget(self.Both_only)
        self.Rhemi_only = QtGui.QRadioButton(self.groupBox_14)
        self.Rhemi_only.setObjectName(_fromUtf8("Rhemi_only"))
        self.horizontalLayout_26.addWidget(self.Rhemi_only)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem12)
        self.horizontalLayout_37.addLayout(self.horizontalLayout_26)
        self.verticalLayout_12.addWidget(self.groupBox_14)
        self.groupBox_2 = QtGui.QGroupBox(self.pOpacity)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 5, -1, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.q_internal = QtGui.QRadioButton(self.groupBox_2)
        self.q_internal.setObjectName(_fromUtf8("q_internal"))
        self.horizontalLayout_8.addWidget(self.q_internal)
        self.q_external = QtGui.QRadioButton(self.groupBox_2)
        self.q_external.setObjectName(_fromUtf8("q_external"))
        self.horizontalLayout_8.addWidget(self.q_external)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_8)
        self.verticalLayout_12.addWidget(self.groupBox_2)
        self.groupBox_6 = QtGui.QGroupBox(self.pOpacity)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_35 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_35.setObjectName(_fromUtf8("verticalLayout_35"))
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setObjectName(_fromUtf8("horizontalLayout_45"))
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem15)
        self.uiSwitchTemplate = QtGui.QComboBox(self.groupBox_6)
        self.uiSwitchTemplate.setObjectName(_fromUtf8("uiSwitchTemplate"))
        self.uiSwitchTemplate.addItem(_fromUtf8(""))
        self.uiSwitchTemplate.addItem(_fromUtf8(""))
        self.uiSwitchTemplate.addItem(_fromUtf8(""))
        self.horizontalLayout_45.addWidget(self.uiSwitchTemplate)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem16)
        self.verticalLayout_35.addLayout(self.horizontalLayout_45)
        self.verticalLayout_12.addWidget(self.groupBox_6)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem17)
        self.verticalLayout_18.addLayout(self.verticalLayout_12)
        self.toolBox_2.addItem(self.pOpacity, _fromUtf8(""))
        self.widget = QtGui.QWidget()
        self.widget.setGeometry(QtCore.QRect(0, 0, 360, 645))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem18)
        self.structEnable = QtGui.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.structEnable.setFont(font)
        self.structEnable.setObjectName(_fromUtf8("structEnable"))
        self.horizontalLayout_43.addWidget(self.structEnable)
        self.strcutShow = QtGui.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.strcutShow.setFont(font)
        self.strcutShow.setObjectName(_fromUtf8("strcutShow"))
        self.horizontalLayout_43.addWidget(self.strcutShow)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem19)
        self.verticalLayout_28.addLayout(self.horizontalLayout_43)
        self.structPanel = QtGui.QWidget(self.widget)
        self.structPanel.setObjectName(_fromUtf8("structPanel"))
        self.verticalLayout_47 = QtGui.QVBoxLayout(self.structPanel)
        self.verticalLayout_47.setObjectName(_fromUtf8("verticalLayout_47"))
        self.groupBox_17 = QtGui.QGroupBox(self.structPanel)
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.horizontalLayout_51 = QtGui.QHBoxLayout(self.groupBox_17)
        self.horizontalLayout_51.setObjectName(_fromUtf8("horizontalLayout_51"))
        self.horizontalLayout_44 = QtGui.QHBoxLayout()
        self.horizontalLayout_44.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_44.setObjectName(_fromUtf8("horizontalLayout_44"))
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem20)
        self.struct_Internal = QtGui.QRadioButton(self.groupBox_17)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.struct_Internal.setFont(font)
        self.struct_Internal.setChecked(True)
        self.struct_Internal.setObjectName(_fromUtf8("struct_Internal"))
        self.horizontalLayout_44.addWidget(self.struct_Internal)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem21)
        self.struct_External = QtGui.QRadioButton(self.groupBox_17)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.struct_External.setFont(font)
        self.struct_External.setObjectName(_fromUtf8("struct_External"))
        self.horizontalLayout_44.addWidget(self.struct_External)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem22)
        self.horizontalLayout_51.addLayout(self.horizontalLayout_44)
        self.verticalLayout_47.addWidget(self.groupBox_17)
        self.groupBox_15 = QtGui.QGroupBox(self.structPanel)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.horizontalLayout_41 = QtGui.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem23)
        self.Sub_brod = QtGui.QRadioButton(self.groupBox_15)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Sub_brod.setFont(font)
        self.Sub_brod.setChecked(True)
        self.Sub_brod.setObjectName(_fromUtf8("Sub_brod"))
        self.horizontalLayout_38.addWidget(self.Sub_brod)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem24)
        self.Sub_aal = QtGui.QRadioButton(self.groupBox_15)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Sub_aal.setFont(font)
        self.Sub_aal.setObjectName(_fromUtf8("Sub_aal"))
        self.horizontalLayout_38.addWidget(self.Sub_aal)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem25)
        self.horizontalLayout_41.addLayout(self.horizontalLayout_38)
        self.verticalLayout_47.addWidget(self.groupBox_15)
        self.groupBox_16 = QtGui.QGroupBox(self.structPanel)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.verticalLayout_43 = QtGui.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_43.setObjectName(_fromUtf8("verticalLayout_43"))
        self.verticalLayout_42 = QtGui.QVBoxLayout()
        self.verticalLayout_42.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_42.setObjectName(_fromUtf8("verticalLayout_42"))
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.struct2select = QtGui.QListWidget(self.groupBox_16)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.struct2select.setFont(font)
        self.struct2select.setTabKeyNavigation(True)
        self.struct2select.setAlternatingRowColors(True)
        self.struct2select.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.struct2select.setObjectName(_fromUtf8("struct2select"))
        self.horizontalLayout_42.addWidget(self.struct2select)
        self.struct2add = QtGui.QListWidget(self.groupBox_16)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.struct2add.setFont(font)
        self.struct2add.setObjectName(_fromUtf8("struct2add"))
        self.horizontalLayout_42.addWidget(self.struct2add)
        self.verticalLayout_42.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_47 = QtGui.QHBoxLayout()
        self.horizontalLayout_47.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_47.setSpacing(0)
        self.horizontalLayout_47.setObjectName(_fromUtf8("horizontalLayout_47"))
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem26)
        self.struct_addLst = QtGui.QPushButton(self.groupBox_16)
        self.struct_addLst.setObjectName(_fromUtf8("struct_addLst"))
        self.horizontalLayout_47.addWidget(self.struct_addLst)
        self.struct_rstLst = QtGui.QPushButton(self.groupBox_16)
        self.struct_rstLst.setObjectName(_fromUtf8("struct_rstLst"))
        self.horizontalLayout_47.addWidget(self.struct_rstLst)
        self.struct_rmvLst = QtGui.QPushButton(self.groupBox_16)
        self.struct_rmvLst.setObjectName(_fromUtf8("struct_rmvLst"))
        self.horizontalLayout_47.addWidget(self.struct_rmvLst)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem27)
        self.verticalLayout_42.addLayout(self.horizontalLayout_47)
        self.verticalLayout_43.addLayout(self.verticalLayout_42)
        self.verticalLayout_47.addWidget(self.groupBox_16)
        self.groupBox_19 = QtGui.QGroupBox(self.structPanel)
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.verticalLayout_44 = QtGui.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_44.setObjectName(_fromUtf8("verticalLayout_44"))
        self.horizontalLayout_46 = QtGui.QHBoxLayout()
        self.horizontalLayout_46.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_46.setObjectName(_fromUtf8("horizontalLayout_46"))
        self.label_16 = QtGui.QLabel(self.groupBox_19)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_46.addWidget(self.label_16)
        self.struct_color_edit = QtGui.QLineEdit(self.groupBox_19)
        self.struct_color_edit.setInputMask(_fromUtf8(""))
        self.struct_color_edit.setText(_fromUtf8(""))
        self.struct_color_edit.setPlaceholderText(_fromUtf8(""))
        self.struct_color_edit.setObjectName(_fromUtf8("struct_color_edit"))
        self.horizontalLayout_46.addWidget(self.struct_color_edit)
        self.verticalLayout_44.addLayout(self.horizontalLayout_46)
        self.verticalLayout_47.addWidget(self.groupBox_19)
        self.verticalLayout_28.addWidget(self.structPanel)
        spacerItem28 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_28.addItem(spacerItem28)
        self.verticalLayout_20.addLayout(self.verticalLayout_28)
        self.horizontalLayout_49 = QtGui.QHBoxLayout()
        self.horizontalLayout_49.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_49.setObjectName(_fromUtf8("horizontalLayout_49"))
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem29)
        self.struct_apply = QtGui.QPushButton(self.widget)
        self.struct_apply.setObjectName(_fromUtf8("struct_apply"))
        self.horizontalLayout_49.addWidget(self.struct_apply)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem30)
        self.structClear = QtGui.QPushButton(self.widget)
        self.structClear.setObjectName(_fromUtf8("structClear"))
        self.horizontalLayout_49.addWidget(self.structClear)
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem31)
        self.verticalLayout_20.addLayout(self.horizontalLayout_49)
        self.toolBox_2.addItem(self.widget, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.toolBox_2)
        self.QuickSettings.addTab(self.q_MNI, _fromUtf8(""))
        self.q_SOURCES = QtGui.QWidget()
        self.q_SOURCES.setObjectName(_fromUtf8("q_SOURCES"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.q_SOURCES)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem32 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem32)
        self.show_Sources = QtGui.QCheckBox(self.q_SOURCES)
        self.show_Sources.setChecked(True)
        self.show_Sources.setObjectName(_fromUtf8("show_Sources"))
        self.horizontalLayout_16.addWidget(self.show_Sources)
        spacerItem33 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem33)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.toolBox = QtGui.QToolBox(self.q_SOURCES)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 348, 256))
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_5 = QtGui.QGroupBox(self.page)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem34 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem34)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.widget1 = QtGui.QWidget(self.groupBox_5)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.s_LeftH = QtGui.QRadioButton(self.widget1)
        self.s_LeftH.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.s_LeftH.setAutoExclusive(True)
        self.s_LeftH.setObjectName(_fromUtf8("s_LeftH"))
        self.verticalLayout_8.addWidget(self.s_LeftH)
        self.s_RightH = QtGui.QRadioButton(self.widget1)
        self.s_RightH.setObjectName(_fromUtf8("s_RightH"))
        self.verticalLayout_8.addWidget(self.s_RightH)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.horizontalLayout_10.addWidget(self.widget1)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_10)
        self.widget_2 = QtGui.QWidget(self.groupBox_5)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.s_Inside = QtGui.QRadioButton(self.widget_2)
        self.s_Inside.setObjectName(_fromUtf8("s_Inside"))
        self.verticalLayout_10.addWidget(self.s_Inside)
        self.s_Outside = QtGui.QRadioButton(self.widget_2)
        self.s_Outside.setObjectName(_fromUtf8("s_Outside"))
        self.verticalLayout_10.addWidget(self.s_Outside)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.horizontalLayout_5.addWidget(self.widget_2)
        spacerItem35 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem35)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_19.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.grpText = QtGui.QGroupBox(self.page)
        self.grpText.setEnabled(True)
        self.grpText.setMinimumSize(QtCore.QSize(0, 0))
        self.grpText.setObjectName(_fromUtf8("grpText"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.grpText)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.q_stextshow = QtGui.QCheckBox(self.grpText)
        self.q_stextshow.setObjectName(_fromUtf8("q_stextshow"))
        self.verticalLayout_16.addWidget(self.q_stextshow)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_23.setSpacing(6)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_12 = QtGui.QLabel(self.grpText)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_23.addWidget(self.label_12)
        self.q_stextsize = QtGui.QSpinBox(self.grpText)
        self.q_stextsize.setProperty("value", 3)
        self.q_stextsize.setObjectName(_fromUtf8("q_stextsize"))
        self.horizontalLayout_23.addWidget(self.q_stextsize)
        spacerItem36 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem36)
        self.label_14 = QtGui.QLabel(self.grpText)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_23.addWidget(self.label_14)
        self.q_stextcolor = QtGui.QLineEdit(self.grpText)
        self.q_stextcolor.setObjectName(_fromUtf8("q_stextcolor"))
        self.horizontalLayout_23.addWidget(self.q_stextcolor)
        spacerItem37 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem37)
        self.verticalLayout_16.addLayout(self.horizontalLayout_23)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        spacerItem38 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem38)
        self.label_15 = QtGui.QLabel(self.grpText)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_28.addWidget(self.label_15)
        self.x_text = QtGui.QDoubleSpinBox(self.grpText)
        self.x_text.setMinimum(-100.0)
        self.x_text.setMaximum(100.0)
        self.x_text.setObjectName(_fromUtf8("x_text"))
        self.horizontalLayout_28.addWidget(self.x_text)
        self.label_17 = QtGui.QLabel(self.grpText)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_28.addWidget(self.label_17)
        self.y_text = QtGui.QDoubleSpinBox(self.grpText)
        self.y_text.setMinimum(-100.0)
        self.y_text.setMaximum(100.0)
        self.y_text.setObjectName(_fromUtf8("y_text"))
        self.horizontalLayout_28.addWidget(self.y_text)
        self.label_20 = QtGui.QLabel(self.grpText)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_28.addWidget(self.label_20)
        self.z_text = QtGui.QDoubleSpinBox(self.grpText)
        self.z_text.setMinimum(-100.0)
        self.z_text.setMaximum(100.0)
        self.z_text.setObjectName(_fromUtf8("z_text"))
        self.horizontalLayout_28.addWidget(self.z_text)
        spacerItem39 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem39)
        self.verticalLayout_15.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_22.addLayout(self.verticalLayout_15)
        self.verticalLayout_7.addWidget(self.grpText)
        spacerItem40 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem40)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.toolBox)
        self.QuickSettings.addTab(self.q_SOURCES, _fromUtf8(""))
        self.q_CONNECT = QtGui.QWidget()
        self.q_CONNECT.setObjectName(_fromUtf8("q_CONNECT"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.q_CONNECT)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem41 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem41)
        self.uiConnectShow = QtGui.QCheckBox(self.q_CONNECT)
        self.uiConnectShow.setChecked(True)
        self.uiConnectShow.setObjectName(_fromUtf8("uiConnectShow"))
        self.horizontalLayout_17.addWidget(self.uiConnectShow)
        spacerItem42 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem42)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        self.toolBox_5 = QtGui.QToolBox(self.q_CONNECT)
        self.toolBox_5.setObjectName(_fromUtf8("toolBox_5"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 327, 208))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_38 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_38.setObjectName(_fromUtf8("verticalLayout_38"))
        self.verticalLayout_37 = QtGui.QVBoxLayout()
        self.verticalLayout_37.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_37.setObjectName(_fromUtf8("verticalLayout_37"))
        self.groupBox_11 = QtGui.QGroupBox(self.page_3)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.verticalLayout_39 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_39.setObjectName(_fromUtf8("verticalLayout_39"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        spacerItem43 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem43)
        self.label_21 = QtGui.QLabel(self.groupBox_11)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_33.addWidget(self.label_21)
        self.uiConnect_colorby = QtGui.QComboBox(self.groupBox_11)
        self.uiConnect_colorby.setObjectName(_fromUtf8("uiConnect_colorby"))
        self.uiConnect_colorby.addItem(_fromUtf8(""))
        self.uiConnect_colorby.addItem(_fromUtf8(""))
        self.horizontalLayout_33.addWidget(self.uiConnect_colorby)
        spacerItem44 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem44)
        self.label_22 = QtGui.QLabel(self.groupBox_11)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_33.addWidget(self.label_22)
        self.uiConnect_lw = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.uiConnect_lw.setMinimum(0.1)
        self.uiConnect_lw.setMaximum(9.0)
        self.uiConnect_lw.setSingleStep(0.1)
        self.uiConnect_lw.setProperty("value", 4.0)
        self.uiConnect_lw.setObjectName(_fromUtf8("uiConnect_lw"))
        self.horizontalLayout_33.addWidget(self.uiConnect_lw)
        spacerItem45 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem45)
        self.verticalLayout_39.addLayout(self.horizontalLayout_33)
        self.verticalLayout_37.addWidget(self.groupBox_11)
        self.groupBox_7 = QtGui.QGroupBox(self.page_3)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_40 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_40.setObjectName(_fromUtf8("verticalLayout_40"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        spacerItem46 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem46)
        self.uiConnect_static = QtGui.QRadioButton(self.groupBox_7)
        self.uiConnect_static.setChecked(True)
        self.uiConnect_static.setObjectName(_fromUtf8("uiConnect_static"))
        self.horizontalLayout_34.addWidget(self.uiConnect_static)
        self.uiConnect_dynamic = QtGui.QRadioButton(self.groupBox_7)
        self.uiConnect_dynamic.setObjectName(_fromUtf8("uiConnect_dynamic"))
        self.horizontalLayout_34.addWidget(self.uiConnect_dynamic)
        spacerItem47 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem47)
        self.verticalLayout_40.addLayout(self.horizontalLayout_34)
        self.uiConnect_dynControl = QtGui.QWidget(self.groupBox_7)
        self.uiConnect_dynControl.setMinimumSize(QtCore.QSize(0, 0))
        self.uiConnect_dynControl.setObjectName(_fromUtf8("uiConnect_dynControl"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout(self.uiConnect_dynControl)
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        spacerItem48 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem48)
        self.label_23 = QtGui.QLabel(self.uiConnect_dynControl)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_35.addWidget(self.label_23)
        self.uiConnect_dynMin = QtGui.QDoubleSpinBox(self.uiConnect_dynControl)
        self.uiConnect_dynMin.setMaximum(1.0)
        self.uiConnect_dynMin.setSingleStep(0.1)
        self.uiConnect_dynMin.setObjectName(_fromUtf8("uiConnect_dynMin"))
        self.horizontalLayout_35.addWidget(self.uiConnect_dynMin)
        spacerItem49 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem49)
        self.label_24 = QtGui.QLabel(self.uiConnect_dynControl)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_35.addWidget(self.label_24)
        self.uiConnect_dynMax = QtGui.QDoubleSpinBox(self.uiConnect_dynControl)
        self.uiConnect_dynMax.setMaximum(1.0)
        self.uiConnect_dynMax.setSingleStep(0.1)
        self.uiConnect_dynMax.setObjectName(_fromUtf8("uiConnect_dynMax"))
        self.horizontalLayout_35.addWidget(self.uiConnect_dynMax)
        spacerItem50 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem50)
        self.horizontalLayout_36.addLayout(self.horizontalLayout_35)
        self.verticalLayout_40.addWidget(self.uiConnect_dynControl)
        self.verticalLayout_37.addWidget(self.groupBox_7)
        self.verticalLayout_38.addLayout(self.verticalLayout_37)
        spacerItem51 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_38.addItem(spacerItem51)
        self.toolBox_5.addItem(self.page_3, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.toolBox_5.addItem(self.page_4, _fromUtf8(""))
        self.verticalLayout_13.addWidget(self.toolBox_5)
        self.QuickSettings.addTab(self.q_CONNECT, _fromUtf8(""))
        self.q_TRANS = QtGui.QWidget()
        self.q_TRANS.setObjectName(_fromUtf8("q_TRANS"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.q_TRANS)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        spacerItem52 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem52)
        self.q_cmap_interact = QtGui.QCheckBox(self.q_TRANS)
        self.q_cmap_interact.setChecked(False)
        self.q_cmap_interact.setObjectName(_fromUtf8("q_cmap_interact"))
        self.horizontalLayout_40.addWidget(self.q_cmap_interact)
        spacerItem53 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem53)
        self.verticalLayout_23.addLayout(self.horizontalLayout_40)
        self.groupBox_12 = QtGui.QGroupBox(self.q_TRANS)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.horizontalLayout_39 = QtGui.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.cmapSources = QtGui.QRadioButton(self.groupBox_12)
        self.cmapSources.setChecked(True)
        self.cmapSources.setObjectName(_fromUtf8("cmapSources"))
        self.gridLayout_4.addWidget(self.cmapSources, 0, 1, 1, 1)
        self.cmapConnect = QtGui.QRadioButton(self.groupBox_12)
        self.cmapConnect.setObjectName(_fromUtf8("cmapConnect"))
        self.gridLayout_4.addWidget(self.cmapConnect, 0, 2, 1, 1)
        spacerItem54 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem54, 0, 0, 1, 1)
        spacerItem55 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem55, 0, 3, 1, 1)
        self.horizontalLayout_39.addLayout(self.gridLayout_4)
        self.verticalLayout_23.addWidget(self.groupBox_12)
        self.groupBox_13 = QtGui.QGroupBox(self.q_TRANS)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.verticalLayout_41 = QtGui.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_41.setObjectName(_fromUtf8("verticalLayout_41"))
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_10 = QtGui.QLabel(self.groupBox_13)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_18.addWidget(self.label_10)
        self.q_cmap_list = QtGui.QComboBox(self.groupBox_13)
        self.q_cmap_list.setEditable(False)
        self.q_cmap_list.setObjectName(_fromUtf8("q_cmap_list"))
        self.horizontalLayout_18.addWidget(self.q_cmap_list)
        self.q_cmap_invert = QtGui.QCheckBox(self.groupBox_13)
        self.q_cmap_invert.setObjectName(_fromUtf8("q_cmap_invert"))
        self.horizontalLayout_18.addWidget(self.q_cmap_invert)
        self.q_auto_scale = QtGui.QCheckBox(self.groupBox_13)
        self.q_auto_scale.setObjectName(_fromUtf8("q_auto_scale"))
        self.horizontalLayout_18.addWidget(self.q_auto_scale)
        spacerItem56 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem56)
        self.verticalLayout_21.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.q_vmin_chk = QtGui.QCheckBox(self.groupBox_13)
        self.q_vmin_chk.setObjectName(_fromUtf8("q_vmin_chk"))
        self.horizontalLayout_20.addWidget(self.q_vmin_chk)
        spacerItem57 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem57)
        self.q_vmin = QtGui.QDoubleSpinBox(self.groupBox_13)
        self.q_vmin.setMinimum(-16777215.0)
        self.q_vmin.setMaximum(16777215.0)
        self.q_vmin.setSingleStep(1.0)
        self.q_vmin.setObjectName(_fromUtf8("q_vmin"))
        self.horizontalLayout_20.addWidget(self.q_vmin)
        spacerItem58 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem58)
        self.q_vmax_chk = QtGui.QCheckBox(self.groupBox_13)
        self.q_vmax_chk.setObjectName(_fromUtf8("q_vmax_chk"))
        self.horizontalLayout_20.addWidget(self.q_vmax_chk)
        self.q_vmax = QtGui.QDoubleSpinBox(self.groupBox_13)
        self.q_vmax.setMinimum(-16777215.0)
        self.q_vmax.setMaximum(16777215.0)
        self.q_vmax.setObjectName(_fromUtf8("q_vmax"))
        self.horizontalLayout_20.addWidget(self.q_vmax)
        spacerItem59 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem59)
        self.verticalLayout_21.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.q_under_chk = QtGui.QCheckBox(self.groupBox_13)
        self.q_under_chk.setObjectName(_fromUtf8("q_under_chk"))
        self.horizontalLayout_21.addWidget(self.q_under_chk)
        self.q_under = QtGui.QLineEdit(self.groupBox_13)
        self.q_under.setObjectName(_fromUtf8("q_under"))
        self.horizontalLayout_21.addWidget(self.q_under)
        self.q_over_chk = QtGui.QCheckBox(self.groupBox_13)
        self.q_over_chk.setObjectName(_fromUtf8("q_over_chk"))
        self.horizontalLayout_21.addWidget(self.q_over_chk)
        self.q_over = QtGui.QLineEdit(self.groupBox_13)
        self.q_over.setObjectName(_fromUtf8("q_over"))
        self.horizontalLayout_21.addWidget(self.q_over)
        self.verticalLayout_21.addLayout(self.horizontalLayout_21)
        self.line = QtGui.QFrame(self.groupBox_13)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_21.addWidget(self.line)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_11 = QtGui.QLabel(self.groupBox_13)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_25.addWidget(self.label_11)
        self.q_cblabel = QtGui.QLineEdit(self.groupBox_13)
        self.q_cblabel.setObjectName(_fromUtf8("q_cblabel"))
        self.horizontalLayout_25.addWidget(self.q_cblabel)
        self.verticalLayout_21.addLayout(self.horizontalLayout_25)
        self.cbpanel = QtGui.QVBoxLayout()
        self.cbpanel.setContentsMargins(-1, 0, -1, 0)
        self.cbpanel.setSpacing(0)
        self.cbpanel.setObjectName(_fromUtf8("cbpanel"))
        spacerItem60 = QtGui.QSpacerItem(100, 200, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.cbpanel.addItem(spacerItem60)
        self.verticalLayout_21.addLayout(self.cbpanel)
        self.verticalLayout_41.addLayout(self.verticalLayout_21)
        self.verticalLayout_23.addWidget(self.groupBox_13)
        self.QuickSettings.addTab(self.q_TRANS, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.QuickSettings)
        self.progressBar = QtGui.QProgressBar(self.q_widget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_4.addWidget(self.progressBar)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem61 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem61)
        self.q_reload = QtGui.QPushButton(self.q_widget)
        self.q_reload.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.q_reload.setObjectName(_fromUtf8("q_reload"))
        self.horizontalLayout_11.addWidget(self.q_reload)
        spacerItem62 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem62)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_2.addWidget(self.q_widget)
        self.vBrain = QtGui.QVBoxLayout()
        self.vBrain.setSpacing(0)
        self.vBrain.setObjectName(_fromUtf8("vBrain"))
        spacerItem63 = QtGui.QSpacerItem(800, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.vBrain.addItem(spacerItem63)
        self.horizontalLayout_2.addLayout(self.vBrain)
        self.table_panel = QtGui.QWidget(self.centralwidget)
        self.table_panel.setEnabled(True)
        self.table_panel.setMinimumSize(QtCore.QSize(0, 0))
        self.table_panel.setMaximumSize(QtCore.QSize(400, 16777215))
        self.table_panel.setObjectName(_fromUtf8("table_panel"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.table_panel)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.sh_table = QtGui.QTableWidget(self.table_panel)
        self.sh_table.setMinimumSize(QtCore.QSize(0, 0))
        self.sh_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sh_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.sh_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.sh_table.setObjectName(_fromUtf8("sh_table"))
        self.sh_table.setColumnCount(2)
        self.sh_table.setRowCount(14)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(9, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(10, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(10, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(11, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(11, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(12, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(12, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(13, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(13, 1, item)
        self.horizontalLayout_3.addWidget(self.sh_table)
        self.horizontalLayout_2.addWidget(self.table_panel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1328, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFiles = QtGui.QMenu(self.menubar)
        self.menuFiles.setObjectName(_fromUtf8("menuFiles"))
        self.menuTransform = QtGui.QMenu(self.menubar)
        self.menuTransform.setObjectName(_fromUtf8("menuTransform"))
        self.menuCortical_projection = QtGui.QMenu(self.menuTransform)
        self.menuCortical_projection.setObjectName(_fromUtf8("menuCortical_projection"))
        self.menuDisplay = QtGui.QMenu(self.menubar)
        self.menuDisplay.setObjectName(_fromUtf8("menuDisplay"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionCortical_repartition = QtGui.QAction(MainWindow)
        self.actionCortical_repartition.setObjectName(_fromUtf8("actionCortical_repartition"))
        self.actionCortical = QtGui.QAction(MainWindow)
        self.actionCortical.setObjectName(_fromUtf8("actionCortical"))
        self.actionSagittal = QtGui.QAction(MainWindow)
        self.actionSagittal.setObjectName(_fromUtf8("actionSagittal"))
        self.actionAxial = QtGui.QAction(MainWindow)
        self.actionAxial.setObjectName(_fromUtf8("actionAxial"))
        self.actionCamera = QtGui.QAction(MainWindow)
        self.actionCamera.setObjectName(_fromUtf8("actionCamera"))
        self.actionLeft = QtGui.QAction(MainWindow)
        self.actionLeft.setObjectName(_fromUtf8("actionLeft"))
        self.actionRight = QtGui.QAction(MainWindow)
        self.actionRight.setObjectName(_fromUtf8("actionRight"))
        self.actionQuick_settings = QtGui.QAction(MainWindow)
        self.actionQuick_settings.setCheckable(True)
        self.actionQuick_settings.setObjectName(_fromUtf8("actionQuick_settings"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionProjection = QtGui.QAction(MainWindow)
        self.actionProjection.setObjectName(_fromUtf8("actionProjection"))
        self.actionRepartition = QtGui.QAction(MainWindow)
        self.actionRepartition.setObjectName(_fromUtf8("actionRepartition"))
        self.actionShortcuts = QtGui.QAction(MainWindow)
        self.actionShortcuts.setCheckable(True)
        self.actionShortcuts.setObjectName(_fromUtf8("actionShortcuts"))
        self.menuCortical_projection.addAction(self.actionProjection)
        self.menuCortical_projection.addAction(self.actionRepartition)
        self.menuTransform.addAction(self.menuCortical_projection.menuAction())
        self.menuDisplay.addAction(self.actionQuick_settings)
        self.menuDisplay.addAction(self.actionShortcuts)
        self.menubar.addAction(self.menuFiles.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuTransform.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.QuickSettings.setCurrentIndex(1)
        self.toolBox_4.setCurrentIndex(1)
        self.toolBox_2.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        self.toolBox_5.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.bgd_green, self.bgd_blue)
        MainWindow.setTabOrder(self.bgd_blue, self.o_Brain)
        MainWindow.setTabOrder(self.o_Brain, self.o_Sources)
        MainWindow.setTabOrder(self.o_Sources, self.o_Connect)
        MainWindow.setTabOrder(self.o_Connect, self.o_Text)
        MainWindow.setTabOrder(self.o_Text, self.OpacitySlider)
        MainWindow.setTabOrder(self.OpacitySlider, self.xSlices)
        MainWindow.setTabOrder(self.xSlices, self.xInvert)
        MainWindow.setTabOrder(self.xInvert, self.ySlices)
        MainWindow.setTabOrder(self.ySlices, self.yInvert)
        MainWindow.setTabOrder(self.yInvert, self.zSlices)
        MainWindow.setTabOrder(self.zSlices, self.zInvert)
        MainWindow.setTabOrder(self.zInvert, self.q_coronal)
        MainWindow.setTabOrder(self.q_coronal, self.q_axial)
        MainWindow.setTabOrder(self.q_axial, self.q_sagittal)
        MainWindow.setTabOrder(self.q_sagittal, self.c_Turnable)
        MainWindow.setTabOrder(self.c_Turnable, self.show_MNI)
        MainWindow.setTabOrder(self.show_MNI, self.q_internal)
        MainWindow.setTabOrder(self.q_internal, self.q_external)
        MainWindow.setTabOrder(self.q_external, self.show_Sources)
        MainWindow.setTabOrder(self.show_Sources, self.s_LeftH)
        MainWindow.setTabOrder(self.s_LeftH, self.s_Inside)
        MainWindow.setTabOrder(self.s_Inside, self.s_RightH)
        MainWindow.setTabOrder(self.s_RightH, self.s_Outside)
        MainWindow.setTabOrder(self.s_Outside, self.q_stextshow)
        MainWindow.setTabOrder(self.q_stextshow, self.q_stextsize)
        MainWindow.setTabOrder(self.q_stextsize, self.x_text)
        MainWindow.setTabOrder(self.x_text, self.y_text)
        MainWindow.setTabOrder(self.y_text, self.q_stextcolor)
        MainWindow.setTabOrder(self.q_stextcolor, self.z_text)
        MainWindow.setTabOrder(self.z_text, self.q_cmap_list)
        MainWindow.setTabOrder(self.q_cmap_list, self.q_cmap_invert)
        MainWindow.setTabOrder(self.q_cmap_invert, self.q_auto_scale)
        MainWindow.setTabOrder(self.q_auto_scale, self.q_vmin_chk)
        MainWindow.setTabOrder(self.q_vmin_chk, self.q_vmin)
        MainWindow.setTabOrder(self.q_vmin, self.q_vmax_chk)
        MainWindow.setTabOrder(self.q_vmax_chk, self.q_vmax)
        MainWindow.setTabOrder(self.q_vmax, self.q_under_chk)
        MainWindow.setTabOrder(self.q_under_chk, self.q_under)
        MainWindow.setTabOrder(self.q_under, self.q_over_chk)
        MainWindow.setTabOrder(self.q_over_chk, self.q_over)
        MainWindow.setTabOrder(self.q_over, self.q_cblabel)
        MainWindow.setTabOrder(self.q_cblabel, self.bgd_red)
        MainWindow.setTabOrder(self.bgd_red, self.sh_table)
        MainWindow.setTabOrder(self.sh_table, self.QuickSettings)
        MainWindow.setTabOrder(self.QuickSettings, self.q_reload)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "visbrain", None))
        self.QuickSettings.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Background", None))
        self.label.setText(_translate("MainWindow", "Red", None))
        self.label_2.setText(_translate("MainWindow", "Green", None))
        self.label_5.setText(_translate("MainWindow", "Blue", None))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.ui_Settings), _translate("MainWindow", "UI Settings", None))
        self.groupBox.setTitle(_translate("MainWindow", "Select objects to control", None))
        self.o_Brain.setText(_translate("MainWindow", "Brain", None))
        self.o_Sources.setText(_translate("MainWindow", "Sources", None))
        self.o_Connect.setText(_translate("MainWindow", "Connectivity", None))
        self.o_Text.setText(_translate("MainWindow", "Text", None))
        self.o_Areas.setText(_translate("MainWindow", "Areas", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Opacity slider", None))
        self.label_3.setText(_translate("MainWindow", "0", None))
        self.label_4.setText(_translate("MainWindow", "1", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Slices", None))
        self.label_6.setText(_translate("MainWindow", "x-axis", None))
        self.xInvert.setText(_translate("MainWindow", "Invert x", None))
        self.label_7.setText(_translate("MainWindow", "y-axis", None))
        self.yInvert.setText(_translate("MainWindow", "Invert y", None))
        self.label_8.setText(_translate("MainWindow", "z-axis", None))
        self.zInvert.setText(_translate("MainWindow", "Invert z", None))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.ui_Opacity), _translate("MainWindow", "Opacity", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Predefined rotations", None))
        self.q_coronal.setText(_translate("MainWindow", "Coronal", None))
        self.q_axial.setText(_translate("MainWindow", "Axial", None))
        self.q_sagittal.setText(_translate("MainWindow", "Sagittal", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Types of cameras", None))
        self.c_Fly.setText(_translate("MainWindow", "Fly", None))
        self.c_Turnable.setText(_translate("MainWindow", "Turnable", None))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.ui_Camera), _translate("MainWindow", "Camera", None))
        self.grpLightPos.setTitle(_translate("MainWindow", "Light position", None))
        self.grpLightColor.setTitle(_translate("MainWindow", "Light color", None))
        self.grpLightIntensity.setTitle(_translate("MainWindow", "Light intensity", None))
        self.grpLightCoefficient.setTitle(_translate("MainWindow", "Light coefficients", None))
        self.label_9.setText(_translate("MainWindow", "Ambient", None))
        self.label_13.setText(_translate("MainWindow", "Specular", None))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.page_5), _translate("MainWindow", "Light", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_UI), _translate("MainWindow", "UI", None))
        self.q_MNI.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.show_MNI.setText(_translate("MainWindow", "Show", None))
        self.groupBox_14.setTitle(_translate("MainWindow", "Hemisphere", None))
        self.Lhemi_only.setText(_translate("MainWindow", "Left", None))
        self.Both_only.setText(_translate("MainWindow", "Both", None))
        self.Rhemi_only.setText(_translate("MainWindow", "Right", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Apply texture on", None))
        self.q_internal.setText(_translate("MainWindow", "Internal", None))
        self.q_external.setText(_translate("MainWindow", "External", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Brain template", None))
        self.uiSwitchTemplate.setItemText(0, _translate("MainWindow", "B1", None))
        self.uiSwitchTemplate.setItemText(1, _translate("MainWindow", "B2", None))
        self.uiSwitchTemplate.setItemText(2, _translate("MainWindow", "B3", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.pOpacity), _translate("MainWindow", "Display", None))
        self.structEnable.setText(_translate("MainWindow", "Enable", None))
        self.strcutShow.setText(_translate("MainWindow", "Show", None))
        self.groupBox_17.setTitle(_translate("MainWindow", "Projection", None))
        self.struct_Internal.setText(_translate("MainWindow", "Internal", None))
        self.struct_External.setText(_translate("MainWindow", "External", None))
        self.groupBox_15.setTitle(_translate("MainWindow", "Sub-division", None))
        self.Sub_brod.setText(_translate("MainWindow", "Brodmann", None))
        self.Sub_aal.setText(_translate("MainWindow", "AAL", None))
        self.groupBox_16.setTitle(_translate("MainWindow", "Select structures", None))
        self.struct_addLst.setText(_translate("MainWindow", "Add", None))
        self.struct_rstLst.setText(_translate("MainWindow", "Reset", None))
        self.struct_rmvLst.setText(_translate("MainWindow", "Remove", None))
        self.groupBox_19.setTitle(_translate("MainWindow", "Color properties", None))
        self.label_16.setText(_translate("MainWindow", "Color/Colormap", None))
        self.struct_apply.setText(_translate("MainWindow", "Apply", None))
        self.structClear.setText(_translate("MainWindow", "Clear", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.widget), _translate("MainWindow", "Structures", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_MNI), _translate("MainWindow", "MNI", None))
        self.show_Sources.setText(_translate("MainWindow", "Show", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Select sources", None))
        self.s_LeftH.setText(_translate("MainWindow", "Left hemisphere", None))
        self.s_RightH.setText(_translate("MainWindow", "Right hemisphere", None))
        self.s_Inside.setText(_translate("MainWindow", "Inside the brain", None))
        self.s_Outside.setText(_translate("MainWindow", "Outside the brain", None))
        self.grpText.setTitle(_translate("MainWindow", "Text", None))
        self.q_stextshow.setText(_translate("MainWindow", "Show", None))
        self.label_12.setText(_translate("MainWindow", "Fontsize", None))
        self.label_14.setText(_translate("MainWindow", "Color", None))
        self.label_15.setText(_translate("MainWindow", "x", None))
        self.label_17.setText(_translate("MainWindow", "y", None))
        self.label_20.setText(_translate("MainWindow", "z", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Display", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Transformation", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_SOURCES), _translate("MainWindow", "Sources", None))
        self.uiConnectShow.setText(_translate("MainWindow", "Show", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Settings", None))
        self.label_21.setText(_translate("MainWindow", "Color by", None))
        self.uiConnect_colorby.setItemText(0, _translate("MainWindow", "strength", None))
        self.uiConnect_colorby.setItemText(1, _translate("MainWindow", "count", None))
        self.label_22.setText(_translate("MainWindow", "Line width", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Dynamic", None))
        self.uiConnect_static.setText(_translate("MainWindow", "Static", None))
        self.uiConnect_dynamic.setText(_translate("MainWindow", "Dynamic", None))
        self.label_23.setText(_translate("MainWindow", "Min", None))
        self.label_24.setText(_translate("MainWindow", "Max", None))
        self.toolBox_5.setItemText(self.toolBox_5.indexOf(self.page_3), _translate("MainWindow", "Display", None))
        self.toolBox_5.setItemText(self.toolBox_5.indexOf(self.page_4), _translate("MainWindow", "Page 2", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_CONNECT), _translate("MainWindow", "Connectivity", None))
        self.q_cmap_interact.setToolTip(_translate("MainWindow", "<html><head/><body><p>Use this parameter to see colormap changes in live</p></body></html>", None))
        self.q_cmap_interact.setText(_translate("MainWindow", "Process in live", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Apply on", None))
        self.cmapSources.setText(_translate("MainWindow", "Sources", None))
        self.cmapConnect.setText(_translate("MainWindow", "Connectivity", None))
        self.groupBox_13.setTitle(_translate("MainWindow", "Colormap", None))
        self.label_10.setText(_translate("MainWindow", "Colormap", None))
        self.q_cmap_invert.setText(_translate("MainWindow", "Invert", None))
        self.q_auto_scale.setText(_translate("MainWindow", "Auto-scale", None))
        self.q_vmin_chk.setText(_translate("MainWindow", "vmin", None))
        self.q_vmax_chk.setText(_translate("MainWindow", "vmax", None))
        self.q_under_chk.setText(_translate("MainWindow", "Under", None))
        self.q_over_chk.setText(_translate("MainWindow", "Over", None))
        self.label_11.setText(_translate("MainWindow", "Colorbar label: ", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_TRANS), _translate("MainWindow", "Colormap", None))
        self.q_reload.setText(_translate("MainWindow", "Reload", None))
        item = self.sh_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Shortcut panel", None))
        item = self.sh_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Panel Settings", None))
        item = self.sh_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Increase opacity", None))
        item = self.sh_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Decrease opacity", None))
        item = self.sh_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Axial view", None))
        item = self.sh_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Sagittal view", None))
        item = self.sh_table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Coronal view", None))
        item = self.sh_table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Internal/External", None))
        item = self.sh_table.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Cortical projection", None))
        item = self.sh_table.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "Cortical repartition", None))
        item = self.sh_table.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "Screenshot", None))
        item = self.sh_table.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "Save", None))
        item = self.sh_table.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "Load", None))
        item = self.sh_table.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "Quit", None))
        item = self.sh_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Description", None))
        item = self.sh_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Shortcut", None))
        __sortingEnabled = self.sh_table.isSortingEnabled()
        self.sh_table.setSortingEnabled(False)
        item = self.sh_table.item(0, 0)
        item.setText(_translate("MainWindow", "Toggle display the shortcut panel", None))
        item = self.sh_table.item(0, 1)
        item.setText(_translate("MainWindow", "CTRL+T", None))
        item = self.sh_table.item(1, 0)
        item.setText(_translate("MainWindow", "Display the panel settings", None))
        item = self.sh_table.item(1, 1)
        item.setText(_translate("MainWindow", "CTRL+D", None))
        item = self.sh_table.item(2, 0)
        item.setText(_translate("MainWindow", "Increase the opacity of the brain", None))
        item = self.sh_table.item(2, 1)
        item.setText(_translate("MainWindow", "+", None))
        item = self.sh_table.item(3, 0)
        item.setText(_translate("MainWindow", "Decrease the opacity of the brain", None))
        item = self.sh_table.item(3, 1)
        item.setText(_translate("MainWindow", "-", None))
        item = self.sh_table.item(4, 0)
        item.setText(_translate("MainWindow", "Toggle axial view (Top/Bottom)", None))
        item = self.sh_table.item(4, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.sh_table.item(5, 0)
        item.setText(_translate("MainWindow", "Toggle sagittal view (Left/Ritgh)", None))
        item = self.sh_table.item(5, 1)
        item.setText(_translate("MainWindow", "1", None))
        item = self.sh_table.item(6, 0)
        item.setText(_translate("MainWindow", "Toggle coronal view (Front/Back)", None))
        item = self.sh_table.item(6, 1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.sh_table.item(7, 0)
        item.setText(_translate("MainWindow", "Toggle between internal and external projection", None))
        item = self.sh_table.item(7, 1)
        item.setText(_translate("MainWindow", "3", None))
        item = self.sh_table.item(8, 0)
        item.setText(_translate("MainWindow", "If some sources are defined (using s_xyz), project their activity (s_data) onto the brain", None))
        item = self.sh_table.item(8, 1)
        item.setText(_translate("MainWindow", "CTRL+P", None))
        item = self.sh_table.item(9, 0)
        item.setText(_translate("MainWindow", "If some sources are defined (using s_xyz), project their repartition onto the brain", None))
        item = self.sh_table.item(9, 1)
        item.setText(_translate("MainWindow", "CTRL+R", None))
        item = self.sh_table.item(10, 0)
        item.setText(_translate("MainWindow", "Make a screenshot of the current axes", None))
        item = self.sh_table.item(10, 1)
        item.setText(_translate("MainWindow", "CTRL+N", None))
        item = self.sh_table.item(11, 0)
        item.setText(_translate("MainWindow", "Save the current visbrain instance", None))
        item = self.sh_table.item(11, 1)
        item.setText(_translate("MainWindow", "CTRL+S", None))
        item = self.sh_table.item(12, 0)
        item.setText(_translate("MainWindow", "Load a visbrain instance", None))
        item = self.sh_table.item(12, 1)
        item.setText(_translate("MainWindow", "CTRL+O", None))
        item = self.sh_table.item(13, 0)
        item.setText(_translate("MainWindow", "Quit the interface", None))
        item = self.sh_table.item(13, 1)
        item.setText(_translate("MainWindow", "CTRL+Q", None))
        self.sh_table.setSortingEnabled(__sortingEnabled)
        self.menuFiles.setTitle(_translate("MainWindow", "Files", None))
        self.menuTransform.setTitle(_translate("MainWindow", "Transform", None))
        self.menuCortical_projection.setTitle(_translate("MainWindow", "Cortical projection", None))
        self.menuDisplay.setTitle(_translate("MainWindow", "Display", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))
        self.actionCortical_repartition.setText(_translate("MainWindow", "Cortical repartition", None))
        self.actionCortical.setText(_translate("MainWindow", "Cortical", None))
        self.actionSagittal.setText(_translate("MainWindow", "Sagittal", None))
        self.actionAxial.setText(_translate("MainWindow", "Axial", None))
        self.actionCamera.setText(_translate("MainWindow", "Camera", None))
        self.actionLeft.setText(_translate("MainWindow", "Left", None))
        self.actionRight.setText(_translate("MainWindow", "Right", None))
        self.actionQuick_settings.setText(_translate("MainWindow", "Quick settings", None))
        self.actionQuick_settings.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionProjection.setText(_translate("MainWindow", "Projection", None))
        self.actionProjection.setToolTip(_translate("MainWindow", "<html><head/><body><p>Find all vertices under a distance of t_radius with each source and project s_data to the surface</p></body></html>", None))
        self.actionProjection.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.actionRepartition.setText(_translate("MainWindow", "Repartition", None))
        self.actionRepartition.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.actionShortcuts.setText(_translate("MainWindow", "Shortcuts", None))
        self.actionShortcuts.setShortcut(_translate("MainWindow", "Ctrl+T", None))

