# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visbrain_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1239, 924)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.q_widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q_widget.sizePolicy().hasHeightForWidth())
        self.q_widget.setSizePolicy(sizePolicy)
        self.q_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.q_widget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.q_widget.setObjectName(_fromUtf8("q_widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.q_widget)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.QuickSettings = QtGui.QTabWidget(self.q_widget)
        self.QuickSettings.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.QuickSettings.setObjectName(_fromUtf8("QuickSettings"))
        self.q_UI = QtGui.QWidget()
        self.q_UI.setObjectName(_fromUtf8("q_UI"))
        self.verticalLayout = QtGui.QVBoxLayout(self.q_UI)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.toolBox_4 = QtGui.QToolBox(self.q_UI)
        self.toolBox_4.setObjectName(_fromUtf8("toolBox_4"))
        self.ui_Settings = QtGui.QWidget()
        self.ui_Settings.setGeometry(QtCore.QRect(0, 0, 332, 638))
        self.ui_Settings.setObjectName(_fromUtf8("ui_Settings"))
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.ui_Settings)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.verticalLayout_33 = QtGui.QVBoxLayout()
        self.verticalLayout_33.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_33.setObjectName(_fromUtf8("verticalLayout_33"))
        self.groupBox_3 = QtGui.QGroupBox(self.ui_Settings)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 70))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_6.addWidget(self.label)
        self.bgd_red = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.bgd_red.setDecimals(1)
        self.bgd_red.setMaximum(1.0)
        self.bgd_red.setSingleStep(0.1)
        self.bgd_red.setObjectName(_fromUtf8("bgd_red"))
        self.horizontalLayout_6.addWidget(self.bgd_red)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.bgd_green = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.bgd_green.setDecimals(1)
        self.bgd_green.setMaximum(1.0)
        self.bgd_green.setSingleStep(0.1)
        self.bgd_green.setObjectName(_fromUtf8("bgd_green"))
        self.horizontalLayout_6.addWidget(self.bgd_green)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.bgd_blue = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.bgd_blue.setDecimals(1)
        self.bgd_blue.setMaximum(1.0)
        self.bgd_blue.setSingleStep(0.1)
        self.bgd_blue.setObjectName(_fromUtf8("bgd_blue"))
        self.horizontalLayout_6.addWidget(self.bgd_blue)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_33.addWidget(self.groupBox_3)
        self.verticalLayout_25.addLayout(self.verticalLayout_33)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem2)
        self.toolBox_4.addItem(self.ui_Settings, _fromUtf8(""))
        self.ui_Opacity = QtGui.QWidget()
        self.ui_Opacity.setGeometry(QtCore.QRect(0, 0, 281, 649))
        self.ui_Opacity.setObjectName(_fromUtf8("ui_Opacity"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.ui_Opacity)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.groupBox = QtGui.QGroupBox(self.ui_Opacity)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.o_Brain = QtGui.QCheckBox(self.groupBox)
        self.o_Brain.setChecked(True)
        self.o_Brain.setObjectName(_fromUtf8("o_Brain"))
        self.gridLayout_2.addWidget(self.o_Brain, 0, 0, 1, 1)
        self.o_Sources = QtGui.QCheckBox(self.groupBox)
        self.o_Sources.setObjectName(_fromUtf8("o_Sources"))
        self.gridLayout_2.addWidget(self.o_Sources, 0, 1, 1, 1)
        self.o_Connect = QtGui.QCheckBox(self.groupBox)
        self.o_Connect.setObjectName(_fromUtf8("o_Connect"))
        self.gridLayout_2.addWidget(self.o_Connect, 1, 0, 1, 1)
        self.o_Text = QtGui.QCheckBox(self.groupBox)
        self.o_Text.setObjectName(_fromUtf8("o_Text"))
        self.gridLayout_2.addWidget(self.o_Text, 1, 1, 1, 1)
        self.verticalLayout_27.addLayout(self.gridLayout_2)
        self.verticalLayout_19.addWidget(self.groupBox)
        self.groupBox_11 = QtGui.QGroupBox(self.ui_Opacity)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.verticalLayout_35 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_35.setObjectName(_fromUtf8("verticalLayout_35"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.opacity_static = QtGui.QRadioButton(self.groupBox_11)
        self.opacity_static.setChecked(True)
        self.opacity_static.setObjectName(_fromUtf8("opacity_static"))
        self.horizontalLayout_17.addWidget(self.opacity_static)
        self.opacity_dynamic = QtGui.QRadioButton(self.groupBox_11)
        self.opacity_dynamic.setObjectName(_fromUtf8("opacity_dynamic"))
        self.horizontalLayout_17.addWidget(self.opacity_dynamic)
        self.verticalLayout_35.addLayout(self.horizontalLayout_17)
        self.verticalLayout_19.addWidget(self.groupBox_11)
        self.groupBox_9 = QtGui.QGroupBox(self.ui_Opacity)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_32 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_32.setObjectName(_fromUtf8("verticalLayout_32"))
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.OpacitySlider = QtGui.QSlider(self.groupBox_9)
        self.OpacitySlider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.OpacitySlider.setAutoFillBackground(False)
        self.OpacitySlider.setMinimum(-5)
        self.OpacitySlider.setMaximum(105)
        self.OpacitySlider.setPageStep(1)
        self.OpacitySlider.setProperty("value", 50)
        self.OpacitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.OpacitySlider.setInvertedAppearance(False)
        self.OpacitySlider.setInvertedControls(False)
        self.OpacitySlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.OpacitySlider.setObjectName(_fromUtf8("OpacitySlider"))
        self.verticalLayout_24.addWidget(self.OpacitySlider)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_3 = QtGui.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_15.addWidget(self.label_3)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.label_4 = QtGui.QLabel(self.groupBox_9)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setUnderline(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_15.addWidget(self.label_4)
        self.verticalLayout_24.addLayout(self.horizontalLayout_15)
        self.verticalLayout_32.addLayout(self.verticalLayout_24)
        self.verticalLayout_19.addWidget(self.groupBox_9)
        self.groupBox_10 = QtGui.QGroupBox(self.ui_Opacity)
        self.groupBox_10.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_34 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_34.setObjectName(_fromUtf8("verticalLayout_34"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_6 = QtGui.QLabel(self.groupBox_10)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.xSlices = QtGui.QSlider(self.groupBox_10)
        self.xSlices.setMinimum(-110)
        self.xSlices.setMaximum(110)
        self.xSlices.setSingleStep(1)
        self.xSlices.setPageStep(1)
        self.xSlices.setProperty("value", 110)
        self.xSlices.setOrientation(QtCore.Qt.Horizontal)
        self.xSlices.setObjectName(_fromUtf8("xSlices"))
        self.horizontalLayout_12.addWidget(self.xSlices)
        self.xInvert = QtGui.QCheckBox(self.groupBox_10)
        self.xInvert.setObjectName(_fromUtf8("xInvert"))
        self.horizontalLayout_12.addWidget(self.xInvert)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.label_7 = QtGui.QLabel(self.groupBox_10)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.ySlices = QtGui.QSlider(self.groupBox_10)
        self.ySlices.setMinimum(-140)
        self.ySlices.setMaximum(140)
        self.ySlices.setPageStep(1)
        self.ySlices.setProperty("value", 140)
        self.ySlices.setOrientation(QtCore.Qt.Horizontal)
        self.ySlices.setObjectName(_fromUtf8("ySlices"))
        self.horizontalLayout_13.addWidget(self.ySlices)
        self.yInvert = QtGui.QCheckBox(self.groupBox_10)
        self.yInvert.setObjectName(_fromUtf8("yInvert"))
        self.horizontalLayout_13.addWidget(self.yInvert)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.label_8 = QtGui.QLabel(self.groupBox_10)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.zSlices = QtGui.QSlider(self.groupBox_10)
        self.zSlices.setMinimum(-110)
        self.zSlices.setMaximum(110)
        self.zSlices.setPageStep(1)
        self.zSlices.setProperty("value", 110)
        self.zSlices.setOrientation(QtCore.Qt.Horizontal)
        self.zSlices.setObjectName(_fromUtf8("zSlices"))
        self.horizontalLayout_14.addWidget(self.zSlices)
        self.zInvert = QtGui.QCheckBox(self.groupBox_10)
        self.zInvert.setObjectName(_fromUtf8("zInvert"))
        self.horizontalLayout_14.addWidget(self.zInvert)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.verticalLayout_34.addLayout(self.verticalLayout_2)
        self.verticalLayout_19.addWidget(self.groupBox_10)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem4)
        self.verticalLayout_17.addLayout(self.verticalLayout_19)
        self.toolBox_4.addItem(self.ui_Opacity, _fromUtf8(""))
        self.ui_Camera = QtGui.QWidget()
        self.ui_Camera.setGeometry(QtCore.QRect(0, 0, 327, 638))
        self.ui_Camera.setObjectName(_fromUtf8("ui_Camera"))
        self.verticalLayout_30 = QtGui.QVBoxLayout(self.ui_Camera)
        self.verticalLayout_30.setObjectName(_fromUtf8("verticalLayout_30"))
        self.verticalLayout_29 = QtGui.QVBoxLayout()
        self.verticalLayout_29.setObjectName(_fromUtf8("verticalLayout_29"))
        self.groupBox_8 = QtGui.QGroupBox(self.ui_Camera)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_31 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_31.setObjectName(_fromUtf8("verticalLayout_31"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.q_coronal = QtGui.QPushButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.q_coronal.setFont(font)
        self.q_coronal.setAutoDefault(True)
        self.q_coronal.setDefault(True)
        self.q_coronal.setFlat(False)
        self.q_coronal.setObjectName(_fromUtf8("q_coronal"))
        self.horizontalLayout.addWidget(self.q_coronal)
        self.q_axial = QtGui.QPushButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.q_axial.setFont(font)
        self.q_axial.setObjectName(_fromUtf8("q_axial"))
        self.horizontalLayout.addWidget(self.q_axial)
        self.q_sagittal = QtGui.QPushButton(self.groupBox_8)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.q_sagittal.setFont(font)
        self.q_sagittal.setObjectName(_fromUtf8("q_sagittal"))
        self.horizontalLayout.addWidget(self.q_sagittal)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_31.addLayout(self.horizontalLayout)
        self.verticalLayout_29.addWidget(self.groupBox_8)
        self.groupBox_4 = QtGui.QGroupBox(self.ui_Camera)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.c_Turnable = QtGui.QRadioButton(self.groupBox_4)
        self.c_Turnable.setMaximumSize(QtCore.QSize(100, 16777215))
        self.c_Turnable.setChecked(True)
        self.c_Turnable.setObjectName(_fromUtf8("c_Turnable"))
        self.gridLayout.addWidget(self.c_Turnable, 0, 0, 1, 1)
        self.c_Arcball = QtGui.QRadioButton(self.groupBox_4)
        self.c_Arcball.setMaximumSize(QtCore.QSize(100, 16777215))
        self.c_Arcball.setObjectName(_fromUtf8("c_Arcball"))
        self.gridLayout.addWidget(self.c_Arcball, 0, 1, 1, 1)
        self.c_Magnify = QtGui.QRadioButton(self.groupBox_4)
        self.c_Magnify.setMaximumSize(QtCore.QSize(100, 16777215))
        self.c_Magnify.setObjectName(_fromUtf8("c_Magnify"))
        self.gridLayout.addWidget(self.c_Magnify, 1, 0, 1, 1)
        self.c_Fly = QtGui.QRadioButton(self.groupBox_4)
        self.c_Fly.setMaximumSize(QtCore.QSize(100, 16777215))
        self.c_Fly.setObjectName(_fromUtf8("c_Fly"))
        self.gridLayout.addWidget(self.c_Fly, 1, 1, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem7)
        self.verticalLayout_29.addWidget(self.groupBox_4)
        self.verticalLayout_30.addLayout(self.verticalLayout_29)
        self.toolBox_4.addItem(self.ui_Camera, _fromUtf8(""))
        self.verticalLayout.addWidget(self.toolBox_4)
        self.QuickSettings.addTab(self.q_UI, _fromUtf8(""))
        self.q_MNI = QtGui.QWidget()
        self.q_MNI.setObjectName(_fromUtf8("q_MNI"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.q_MNI)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.toolBox_2 = QtGui.QToolBox(self.q_MNI)
        self.toolBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.toolBox_2.setFont(font)
        self.toolBox_2.setObjectName(_fromUtf8("toolBox_2"))
        self.pOpacity = QtGui.QWidget()
        self.pOpacity.setGeometry(QtCore.QRect(0, 0, 281, 680))
        self.pOpacity.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pOpacity.setFont(font)
        self.pOpacity.setObjectName(_fromUtf8("pOpacity"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.pOpacity)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.show_MNI = QtGui.QCheckBox(self.pOpacity)
        self.show_MNI.setChecked(True)
        self.show_MNI.setObjectName(_fromUtf8("show_MNI"))
        self.horizontalLayout_9.addWidget(self.show_MNI)
        self.Lhemi_only = QtGui.QRadioButton(self.pOpacity)
        self.Lhemi_only.setObjectName(_fromUtf8("Lhemi_only"))
        self.horizontalLayout_9.addWidget(self.Lhemi_only)
        self.Rhemi_only = QtGui.QRadioButton(self.pOpacity)
        self.Rhemi_only.setObjectName(_fromUtf8("Rhemi_only"))
        self.horizontalLayout_9.addWidget(self.Rhemi_only)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.verticalLayout_18.addLayout(self.horizontalLayout_9)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.groupBox_2 = QtGui.QGroupBox(self.pOpacity)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 5, -1, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.q_internal = QtGui.QRadioButton(self.groupBox_2)
        self.q_internal.setObjectName(_fromUtf8("q_internal"))
        self.horizontalLayout_8.addWidget(self.q_internal)
        self.q_external = QtGui.QRadioButton(self.groupBox_2)
        self.q_external.setObjectName(_fromUtf8("q_external"))
        self.horizontalLayout_8.addWidget(self.q_external)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_8)
        self.verticalLayout_12.addWidget(self.groupBox_2)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem12)
        self.verticalLayout_18.addLayout(self.verticalLayout_12)
        self.toolBox_2.addItem(self.pOpacity, _fromUtf8(""))
        self.pSlice = QtGui.QWidget()
        self.pSlice.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.pSlice.setObjectName(_fromUtf8("pSlice"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.pSlice)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.toolBox_2.addItem(self.pSlice, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.toolBox_2)
        self.QuickSettings.addTab(self.q_MNI, _fromUtf8(""))
        self.q_SOURCES = QtGui.QWidget()
        self.q_SOURCES.setObjectName(_fromUtf8("q_SOURCES"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.q_SOURCES)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.toolBox = QtGui.QToolBox(self.q_SOURCES)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 348, 669))
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_5 = QtGui.QGroupBox(self.page)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem13)
        self.show_Sources = QtGui.QCheckBox(self.groupBox_5)
        self.show_Sources.setChecked(True)
        self.show_Sources.setObjectName(_fromUtf8("show_Sources"))
        self.horizontalLayout_16.addWidget(self.show_Sources)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem14)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.widget = QtGui.QWidget(self.groupBox_5)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.s_LeftH = QtGui.QRadioButton(self.widget)
        self.s_LeftH.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.s_LeftH.setAutoExclusive(True)
        self.s_LeftH.setObjectName(_fromUtf8("s_LeftH"))
        self.verticalLayout_8.addWidget(self.s_LeftH)
        self.s_RightH = QtGui.QRadioButton(self.widget)
        self.s_RightH.setObjectName(_fromUtf8("s_RightH"))
        self.verticalLayout_8.addWidget(self.s_RightH)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.horizontalLayout_10.addWidget(self.widget)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_10)
        self.widget_2 = QtGui.QWidget(self.groupBox_5)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.s_Inside = QtGui.QRadioButton(self.widget_2)
        self.s_Inside.setObjectName(_fromUtf8("s_Inside"))
        self.verticalLayout_10.addWidget(self.s_Inside)
        self.s_Outside = QtGui.QRadioButton(self.widget_2)
        self.s_Outside.setObjectName(_fromUtf8("s_Outside"))
        self.verticalLayout_10.addWidget(self.s_Outside)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.horizontalLayout_5.addWidget(self.widget_2)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_19.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.page)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.q_stextshow = QtGui.QCheckBox(self.groupBox_6)
        self.q_stextshow.setObjectName(_fromUtf8("q_stextshow"))
        self.verticalLayout_16.addWidget(self.q_stextshow)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_23.setSpacing(6)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_23.addWidget(self.label_12)
        self.q_stextsize = QtGui.QSpinBox(self.groupBox_6)
        self.q_stextsize.setProperty("value", 3)
        self.q_stextsize.setObjectName(_fromUtf8("q_stextsize"))
        self.horizontalLayout_23.addWidget(self.q_stextsize)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem17)
        self.label_14 = QtGui.QLabel(self.groupBox_6)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_23.addWidget(self.label_14)
        self.q_stextcolor = QtGui.QLineEdit(self.groupBox_6)
        self.q_stextcolor.setObjectName(_fromUtf8("q_stextcolor"))
        self.horizontalLayout_23.addWidget(self.q_stextcolor)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem18)
        self.verticalLayout_16.addLayout(self.horizontalLayout_23)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem19)
        self.label_15 = QtGui.QLabel(self.groupBox_6)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_28.addWidget(self.label_15)
        self.x_text = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.x_text.setMinimum(-100.0)
        self.x_text.setMaximum(100.0)
        self.x_text.setObjectName(_fromUtf8("x_text"))
        self.horizontalLayout_28.addWidget(self.x_text)
        self.label_17 = QtGui.QLabel(self.groupBox_6)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_28.addWidget(self.label_17)
        self.y_text = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.y_text.setMinimum(-100.0)
        self.y_text.setMaximum(100.0)
        self.y_text.setObjectName(_fromUtf8("y_text"))
        self.horizontalLayout_28.addWidget(self.y_text)
        self.label_20 = QtGui.QLabel(self.groupBox_6)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_28.addWidget(self.label_20)
        self.z_text = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.z_text.setMinimum(-100.0)
        self.z_text.setMaximum(100.0)
        self.z_text.setObjectName(_fromUtf8("z_text"))
        self.horizontalLayout_28.addWidget(self.z_text)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem20)
        self.verticalLayout_15.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_22.addLayout(self.verticalLayout_15)
        self.verticalLayout_7.addWidget(self.groupBox_6)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem21)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.toolBox)
        self.QuickSettings.addTab(self.q_SOURCES, _fromUtf8(""))
        self.q_CONNECT = QtGui.QWidget()
        self.q_CONNECT.setObjectName(_fromUtf8("q_CONNECT"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.q_CONNECT)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.toolBox_5 = QtGui.QToolBox(self.q_CONNECT)
        self.toolBox_5.setObjectName(_fromUtf8("toolBox_5"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 281, 680))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.toolBox_5.addItem(self.page_3, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.toolBox_5.addItem(self.page_4, _fromUtf8(""))
        self.verticalLayout_13.addWidget(self.toolBox_5)
        self.QuickSettings.addTab(self.q_CONNECT, _fromUtf8(""))
        self.q_TRANS = QtGui.QWidget()
        self.q_TRANS.setObjectName(_fromUtf8("q_TRANS"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.q_TRANS)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.toolBox_3 = QtGui.QToolBox(self.q_TRANS)
        self.toolBox_3.setObjectName(_fromUtf8("toolBox_3"))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 384, 638))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.page_5)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.q_cmap_interact = QtGui.QCheckBox(self.page_5)
        self.q_cmap_interact.setChecked(False)
        self.q_cmap_interact.setObjectName(_fromUtf8("q_cmap_interact"))
        self.verticalLayout_22.addWidget(self.q_cmap_interact)
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.line_2 = QtGui.QFrame(self.page_5)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_21.addWidget(self.line_2)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_10 = QtGui.QLabel(self.page_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_18.addWidget(self.label_10)
        self.q_cmap_list = QtGui.QComboBox(self.page_5)
        self.q_cmap_list.setEditable(False)
        self.q_cmap_list.setObjectName(_fromUtf8("q_cmap_list"))
        self.horizontalLayout_18.addWidget(self.q_cmap_list)
        self.q_cmap_invert = QtGui.QCheckBox(self.page_5)
        self.q_cmap_invert.setObjectName(_fromUtf8("q_cmap_invert"))
        self.horizontalLayout_18.addWidget(self.q_cmap_invert)
        self.q_auto_scale = QtGui.QCheckBox(self.page_5)
        self.q_auto_scale.setObjectName(_fromUtf8("q_auto_scale"))
        self.horizontalLayout_18.addWidget(self.q_auto_scale)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem22)
        self.verticalLayout_21.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.q_vmin_chk = QtGui.QCheckBox(self.page_5)
        self.q_vmin_chk.setObjectName(_fromUtf8("q_vmin_chk"))
        self.horizontalLayout_20.addWidget(self.q_vmin_chk)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem23)
        self.q_vmin = QtGui.QDoubleSpinBox(self.page_5)
        self.q_vmin.setMinimum(-16777215.0)
        self.q_vmin.setMaximum(16777215.0)
        self.q_vmin.setSingleStep(1.0)
        self.q_vmin.setObjectName(_fromUtf8("q_vmin"))
        self.horizontalLayout_20.addWidget(self.q_vmin)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem24)
        self.q_vmax_chk = QtGui.QCheckBox(self.page_5)
        self.q_vmax_chk.setObjectName(_fromUtf8("q_vmax_chk"))
        self.horizontalLayout_20.addWidget(self.q_vmax_chk)
        self.q_vmax = QtGui.QDoubleSpinBox(self.page_5)
        self.q_vmax.setMinimum(-16777215.0)
        self.q_vmax.setMaximum(16777215.0)
        self.q_vmax.setObjectName(_fromUtf8("q_vmax"))
        self.horizontalLayout_20.addWidget(self.q_vmax)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem25)
        self.verticalLayout_21.addLayout(self.horizontalLayout_20)
        self.label_16 = QtGui.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_21.addWidget(self.label_16)
        self.label_18 = QtGui.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_21.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_21.addWidget(self.label_19)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.q_under_chk = QtGui.QCheckBox(self.page_5)
        self.q_under_chk.setObjectName(_fromUtf8("q_under_chk"))
        self.horizontalLayout_21.addWidget(self.q_under_chk)
        self.q_under = QtGui.QLineEdit(self.page_5)
        self.q_under.setObjectName(_fromUtf8("q_under"))
        self.horizontalLayout_21.addWidget(self.q_under)
        self.q_over_chk = QtGui.QCheckBox(self.page_5)
        self.q_over_chk.setObjectName(_fromUtf8("q_over_chk"))
        self.horizontalLayout_21.addWidget(self.q_over_chk)
        self.q_over = QtGui.QLineEdit(self.page_5)
        self.q_over.setObjectName(_fromUtf8("q_over"))
        self.horizontalLayout_21.addWidget(self.q_over)
        self.verticalLayout_21.addLayout(self.horizontalLayout_21)
        self.line = QtGui.QFrame(self.page_5)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_21.addWidget(self.line)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_11 = QtGui.QLabel(self.page_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_25.addWidget(self.label_11)
        self.q_cblabel = QtGui.QLineEdit(self.page_5)
        self.q_cblabel.setObjectName(_fromUtf8("q_cblabel"))
        self.horizontalLayout_25.addWidget(self.q_cblabel)
        self.verticalLayout_21.addLayout(self.horizontalLayout_25)
        self.cbpanel = QtGui.QVBoxLayout()
        self.cbpanel.setContentsMargins(-1, 0, -1, 0)
        self.cbpanel.setSpacing(0)
        self.cbpanel.setObjectName(_fromUtf8("cbpanel"))
        spacerItem26 = QtGui.QSpacerItem(100, 200, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.cbpanel.addItem(spacerItem26)
        self.verticalLayout_21.addLayout(self.cbpanel)
        self.verticalLayout_22.addLayout(self.verticalLayout_21)
        self.toolBox_3.addItem(self.page_5, _fromUtf8(""))
        self.page_7 = QtGui.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 281, 649))
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.page_7)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.horizontalLayout_26.addLayout(self.verticalLayout_28)
        self.toolBox_3.addItem(self.page_7, _fromUtf8(""))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 281, 649))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.toolBox_3.addItem(self.page_6, _fromUtf8(""))
        self.verticalLayout_23.addWidget(self.toolBox_3)
        self.QuickSettings.addTab(self.q_TRANS, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.QuickSettings)
        self.progressBar = QtGui.QProgressBar(self.q_widget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_4.addWidget(self.progressBar)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem27)
        self.q_reload = QtGui.QPushButton(self.q_widget)
        self.q_reload.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.q_reload.setObjectName(_fromUtf8("q_reload"))
        self.horizontalLayout_11.addWidget(self.q_reload)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem28)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_2.addWidget(self.q_widget)
        self.vBrain = QtGui.QVBoxLayout()
        self.vBrain.setSpacing(0)
        self.vBrain.setObjectName(_fromUtf8("vBrain"))
        spacerItem29 = QtGui.QSpacerItem(800, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.vBrain.addItem(spacerItem29)
        self.horizontalLayout_2.addLayout(self.vBrain)
        self.table_panel = QtGui.QWidget(self.centralwidget)
        self.table_panel.setEnabled(True)
        self.table_panel.setMinimumSize(QtCore.QSize(0, 0))
        self.table_panel.setMaximumSize(QtCore.QSize(400, 16777215))
        self.table_panel.setObjectName(_fromUtf8("table_panel"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.table_panel)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.sh_table = QtGui.QTableWidget(self.table_panel)
        self.sh_table.setMinimumSize(QtCore.QSize(0, 0))
        self.sh_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sh_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.sh_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.sh_table.setObjectName(_fromUtf8("sh_table"))
        self.sh_table.setColumnCount(2)
        self.sh_table.setRowCount(14)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(9, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(10, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(10, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(11, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(11, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(12, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(12, 1, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(13, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sh_table.setItem(13, 1, item)
        self.horizontalLayout_3.addWidget(self.sh_table)
        self.horizontalLayout_2.addWidget(self.table_panel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1239, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFiles = QtGui.QMenu(self.menubar)
        self.menuFiles.setObjectName(_fromUtf8("menuFiles"))
        self.menuTransform = QtGui.QMenu(self.menubar)
        self.menuTransform.setObjectName(_fromUtf8("menuTransform"))
        self.menuCortical_projection = QtGui.QMenu(self.menuTransform)
        self.menuCortical_projection.setObjectName(_fromUtf8("menuCortical_projection"))
        self.menuDisplay = QtGui.QMenu(self.menubar)
        self.menuDisplay.setObjectName(_fromUtf8("menuDisplay"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionCortical_repartition = QtGui.QAction(MainWindow)
        self.actionCortical_repartition.setObjectName(_fromUtf8("actionCortical_repartition"))
        self.actionCortical = QtGui.QAction(MainWindow)
        self.actionCortical.setObjectName(_fromUtf8("actionCortical"))
        self.actionSagittal = QtGui.QAction(MainWindow)
        self.actionSagittal.setObjectName(_fromUtf8("actionSagittal"))
        self.actionAxial = QtGui.QAction(MainWindow)
        self.actionAxial.setObjectName(_fromUtf8("actionAxial"))
        self.actionCamera = QtGui.QAction(MainWindow)
        self.actionCamera.setObjectName(_fromUtf8("actionCamera"))
        self.actionLeft = QtGui.QAction(MainWindow)
        self.actionLeft.setObjectName(_fromUtf8("actionLeft"))
        self.actionRight = QtGui.QAction(MainWindow)
        self.actionRight.setObjectName(_fromUtf8("actionRight"))
        self.actionQuick_settings = QtGui.QAction(MainWindow)
        self.actionQuick_settings.setCheckable(True)
        self.actionQuick_settings.setObjectName(_fromUtf8("actionQuick_settings"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionProjection = QtGui.QAction(MainWindow)
        self.actionProjection.setObjectName(_fromUtf8("actionProjection"))
        self.actionRepartition = QtGui.QAction(MainWindow)
        self.actionRepartition.setObjectName(_fromUtf8("actionRepartition"))
        self.actionShortcuts = QtGui.QAction(MainWindow)
        self.actionShortcuts.setCheckable(True)
        self.actionShortcuts.setObjectName(_fromUtf8("actionShortcuts"))
        self.menuCortical_projection.addAction(self.actionProjection)
        self.menuCortical_projection.addAction(self.actionRepartition)
        self.menuTransform.addAction(self.menuCortical_projection.menuAction())
        self.menuDisplay.addAction(self.actionQuick_settings)
        self.menuDisplay.addAction(self.actionShortcuts)
        self.menubar.addAction(self.menuFiles.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuTransform.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.QuickSettings.setCurrentIndex(4)
        self.toolBox_4.setCurrentIndex(1)
        self.toolBox_2.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.toolBox_5.setCurrentIndex(0)
        self.toolBox_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.bgd_green, self.bgd_blue)
        MainWindow.setTabOrder(self.bgd_blue, self.o_Brain)
        MainWindow.setTabOrder(self.o_Brain, self.o_Sources)
        MainWindow.setTabOrder(self.o_Sources, self.o_Connect)
        MainWindow.setTabOrder(self.o_Connect, self.o_Text)
        MainWindow.setTabOrder(self.o_Text, self.OpacitySlider)
        MainWindow.setTabOrder(self.OpacitySlider, self.xSlices)
        MainWindow.setTabOrder(self.xSlices, self.xInvert)
        MainWindow.setTabOrder(self.xInvert, self.ySlices)
        MainWindow.setTabOrder(self.ySlices, self.yInvert)
        MainWindow.setTabOrder(self.yInvert, self.zSlices)
        MainWindow.setTabOrder(self.zSlices, self.zInvert)
        MainWindow.setTabOrder(self.zInvert, self.q_coronal)
        MainWindow.setTabOrder(self.q_coronal, self.q_axial)
        MainWindow.setTabOrder(self.q_axial, self.q_sagittal)
        MainWindow.setTabOrder(self.q_sagittal, self.c_Turnable)
        MainWindow.setTabOrder(self.c_Turnable, self.c_Arcball)
        MainWindow.setTabOrder(self.c_Arcball, self.c_Magnify)
        MainWindow.setTabOrder(self.c_Magnify, self.c_Fly)
        MainWindow.setTabOrder(self.c_Fly, self.show_MNI)
        MainWindow.setTabOrder(self.show_MNI, self.Lhemi_only)
        MainWindow.setTabOrder(self.Lhemi_only, self.Rhemi_only)
        MainWindow.setTabOrder(self.Rhemi_only, self.q_internal)
        MainWindow.setTabOrder(self.q_internal, self.q_external)
        MainWindow.setTabOrder(self.q_external, self.show_Sources)
        MainWindow.setTabOrder(self.show_Sources, self.s_LeftH)
        MainWindow.setTabOrder(self.s_LeftH, self.s_Inside)
        MainWindow.setTabOrder(self.s_Inside, self.s_RightH)
        MainWindow.setTabOrder(self.s_RightH, self.s_Outside)
        MainWindow.setTabOrder(self.s_Outside, self.q_stextshow)
        MainWindow.setTabOrder(self.q_stextshow, self.q_stextsize)
        MainWindow.setTabOrder(self.q_stextsize, self.x_text)
        MainWindow.setTabOrder(self.x_text, self.y_text)
        MainWindow.setTabOrder(self.y_text, self.q_stextcolor)
        MainWindow.setTabOrder(self.q_stextcolor, self.z_text)
        MainWindow.setTabOrder(self.z_text, self.q_cmap_interact)
        MainWindow.setTabOrder(self.q_cmap_interact, self.q_cmap_list)
        MainWindow.setTabOrder(self.q_cmap_list, self.q_cmap_invert)
        MainWindow.setTabOrder(self.q_cmap_invert, self.q_auto_scale)
        MainWindow.setTabOrder(self.q_auto_scale, self.q_vmin_chk)
        MainWindow.setTabOrder(self.q_vmin_chk, self.q_vmin)
        MainWindow.setTabOrder(self.q_vmin, self.q_vmax_chk)
        MainWindow.setTabOrder(self.q_vmax_chk, self.q_vmax)
        MainWindow.setTabOrder(self.q_vmax, self.q_under_chk)
        MainWindow.setTabOrder(self.q_under_chk, self.q_under)
        MainWindow.setTabOrder(self.q_under, self.q_over_chk)
        MainWindow.setTabOrder(self.q_over_chk, self.q_over)
        MainWindow.setTabOrder(self.q_over, self.q_cblabel)
        MainWindow.setTabOrder(self.q_cblabel, self.bgd_red)
        MainWindow.setTabOrder(self.bgd_red, self.sh_table)
        MainWindow.setTabOrder(self.sh_table, self.QuickSettings)
        MainWindow.setTabOrder(self.QuickSettings, self.q_reload)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "visbrain", None))
        self.QuickSettings.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Background", None))
        self.label.setText(_translate("MainWindow", "Red", None))
        self.label_2.setText(_translate("MainWindow", "Green", None))
        self.label_5.setText(_translate("MainWindow", "Blue", None))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.ui_Settings), _translate("MainWindow", "UI Settings", None))
        self.groupBox.setTitle(_translate("MainWindow", "Select objects to control", None))
        self.o_Brain.setText(_translate("MainWindow", "Brain", None))
        self.o_Sources.setText(_translate("MainWindow", "Sources", None))
        self.o_Connect.setText(_translate("MainWindow", "Connectivity", None))
        self.o_Text.setText(_translate("MainWindow", "Text", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Static or dynamic opacity", None))
        self.opacity_static.setText(_translate("MainWindow", "Static", None))
        self.opacity_dynamic.setText(_translate("MainWindow", "Dynamic", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Opacity slider", None))
        self.label_3.setText(_translate("MainWindow", "0", None))
        self.label_4.setText(_translate("MainWindow", "1", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Slices", None))
        self.label_6.setText(_translate("MainWindow", "x-axis", None))
        self.xInvert.setText(_translate("MainWindow", "Invert x", None))
        self.label_7.setText(_translate("MainWindow", "y-axis", None))
        self.yInvert.setText(_translate("MainWindow", "Invert y", None))
        self.label_8.setText(_translate("MainWindow", "z-axis", None))
        self.zInvert.setText(_translate("MainWindow", "Invert z", None))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.ui_Opacity), _translate("MainWindow", "Opacity", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Predefined rotations", None))
        self.q_coronal.setText(_translate("MainWindow", "Coronal", None))
        self.q_axial.setText(_translate("MainWindow", "Axial", None))
        self.q_sagittal.setText(_translate("MainWindow", "Sagittal", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Types of cameras", None))
        self.c_Turnable.setText(_translate("MainWindow", "Turnable", None))
        self.c_Arcball.setText(_translate("MainWindow", "Arcball", None))
        self.c_Magnify.setText(_translate("MainWindow", "Magnify", None))
        self.c_Fly.setText(_translate("MainWindow", "Fly", None))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.ui_Camera), _translate("MainWindow", "Camera", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_UI), _translate("MainWindow", "UI", None))
        self.q_MNI.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.show_MNI.setText(_translate("MainWindow", "Show", None))
        self.Lhemi_only.setText(_translate("MainWindow", "Left", None))
        self.Rhemi_only.setText(_translate("MainWindow", "Right", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Apply texture on", None))
        self.q_internal.setText(_translate("MainWindow", "Internal", None))
        self.q_external.setText(_translate("MainWindow", "External", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.pOpacity), _translate("MainWindow", "Display", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.pSlice), _translate("MainWindow", "Slice", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_MNI), _translate("MainWindow", "MNI", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Select sources", None))
        self.show_Sources.setText(_translate("MainWindow", "Show", None))
        self.s_LeftH.setText(_translate("MainWindow", "Left hemisphere", None))
        self.s_RightH.setText(_translate("MainWindow", "Right hemisphere", None))
        self.s_Inside.setText(_translate("MainWindow", "Inside the brain", None))
        self.s_Outside.setText(_translate("MainWindow", "Outside the brain", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Text", None))
        self.q_stextshow.setText(_translate("MainWindow", "Show", None))
        self.label_12.setText(_translate("MainWindow", "Fontsize", None))
        self.label_14.setText(_translate("MainWindow", "Color", None))
        self.label_15.setText(_translate("MainWindow", "x", None))
        self.label_17.setText(_translate("MainWindow", "y", None))
        self.label_20.setText(_translate("MainWindow", "z", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Display", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Page 2", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_SOURCES), _translate("MainWindow", "Sources", None))
        self.toolBox_5.setItemText(self.toolBox_5.indexOf(self.page_3), _translate("MainWindow", "Page 1", None))
        self.toolBox_5.setItemText(self.toolBox_5.indexOf(self.page_4), _translate("MainWindow", "Page 2", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_CONNECT), _translate("MainWindow", "Connectivity", None))
        self.q_cmap_interact.setToolTip(_translate("MainWindow", "<html><head/><body><p>Use this parameter to see colormap changes in live</p></body></html>", None))
        self.q_cmap_interact.setText(_translate("MainWindow", "See live changement of colormap settings", None))
        self.label_10.setText(_translate("MainWindow", "Colormap", None))
        self.q_cmap_invert.setText(_translate("MainWindow", "Invert", None))
        self.q_auto_scale.setText(_translate("MainWindow", "Auto-scale", None))
        self.q_vmin_chk.setText(_translate("MainWindow", "vmin", None))
        self.q_vmax_chk.setText(_translate("MainWindow", "vmax", None))
        self.label_16.setText(_translate("MainWindow", "For the choice of color under vmin and over vmax, use", None))
        self.label_18.setText(_translate("MainWindow", "matplotlib predifined colors (ex: \'red\', \'green\'...) of hexadecimal", None))
        self.label_19.setText(_translate("MainWindow", "(ex: \"#9b59b6\", \"#3498db\", \"#95a5a6\"... )", None))
        self.q_under_chk.setText(_translate("MainWindow", "Under", None))
        self.q_over_chk.setText(_translate("MainWindow", "Over", None))
        self.label_11.setText(_translate("MainWindow", "Colorbar label: ", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_5), _translate("MainWindow", "Colormap", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_7), _translate("MainWindow", "Colorbar", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_6), _translate("MainWindow", "Settings", None))
        self.QuickSettings.setTabText(self.QuickSettings.indexOf(self.q_TRANS), _translate("MainWindow", "Transformation", None))
        self.q_reload.setText(_translate("MainWindow", "Reload", None))
        item = self.sh_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Shortcut panel", None))
        item = self.sh_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Panel Settings", None))
        item = self.sh_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Increase opacity", None))
        item = self.sh_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Decrease opacity", None))
        item = self.sh_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Axial view", None))
        item = self.sh_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Sagittal view", None))
        item = self.sh_table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Coronal view", None))
        item = self.sh_table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Internal/External", None))
        item = self.sh_table.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Cortical projection", None))
        item = self.sh_table.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "Cortical repartition", None))
        item = self.sh_table.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "Screenshot", None))
        item = self.sh_table.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "Save", None))
        item = self.sh_table.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "Load", None))
        item = self.sh_table.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "Quit", None))
        item = self.sh_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Description", None))
        item = self.sh_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Shortcut", None))
        __sortingEnabled = self.sh_table.isSortingEnabled()
        self.sh_table.setSortingEnabled(False)
        item = self.sh_table.item(0, 0)
        item.setText(_translate("MainWindow", "Toggle display the shortcut panel", None))
        item = self.sh_table.item(0, 1)
        item.setText(_translate("MainWindow", "CTRL+T", None))
        item = self.sh_table.item(1, 0)
        item.setText(_translate("MainWindow", "Display the panel settings", None))
        item = self.sh_table.item(1, 1)
        item.setText(_translate("MainWindow", "CTRL+D", None))
        item = self.sh_table.item(2, 0)
        item.setText(_translate("MainWindow", "Increase the opacity of the brain", None))
        item = self.sh_table.item(2, 1)
        item.setText(_translate("MainWindow", "+", None))
        item = self.sh_table.item(3, 0)
        item.setText(_translate("MainWindow", "Decrease the opacity of the brain", None))
        item = self.sh_table.item(3, 1)
        item.setText(_translate("MainWindow", "-", None))
        item = self.sh_table.item(4, 0)
        item.setText(_translate("MainWindow", "Toggle axial view (Top/Bottom)", None))
        item = self.sh_table.item(4, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.sh_table.item(5, 0)
        item.setText(_translate("MainWindow", "Toggle sagittal view (Left/Ritgh)", None))
        item = self.sh_table.item(5, 1)
        item.setText(_translate("MainWindow", "1", None))
        item = self.sh_table.item(6, 0)
        item.setText(_translate("MainWindow", "Toggle coronal view (Front/Back)", None))
        item = self.sh_table.item(6, 1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.sh_table.item(7, 0)
        item.setText(_translate("MainWindow", "Toggle between internal and external projection", None))
        item = self.sh_table.item(7, 1)
        item.setText(_translate("MainWindow", "3", None))
        item = self.sh_table.item(8, 0)
        item.setText(_translate("MainWindow", "If some sources are defined (using s_xyz), project their activity (s_data) onto the brain", None))
        item = self.sh_table.item(8, 1)
        item.setText(_translate("MainWindow", "CTRL+P", None))
        item = self.sh_table.item(9, 0)
        item.setText(_translate("MainWindow", "If some sources are defined (using s_xyz), project their repartition onto the brain", None))
        item = self.sh_table.item(9, 1)
        item.setText(_translate("MainWindow", "CTRL+R", None))
        item = self.sh_table.item(10, 0)
        item.setText(_translate("MainWindow", "Make a screenshot of the current axes", None))
        item = self.sh_table.item(10, 1)
        item.setText(_translate("MainWindow", "CTRL+N", None))
        item = self.sh_table.item(11, 0)
        item.setText(_translate("MainWindow", "Save the current visbrain instance", None))
        item = self.sh_table.item(11, 1)
        item.setText(_translate("MainWindow", "CTRL+S", None))
        item = self.sh_table.item(12, 0)
        item.setText(_translate("MainWindow", "Load a visbrain instance", None))
        item = self.sh_table.item(12, 1)
        item.setText(_translate("MainWindow", "CTRL+O", None))
        item = self.sh_table.item(13, 0)
        item.setText(_translate("MainWindow", "Quit the interface", None))
        item = self.sh_table.item(13, 1)
        item.setText(_translate("MainWindow", "CTRL+Q", None))
        self.sh_table.setSortingEnabled(__sortingEnabled)
        self.menuFiles.setTitle(_translate("MainWindow", "Files", None))
        self.menuTransform.setTitle(_translate("MainWindow", "Transform", None))
        self.menuCortical_projection.setTitle(_translate("MainWindow", "Cortical projection", None))
        self.menuDisplay.setTitle(_translate("MainWindow", "Display", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))
        self.actionCortical_repartition.setText(_translate("MainWindow", "Cortical repartition", None))
        self.actionCortical.setText(_translate("MainWindow", "Cortical", None))
        self.actionSagittal.setText(_translate("MainWindow", "Sagittal", None))
        self.actionAxial.setText(_translate("MainWindow", "Axial", None))
        self.actionCamera.setText(_translate("MainWindow", "Camera", None))
        self.actionLeft.setText(_translate("MainWindow", "Left", None))
        self.actionRight.setText(_translate("MainWindow", "Right", None))
        self.actionQuick_settings.setText(_translate("MainWindow", "Quick settings", None))
        self.actionQuick_settings.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionProjection.setText(_translate("MainWindow", "Projection", None))
        self.actionProjection.setToolTip(_translate("MainWindow", "<html><head/><body><p>Find all vertices under a distance of t_radius with each source and project s_data to the surface</p></body></html>", None))
        self.actionProjection.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.actionRepartition.setText(_translate("MainWindow", "Repartition", None))
        self.actionRepartition.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.actionShortcuts.setText(_translate("MainWindow", "Shortcuts", None))
        self.actionShortcuts.setShortcut(_translate("MainWindow", "Ctrl+T", None))

